obot-platform/obot

Dockerfile
alternatively to setting the PATH env, we could link only the soffice executable
=> feat: add libreoffice to the docker image (to be used by knowledge)

docs/docs/03-guides/01-first-tool.md, docs/docs/03-guides/01-first-tool.mdx, docs/docs/03-guides/03-workflows.md, docs/docusaurus.config.ts, docs/package-lock.json, docs/package.json, docs/snippets/go-hash-tool-readme.md.mdx, docs/snippets/node-hash-tool-readme.md.mdx, docs/snippets/python-hash-tool-readme.md.mdx, docs/src/plugins/fetch-snippets/index.ts
Add the `Writing your First Tool` guide with instructions for authoring and publishing Tools written in `Python`, `Node.JS`, and `Go`.
=> doc: add multi-language guide for authoring and packaging tools

apiclient/types/assitant.go, pkg/api/handlers/assistants.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentPublishStatus.tsx, ui/admin/app/components/agent/Publish.tsx, ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/Unpublish.tsx, ui/admin/app/lib/model/agents.ts, ui/admin/app/lib/model/assistants.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/assistantApiService.ts, ui/admin/app/routes/_auth.agents.$agent.tsx
=> feat: admin ui - display information on agent when refName conflict

ui/admin/app/components/header/HeaderNav.tsx, ui/admin/app/hooks/useRouteInfo.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.thread.$id.tsx, ui/admin/app/routes/_auth.threads.tsx
Updates Typesafe Routing in admin ui
- Updates to Routes will have to be made in `routeService.ts`
- all query params are defined as zod schemas in `QuerySchemas` const
- linter will fail if no route helper object is provided for a given url
=> chore: update typesafe routing for admin ui

ui/admin/app/components/agent/Publish.tsx, ui/admin/app/components/oauth-apps/OAuthAppForm.tsx
Prior to this change, the spacing cut off the border on the x-axis. This change makes a little space, so the border highlighting appears all the way around.
Issue: https://github.com/otto8-ai/otto8/issues/612
=> fix: add padding to oauth app forms

apiclient/types/webhook.go, pkg/api/handlers/webhooks.go
This change also adds a HasToken field to the API since the API doesn't return the hashed token.
=> chore: change webhook password field to token

pkg/gateway/server/dispatcher/dispatcher.go, pkg/gateway/server/llmproxy.go
This change also creates a single thread when running model providers.
=> fix: use run namespace to get models in llm proxy

ui/admin/app/components/oauth-apps/custom/CustomOAuthAppForm.tsx
The border for the focused form input will be completely visible with this padding.
Issue: https://github.com/otto8-ai/otto8/issues/624
=> chore: add padding to custom oauth app form

docs/docs/03-guides/01-first-tool.mdx, docs/snippets/go-hash-tool-readme.md.mdx, docs/snippets/node-hash-tool-readme.md.mdx, docs/snippets/python-hash-tool-readme.md.mdx, docs/src/plugins/fetch-snippets/index.ts
- The default table of contents is incompatible with tabs, so remove it
from the first-tool guide
- Auto-generated IDs for markdown headers in the first-tool page aren't
unique, so generate unique IDs and inject them at snippet fetch time
- Re-fetch latest README.md files from `*-hash-tool` repos to fix
guide doc formatting issues
=> docs: remove toc from first tool guide and add unique ids to markdown headers

apiclient/types/knowledgesource.go, pkg/api/handlers/knowledgesource.go, pkg/controller/handlers/knowledgefile/knowledgefile.go, ui/admin/app/components/knowledge/FileTree.tsx, ui/admin/app/components/knowledge/KnowledgeSourceDetail.tsx, ui/admin/app/components/ui/collapsible.tsx, ui/admin/app/lib/model/knowledge.ts, ui/admin/package.json, ui/admin/pnpm-lock.yaml
This PR add file tree to show knowledge files. Demo is here https://www.loom.com/share/0e707405c1194ea1a9a1ffd595347a22 
It also adds a backend piece of functionality to include/exclude folder prefix so that user can add a folder in UI to automatically ingest files inside the folder.
=> Feat: Add file tree, add include and exclude prefix for auto ingestion

pkg/controller/handlers/runs/runs.go, pkg/controller/routes.go, pkg/invoke/invoker.go, pkg/storage/apis/otto.otto8.ai/v1/run.go, pkg/storage/apis/otto.otto8.ai/v1/runstate.go
Finalizers can be a PITA and leave over dangling refs.
We've also seen RunStates hanging around while their Runs were already gone.
This change switches RunStates over to the same cleanup logic we use for most other objects.
=> change: use cleanup handler for runstate instead of finalizer on a run

ui/admin/app/lib/service/nameGenerator.ts
Now uses the `noun` method instead of `animal` for generating the subject of an agent name
=> enhance: turn up the heat in the agent/workflow name generation

apiclient/types/zz_generated.deepcopy.go, pkg/invoke/invoker.go, pkg/storage/openapi/generated/openapi_generated.go
The uncached.Get works when calling the invoker from a controller, but not when calling from the API.
This change also includes some generated changes that were left out of a previous change.
Issue: https://github.com/otto8-ai/otto8/issues/670
=> fix: don't assume uncached.Get works in the invoker

pkg/api/handlers/webhooks.go, pkg/api/router/router.go
This PR fixes the issue where a webhook execution throws a not found error.
This fix solves that by providing the default namespace to the workflow execution handler.
=> fix: webhooks getting not found error when triggering workflows

ui/admin/app/components/webhooks/WebhookForm.tsx, ui/admin/app/components/webhooks/WebhookFormContext.tsx, ui/admin/app/lib/model/webhooks.ts, ui/admin/app/lib/utils.ts
- Remove Type field
- Always show validation header field
- move logic for deleting secret
- remove github related header suggestions
=> enhance: convert webhook form to be generic

ui/admin/app/components/form/BasicInputItem.tsx, ui/admin/app/components/form/controlledInputs.tsx, ui/admin/app/components/model/DefaultModelAliasForm.tsx, ui/admin/app/components/model/ModelForm.tsx, ui/admin/app/lib/model/defaultModelAliases.ts, ui/admin/app/lib/model/models.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/defaultModelAliasApiService.ts, ui/admin/app/lib/service/api/modelApiService.ts, ui/admin/app/routes/_auth.models.tsx
Adds modal that allows users to view and update the default model alias values
=> feat: add default model alias crud to admin ui

pkg/api/handlers/agent.go, pkg/api/handlers/emailreceiver.go, pkg/api/handlers/model.go, pkg/api/handlers/webhooks.go, pkg/api/handlers/workflows.go, pkg/controller/handlers/alias/alias.go, pkg/storage/apis/otto.otto8.ai/v1/agent.go, pkg/storage/apis/otto.otto8.ai/v1/alias.go, pkg/storage/apis/otto.otto8.ai/v1/defaultmodelalias.go, pkg/storage/apis/otto.otto8.ai/v1/emailaddress.go, pkg/storage/apis/otto.otto8.ai/v1/model.go, pkg/storage/apis/otto.otto8.ai/v1/oauthapp.go, pkg/storage/apis/otto.otto8.ai/v1/webhook.go, pkg/storage/apis/otto.otto8.ai/v1/workflow.go, pkg/storage/openapi/generated/openapi_generated.go, pkg/wait/waitfor.go
For objects with aliases, like agents, if the alias is created or updated, the API may return stale data because the controller hasn't processed the object yet. This change adds a mechanism for the API layer to ensure that the alias controller has processed the object.
Issue: https://github.com/otto8-ai/otto8/issues/634
=> fix: wait for the alias to be processed in the API layer

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentContext.tsx, ui/admin/app/components/agent/AgentPublishStatus.tsx
This addresses issue 634.
* checks against entityID instead of id.
* updates AgentContext to return agent from getAgent.data or default to the agent supplied from clientLoader.
* updates agentUpdates with appropriate aliasAssigned when agent is updated.
=> fix: Publish URL showing based on aliasAssigned and entityID check

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/routes/_auth.agents.$agent.tsx
Addresses #509
- wraps components only with necessary context providers
- internally indicates chat is no longer running when switching threads
=> fix: unable to start a new thread when tool call in progress

ui/admin/app/components/oauth-apps/OAuthAppTile.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/ui/badge.tsx, ui/admin/app/components/ui/button.tsx, ui/admin/app/tailwind.css
Previously the primary color was black (because it provided the most contrast)
This has been updated to use the blue brand color
=> enhance: switch primary accent color to "Otto8" blue

ui/admin/app/components/agent/AgentForm.tsx
Quick fix to display `modelProvider` in the model dropdown when selecting a model for an agent.
Note: Added quick question about the `modelProvider` in the related issue: #613
=> fix: show modelProvider in agent's model dropdown

ui/admin/app/routes/_index.tsx
=> fix: Prevent browser tab title from being set to "New Remix App"

Dockerfile, run.sh
This PR should configure postgres and pgvector into otto dockerfile. It will run and use the built-in postgres process if no OTTO8_SERVER_DSN is set.
I ran some test against knowledge ingestion and it works fine.
=> Chore: setup postgres and vector in dockerfile

ui/admin/app/components/tools/toolGrid/ToolCard.tsx
* minor update to avoid chip being cut off and icon being shrunk as browser is resized
* instead of margins, removed and used gap-2 so if the chip / "Bundle" is moved to a new line, its left side is still aligned with the above line
Before:
https://github.com/user-attachments/assets/2ca84f83-2b0b-47c6-8108-81d3f470cbab
After:
https://github.com/user-attachments/assets/379393bf-9a51-4078-97a9-8a49902c6df9
=> fix: minor ToolCard styling change

ui/admin/app/components/workflow/NameDescriptionForm.tsx, ui/admin/app/components/workflow/ParamsForm.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/components/workflow/WorkflowEnvForm.tsx, ui/admin/app/components/workflow/steps/AddStep.tsx, ui/admin/app/lib/model/workflows.ts, ui/admin/app/routes/_auth.workflows.$workflow.tsx
Allows admins to update the `env` property on the workflow object
- reuses the workflow parameters form
=> feat: add environment variables to workflow form in admin ui

ui/admin/app/components/sidebar/Sidebar.tsx, ui/admin/app/components/ui/sidebar.tsx
Random suggestion / thought! Noticed there wasn't an active state when clicking the links in the sidebar so throwing this one out there!
=> enhancement: Active selected link in sidebar state

ui/admin/app/components/knowledge/AgentKnowledgePanel.tsx, ui/admin/app/components/knowledge/KnowledgeSourceDetail.tsx
Don't make API requests when manually validating cache data. This is causing problem when ingesting large amount of files, as it is making too many requests in the server which cause server to load up. The knowledge files are stored in a same database withe `default` namespace so there is no index when retrieving them from database.
Also cut the interval from 1 second to 5 seconds to avoid putting too much load to server.
https://github.com/otto8-ai/otto8/issues/558
=> Fix: fix fe code to not make requests when validating cache

ui/admin/app/components/chat/ChatContext.tsx
After a workflow (or workflow authentication) was completed, the Server would close it's connection to the SSE, but the UI never closed the EventSource and would repeatedly attempt to reconnect causing a new api request every few seconds. This fix alleviates this by closing the connection in the UI whenever the server sends a `close` event
=> fix: prevent event source from reconnecting after SSE close event

docs/docs/05-configuration/02-model-providers.md, go.mod, go.sum, pkg/api/handlers/availablemodels.go, pkg/api/router/router.go, pkg/gateway/server/dispatcher/dispatcher.go, pkg/gateway/server/server.go, pkg/services/config.go, pkg/storage/apis/otto.otto8.ai/v1/toolreference.go
The available models API allows listing of all available models from all configured model providers in Otto8.
Requires: https://github.com/otto8-ai/tools/pull/248
=> feat: add available models API

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentPublishStatus.tsx
Synced with Donnie and the changes made to the api for aliasAssigned were made:
* `undefined` means the alias is still resolving
*  `true` is alias has been assigned
* `false` is alias has not been assigned (whether published or not)
It looks like `aliasAssigned` is properly updated on the revalidation call so doesn't look like polling is needed currently.
=> chore: update publish with aliasAssigned api change

ui/admin/app/components/composed/ErrorDialog.tsx, ui/admin/app/components/knowledge/AgentKnowledgePanel.tsx, ui/admin/app/components/knowledge/KnowledgeSourceDetail.tsx, ui/admin/app/components/tools/CreateTool.tsx, ui/admin/app/lib/model/toolReferences.ts, ui/admin/app/routes/_auth.tools._index.tsx
Addresses #502 
After syncing with Donnie, `resolved` field was added to the ToolReference. Similarly to `aliasAssigned`:
* `undefined`, the creation of tool is still resolving
*  `true/false`, tool has or has not been resolved
Once resolved, `error` should be supplied.
Needed to implement polling to fetch the ToolReference until it is resolved. 
Once resolved, error is shown in ErrorDialog, but lemme know if there is a different preferred error handling!
https://github.com/user-attachments/assets/2601e797-568e-45bc-9e8e-1737263000b9
(Tempted to see if I can make it scroll to the created tool once it's completed so user immediately sees their uploaded tool or maybe sort by recently created so it immediately shows at the top?)
=> fix: display error if tool creation failed

Makefile
We are missing the build step in packaging script that are used to build docker images
=> Fix: run pnpm build in package script

ui/admin/app/components/knowledge/AddSourceModal.tsx
Add documentation to generate onedrive link.
=> Chore: Add document link to generate onedrive link

pkg/controller/handlers/knowledgesource/knowledgesource.go, pkg/invoke/invoker.go, pkg/invoke/system.go, pkg/storage/apis/otto.otto8.ai/v1/run.go
... also set default knowledge data-source sync timeout to ~30m~ 1h, as it can easily happen that website-scraping exceeds 10 minutes.
Ref https://github.com/otto8-ai/otto8/issues/743
=> feat: RunSpec.Timeout to override default 10m run timeout

ui/admin/app/components/knowledge/AgentKnowledgePanel.tsx, ui/admin/app/lib/model/knowledge.ts
Don't list knowledge source with `deleted` as it could be waiting to be cleaned by finalizer. Also validate in cache after deletion.
https://github.com/otto8-ai/otto8/issues/746
=> Fix: fix delete knowledge source hanging in UI

ui/admin/app/lib/service/nameGenerator.ts
This PR improves the agent name generation in the admin UI by selecting a pool of nouns to select from.
This should reduce the number of nouns that could also be used as adjectives and increases the number of nouns likely to be familiar to a user.
The end goal: improve the likelihood of generating a "fun" agent name.
=> enhance: agent name generation in admin ui

ui/admin/app/components/errors/Error.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/ui/button.tsx, ui/admin/app/components/ui/link.tsx, ui/admin/app/components/webhooks/WebhookActions.tsx, ui/admin/app/components/workflow/DeleteWorkflow.tsx, ui/admin/app/components/workflow/WorkflowView.tsx, ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.users.tsx, ui/admin/app/routes/_auth.webhooks._index.tsx, ui/admin/app/routes/_auth.workflows._index.tsx
- Updated link component to optionally use button classes
- Fixed link alignment in tables (Agents, Workflows)
- Updated webhooks actions to use dropdown instead of popover
=> chore: update link implementation and usages in tables app-wide

ui/admin/app/components/model-providers/ModelProviderForm.tsx, ui/admin/app/components/model-providers/ModelProviderLists.tsx, ui/admin/app/components/model-providers/ModelProviderModels.tsx, ui/admin/app/components/model-providers/constants.ts, ui/admin/app/components/model/shared/DefaultModelAliasForm.tsx, ui/admin/app/routes/_auth.model-providers.tsx
https://github.com/user-attachments/assets/ff2f6bfd-6fcc-4606-a906-9937e3eeb3ab
* view models from a Model Provider. After configuring a Model Provider, gear shows on top right
* added helper text for Azure and Ollama for some inputs that need info to help fill out
* added helper text for required inputs that may require more context (ex. Ollama & Azure OpenAI Model Provider required configurations)
For context, after discussing with Will & Craig, it was decided that it made more sense to view the models from a Model Provider. This PR adds that in but there may be a follow-up of:
* removing the Models page
* turning the delete into a disable toggle switch. disabling means: If a model is disabled, then that means the model is not usable period (Add a warning that the agents/etc could break …
=> feat: view models for a model provider & configure helper text for inputs

pkg/controller/controller.go, pkg/controller/handlers/toolreference/toolreference.go
When the user configures the OpenAI model provider with an environment variable, this change will ensure that the models are populated as expected and that the default model aliases are set to reasonable defaults. If the default model aliases are already set, then this change will not touch them.
=> feat: set default aliases if configuring OpenAI with env var

ui/admin/app/components/model-providers/ModelProviderConfigure.tsx, ui/admin/app/components/model-providers/ModelProviderModels.tsx, ui/admin/app/components/model/shared/DefaultModelAliasForm.tsx
https://github.com/user-attachments/assets/a1c84366-7ecc-4576-b44f-ca48ceac68de
* adds polling to wait for models to be back populated after configuring
Also included small fixes:
* No Models Available when no options to select in default model input dropdown
* do not show empty badge when usage isn't set for back populated models
* show name instead of id in table when viewing model provider's models
=> fix: waiting for modelProvider models to load before showing default model selection

ui/admin/app/routes/_auth.threads._index.tsx, ui/admin/app/routes/_auth.tools._index.tsx
* fix for threads table expanding to fill h-full space when not enough rows 
* this is prolly a my bad when removing some of wrapper divs to get the sticky for table headers to work! 🙏
=> fix: stop threads table filling up empty space

apiclient/types/model.go, ui/admin/app/components/model-providers/ModelProviderConfigure.tsx, ui/admin/app/components/model/DefaultModelAliasForm.tsx, ui/admin/app/components/model/constants.ts, ui/admin/app/lib/model/defaultModelAliases.ts, ui/admin/app/lib/model/models.ts
- sorts models by name in default model dropdowns
- adds an "Other" group to dropdowns for models that don't have a usage
- ensures that backend always returns a value for model usage
- apply suggested models to default models form after configuration
=> feat: sort models by name in default model dropdowns

ui/admin/app/components/composed/NameDescriptionForm.tsx, ui/admin/app/components/model-providers/ModelProviderForm.tsx
- updates NameDescriptionForm to accept prop overrides for it's fields
=> feat: set api key inputs to be type password in model provider form

ui/admin/app/components/model-providers/ModelProviderConfigure.tsx, ui/admin/app/components/model-providers/ModelProviderModels.tsx, ui/admin/app/components/ui/table.tsx
* adds padding to align model provider header with start of table row
* opens new tab for anthropic link
* removes border-b from table rows
=> fix: link open new tab fix & minor table styling fixes

ui/admin/app/routes/_auth.workflows._index.tsx
Couldn't click the Threads link on the workflow table because the row
click was getting in the way.
=> Fix: Make workflow thread link clickable

ui/admin/app/components/composed/WarningAlert.tsx, ui/admin/app/components/knowledge/AgentKnowledgePanel.tsx, ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.model-providers.tsx
* disables Knowledge description & Add Knowledge button if default text-embedding isn't set
* adds Alert to notify user why it's disabled
=> enhance: if no default text-embedding set, disable knowledge for agent/workflows

ui/admin/app/components/tools/CreateTool.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/lib/service/api/toolreferenceService.ts, ui/admin/app/root.tsx
Addresses #481.
* creates toast when adding tool is successful
* user created tools is at top
Update:
* green checkmark for toast.success
=> fix: user tools to the top & toast on successful tool addition

tools/dev.sh
=> fix: update make dev user ui ping url

ui/admin/app/components/knowledge/FileTree.tsx
When adding/excluding files, we approve/unapprove individual files first and then add include/exclude list for backend reconcilation. Since approving individual files takes some time, if getting interupted, the backedn include/exclude list will never be added. So moving the logic up to add include/exclude list first before approving/unapproving individual files.
https://github.com/otto8-ai/otto8/issues/822
=> Fix: Add include/exclude list first before approving files

ui/admin/app/components/agent/AgentForm.tsx, ui/admin/app/components/model/DefaultModelAliasForm.tsx
* adds model provider in dropdown like in agent models dropdown 
* only thing about this is a little busy and drowns out (Suggested), not sure if a smaller font size for the provider would help
=> fix: adds model provider in dropdown options for default models

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/lib/model/chatEvents.ts
addresses #854 
Before:
After:
=> fix: prevent display of tool call output events

go.mod, pkg/api/handlers/version.go
- Add the module version for `github.com/gptscript-ai/gptscript` to the `/api/version` API response
- Change `/api/version` API response field name from `otto` to `acorn`
Addresses https://github.com/acorn-io/acorn/issues/899
=> enhance: add gptscript module version to /api/version

ui/admin/app/components/model-providers/ModelProviderConfigure.tsx, ui/admin/app/lib/service/api/apiErrors.tsx, ui/admin/app/lib/service/api/primitives.ts
* Addresses #843 
* useSWR continues to retry if it receives an error response but 404 response is valid for /reveal (means no credential found for that model provider)
* avoid retry for 404 (causing clear out of form and retry is unnecessary, we revalidate reveal after user submits form)
=> fix: do not retry for reveal 404, will clear existing form entries

.github/workflows/docker-build-and-push.yml, .github/workflows/docker-build.yml, .github/workflows/go.yml, .gitignore, DEVELOPMENT.md, pkg/controller/handlers/knowledgesummary/knowledgesummary.go
This change also adds a docker build step to CI and adds the http/ directory to the gitignore.
Issue: https://github.com/obot-platform/obot/issues/909
=> chore: add a development explainer

pkg/controller/handlers/knowledgefile/knowledgefile.go
When comparing with prefix pattern, the onedrive file has filepath starting with "/". But when we are adding folder to the prefix path, we are only adding the name. This makes the folder prefix matching not working in onedrive. So removing the prefix slash before comparing.
https://github.com/acorn-io/acorn/issues/822
=> Fix: remove slash prefix when comparing with match pattern

ui/admin/app/lib/model/oauthApps/index.ts
Hide the Atlassian OAuth integration from admins until we have tools that use it.
=> chore: hide atlassian oauth config from admins

ui/admin/app/components/tools/BasicToolForm.tsx
The useEffect updating on the watch is not effectively updating the tools for workflows. This change switches back using the form.
=> fix: update workflow tools more consistently

ui/admin/app/components/model-providers/ModelProviderConfigure.tsx
* intermittent behavior due to sometimes models getting revalidated due to staleness, otherwise models remains empty and you get the empty dropdowns. This makes sure getModels get revalidated after checking modelsBackPopulated.
=> fix: revalidate getModels after confirming modelsBackPopulated

ui/admin/.eslintrc.cjs, ui/admin/app/components/ui/multi-select.tsx, ui/admin/app/components/ui/scroll-area.tsx, ui/admin/app/components/ui/sidebar.tsx, ui/admin/app/components/ui/textarea.tsx, ui/admin/app/hooks/useLogEffect.ts, ui/admin/package.json, ui/admin/pnpm-lock.yaml
- All code logic should be identical
- did some swapping out of refs for state vars to improve adherence to the rules of react
=> feat: implement new linter rules in preparation for react compiler

ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/tools/BasicToolForm.tsx, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/components/workflow/steps/Step.tsx
TLDR;
useForm returns `useRef().current` under the hood as a hack to optimize rendering. For the most part, this is totally fine, but it CAN cause some erratic behavior when certain conditions are met (I think it has to do with resetting the form's default values...????)
Either way, it added way more complexity than it was worth (at least for this component) so removing it was the best solution
More in-depth:
After mount, the first rerender (change event) of this specific usage of `BasicToolForm` was causing the `form.watch` method to change references (not only that but it was being treated as a NOOP??) as a result, the `onChange` prop was not getting triggered, but only for the first change. Subsequent rerenders **did not** reinitialize the `watch` method and it behaved as expected. …
=> chore: remove useForm dependency from BasicToolForm

ui/admin/app/routes/_auth.workflows._index.tsx
=> fix: re-enable event propagation for workflow edit icon on the workflows page

pkg/controller/handlers/toolreference/toolreference.go
There were a couple issues. First, since we are using the url package, the credential tool was path-escaped. This change fixes that.
Secondly, the credential set here was not usable by GPTScript if the reference was of the form "sub tool from path/to/tool". This change also addresses that by parsing the tool reference.
=> fix: set the correct credential tool for tool reference

ui/admin/app/components/chat/MessagePane.tsx, ui/admin/app/components/ui/scroll-area.tsx
- Updates the scroll-area component to take classNames for it's viewport subcomponent for more flexible styling
before:
after:
=> refactor: re-center the message suggestions for new threads

ui/admin/app/lib/service/api/toolreferenceService.ts
* one-liner fix, if a toolReference is marked with deleted, it's being cleaned up  [Thread here](https://github.com/obot-platform/obot/issues/858#issuecomment-2557467363) Account for deleted and don't include it if it is set.
=> fix: account for deleted property on toolReference

ui/admin/app/components/agent/AgentForm.tsx, ui/admin/app/components/composed/ComboBox.tsx, ui/admin/app/components/model/DefaultModelAliasForm.tsx
* get ComboBox working with nested groups and filtering with nested groups/items
* change default model alias selects to comboboxes
=> enhance: combobox with nested groups & use for default alias dropdown

ui/admin/app/components/model-providers/ModelProviderForm.tsx
* super small one-liner: remove redundant toast for successful model provider configuration
=> fix: remove redundant model provider config toast

ui/admin/app/components/chat/Chat.tsx, ui/admin/app/components/chat/RunWorkflow.tsx, ui/admin/app/components/model-providers/ModelProviderConfigure.tsx
=> enhance: add stopping of workflows

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/routes/_auth.workflows._index.tsx
* instead of skipping events with toolCall.output, update the previous toolCall without an output with it during event phase
* allow showing of messages with toolCall.output
* tested with while running with a workflow, newly created agent 
* tested with going to Threads and visiting a pre-existing thread where a tool was used
=> fix: continue showing tool calls in revisiting thread

ui/admin/app/components/sidebar/Sidebar.tsx, ui/admin/app/lib/model/version.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/versionApiService.ts
Addresses #1057 
* adds obot version to sidebar footer
* clicking it shows rest of versioning 
https://www.loom.com/share/9d2099ef83df41279895c175739515c3?sid=74ae922b-8d99-425c-a6fc-d15f3a379d4d
=> feat: add ui version to sidebar footer

ui/admin/app/components/composed/ComboBox.tsx, ui/admin/app/routes/_auth.model-providers.tsx
Addresses #827 and #841 
* set max height to avoid command dropdown being cut off due to smaller browser height screens
* set empty placeholder in model providers page to avoid jumping around from not configured -> configured
=> fix: model-providers configured empty placeholder & combobox max height

ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.threads.$id.tsx
Addresses #816 and #815
* fixing showing of agent id instead of agent name in Threads page
=> fix: agent id briefly showing on breadcrumb in threads

ui/admin/app/components/ui/input.tsx, ui/admin/app/routes/_auth.tools._index.tsx
- additionally extract input reset classname variable
=> fix: prevent default scrollbar from displaying on tools page

ui/admin/app/components/model-providers/ModelProviderForm.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/webhooks/WebhookConfirmation.tsx
Addresses #814 
Addresses #1042 
Addresses #901 
* minor adjustments for ui in tools, webhook, and model provider
* fixes overflow of webhook url in dialog
* removes tool.reference from displaying for built-in tools per request
* makes sure model provider revealed keys gets revalidated on success of configure rather than success of getting of models
=> fix: minor ui updates & fix model provider key updating on save/error

ui/admin/app/components/chat/Message.tsx
addresses #730 
pulls icon and category information from the prompt metadata and displays it in the message
=> enhance: add metadata information to authentication messages once auth is confirmed

pkg/invoke/invoker.go, pkg/services/config.go
Add a no-reply email address option to the Obot server configuration. This setting is passed down to running tools so that the sendgrid tool can send emails using a pre-configured no-reply address.
=> enhance: add no-reply email to server config

ui/admin/app/components/knowledge/FileTree.tsx
https://github.com/obot-platform/obot/issues/719
=> Fix: Don't show yellow text for unsupported files

pkg/render/render.go
We should remove knowledge tool when invoking if knowledge set has no content. This avoid LLM to call knowledge when no data is in it.
=> Fix: remove knowledge tool when knowledge set has no content

pkg/controller/handlers/knowledgefile/knowledgefile.go, pkg/controller/handlers/knowledgesource/knowledgesource.go, pkg/services/config.go, pkg/storage/apis/otto.otto8.ai/v1/file.go, pkg/storage/openapi/generated/openapi_generated.go
Add ability to re-enqueue the file ingestion process up to 3 times when it fails. 
https://github.com/obot-platform/obot/issues/1071
=> Chore: Add ability to retry ingestion up to 3 times

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/RunWorkflow.tsx, ui/admin/app/lib/model/oauthApps/providers/microsoft365.ts
Addresses #405 & #734 
* shows "Authenticating" instead of "Run Workflow" when in authentication step (#734)
* also shows disabled oauth button/link if user stops during authentication step 
* minor text updates for microsoft 365 oauth instructions for clarification (#405)
During authenticating:
Aborting during authenticating:
=> fix: "Authenticating" instead of "Run Workflow" during workflow authentication

pkg/api/handlers/agent.go, pkg/api/router/router.go, ui/admin/app/components/knowledge/FileTree.tsx, ui/admin/app/hooks/knowledge/useKnowledgeSourceFiles.ts, ui/admin/app/lib/model/knowledge.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/knowledgeSourceApiService.ts
We used to pull knowledge at an interval but this is not effiencient. Switching to use SSE events to watch for changes.
=> Chore: use SSE to deliver change event for knowledgefiles

apiclient/types/user.go, pkg/api/authn/noauth.go, pkg/api/handlers/assistants.go, pkg/api/request.go, pkg/controller/data/agent.yaml, pkg/gateway/client/auth.go, pkg/gateway/client/identity.go, pkg/gateway/server/user.go, pkg/gateway/types/users.go, pkg/invoke/invoker.go, pkg/services/config.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/lib/model/users.ts, ui/admin/app/lib/service/api/primitives.ts, ui/user/src/lib/services/chat/http.ts
Make the [tz database timezone ID](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) for the default timezone of a user available to tools at runtime via the `OBOT_USER_TIMEZONE` environment variable.
e.g. `OBOT_USER_TIMEZONE=America/New_York`
TThe timezone ID is captured by the admin and user UIs from the browser and passed using the `X-Obot-User-Timezone` header on requests to Obot's APIs. The header is then unpacked in Obot's Authentication middleware and persisted in the respective `User` object. When a thread is invoked, its value is extracted from the `User` and passed to tool calls via the aforementioned environment variable.
The user's timezone can be customized independently of this defaulting mechanism by issuing a PATCH on `/api/users/{username}` with a body …
=> enhance: plumb tz from client-side uis to tools

ui/admin/app/components/errors/Error.tsx, ui/admin/app/components/errors/RouteError.tsx, ui/admin/app/routes/_auth.workflows.$workflow.tsx
addresses #1114
- fixes the `go back` cta
- adds a third `try again` option that refreshes the page
=> fix: error boundary go back

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/MessageDebug.tsx, ui/admin/app/components/chat/MessagePane.tsx, ui/admin/tsconfig.json
addresses #1022
- shows debug info for the current run
- updates the displayed icon
https://github.com/user-attachments/assets/0440ed31-f74d-4753-8e62-ca0163f7a66c
=> feat: add debug info to typing dots indicator in chat

pkg/controller/handlers/toolreference/toolreference.go
The credential parsing was not correct for credentials in the sub tool format. This change fixes that parsing.
=> fix: fix tool reference credentials that have sub tools

pkg/controller/handlers/toolinfo/toolinfo.go, pkg/controller/handlers/toolreference/toolreference.go, pkg/system/tools.go
The model provider credential is special and will always be set to point back to Obot. For tools that use this credential, we now properly detect it and report its status.
=> fix: properly report credential info for tools with model provider cred

pkg/api/handlers/agent.go, pkg/controller/handlers/toolinfo/toolinfo.go
The threads used to authorize agents and workflows should not be shown to users. This change ensures that is the case.
Issue: https://github.com/obot-platform/obot/issues/1127
=> fix: stop show credential threads to users

ui/admin/app/components/webhooks/WebhookFormContext.tsx
=> chore: drop default header options from webhook form

ui/admin/app/components/knowledge/FileTree.tsx
Fix https://acorn-io.slack.com/archives/C07FZ46QA2J/p1736185965118239
=> Fix: fix individual files not showing correct icon

ui/admin/app/routes/_auth.threads.$id.tsx
- previously just went back to all threads page
=> fix: update thread back button to navigate back in browser history

ui/admin/app/components/agent/Publish.tsx
* The alias is used as the `id` identifier for assistants so restricting the input to only allow alphanumeric, dashes, & underscores
Addresses #951
=> fix: publish restricted to alphanumeric, dashes, & underscores

ui/admin/app/components/chat/CallFrames.tsx
* remove "Obot" from top-level
* account for `chatCompletion` in `llmRequest` for `LLM Request & Response`-like labels (otherwise you get Command Input/Output)
Addresses #1024
=> fix: debug, remove top-level obot and llm response/request label fix

apiclient/types/user.go, pkg/api/authz/authz.go, pkg/gateway/client/auth.go, pkg/gateway/client/error.go, pkg/gateway/client/identity.go, pkg/gateway/client/user.go, pkg/gateway/server/user.go
The user API was migrated from the Gateway and wasn't used outside getting and listing. This change ensures that update and delete work, especially in regard to changing user roles.
One note: this change does make it possible to change the "nobody" user when authentication is turned off. However, the role will be switched back to admin automatically.
=> chore: update the user API to be usable

pkg/api/handlers/agent.go, pkg/api/handlers/workflows.go, pkg/controller/creds/creds.go, pkg/controller/handlers/toolinfo/toolinfo.go, pkg/controller/handlers/toolreference/toolreference.go
Support authentication for agent and workflow tools that use non-tool-references in their definition. That is, a GitHub-hosted tool or a local tool.
During the implementation and testing for non-tool-references, I also spotted a gap: nested tools. That is, if an agent uses a tool that uses a tool that has a credential, then the authentication for that tool would not be processed. After this change, it will.
=> feat: add support for credential auth for non-tool-references

ui/admin/app/components/workflow-triggers/CreateWorkflowTrigger.tsx, ui/admin/app/components/workflow-triggers/DeleteWorkflowTrigger.tsx, ui/admin/app/components/workflow-triggers/EmailReceiverForm.tsx, ui/admin/app/components/workflow-triggers/WorkflowTriggerActions.tsx, ui/admin/app/lib/model/email-receivers.ts, ui/admin/app/lib/model/workflow-trigger.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/EmailRecieverApiService.ts, ui/admin/app/lib/service/api/emailReceiverApiService.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/_auth.workflow-triggers._index.tsx, ui/admin/app/routes/_auth.workflow-triggers.email.$receiver.tsx, ui/admin/app/routes/_auth.workflow-triggers.email.create.tsx
=> feat: implement email receivers in workflow-triggers page

ui/admin/app/lib/model/oauthApps/providers/atlassian.ts
- Add optional steps in the Atlassian Oauth App guide to guide users on `how to set their Atlassian apps to public` to get rid of the warning message. See https://github.com/obot-platform/obot/issues/1015
=> fix: Include steps in the Atlassian Oauth App guide to guide users on how to set their apps to public.

ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/lib/service/api/toolreferenceService.ts
Addresses #1141 
Addresses #1021 
* "Custom Tools" to "Your Tools"
* fix search/filtering in tool category dropdown not showing results
* found weird bug with native Command filter where searching with a bundle selected and expanded -- the bundle item gets moved to the bottom and stays that way until you deselect, collapse it, and expand it or search again. Moved filtering logic out and that addressed it.
=> fix: Custom Tools & search tool dropdown fix

ui/admin/app/components/model-providers/ModelProviderIcon.tsx
* super small fix, down to very dehydrated whale icon
=> fix: DeepSeek icon inverted in dark mode fix

pkg/controller/handlers/toolinfo/toolinfo.go, pkg/storage/apis/obot.obot.ai/v1/file.go
The model provider credential cannot be set by the user nor can it be deleted. Therefore, it doesn't make sense to include it when reporting tool infos on agents and workflows.
Issue: https://github.com/obot-platform/obot/issues/1159
=> fix: filter out the model provider credential when reporting tool info

ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/ToolTooltip.tsx, ui/admin/app/components/workflow/steps/StepBase.tsx, ui/admin/app/lib/model/workflows.ts
Addresses #1039
Addresses #1183 
* per thread with Craig, changed from filtering out to showing greyed out and why it's inaccessible
* noticed small bug with step deletion, fixed here as well
=> enhance: greyed out tool if oauth is unconfigured

apiclient/types/user.go, pkg/api/handlers/authorizations.go, pkg/gateway/client/client.go, pkg/gateway/client/error.go, pkg/gateway/client/user.go, pkg/gateway/server/user.go, pkg/gateway/types/users.go, pkg/storage/openapi/generated/openapi_generated.go
Users that were made admins by the config when deploying Obot are now marked. Additionally, it is an error to change their role to be different from an admin.
=> enhance: mark users that have been made explicit admins via config

ui/admin/app/hooks/useHasChanged.tsx
=> fix: improve object comparison in useHasChanged

pkg/api/handlers/tables.go
Use the updated database tool names introduced by https://github.com/obot-platform/tools/pull/334
Addresses part of https://github.com/obot-platform/obot/issues/1208
=> chore: update database tool names

docs/snippets/go-hash-tool-readme.md.mdx, docs/snippets/node-hash-tool-readme.md.mdx, docs/snippets/python-hash-tool-readme.md.mdx
Fetch the latest tool authoring README.md snippets from the respective example tool repos to include the doc updates initially authored by https://github.com/oskapt in https://github.com/obot-platform/obot/pull/1217.
This is change depends on the following PRs, which must merge before this:
- https://github.com/obot-platform/go-hash-tool/pull/2
- https://github.com/obot-platform/python-hash-tool/pull/3
- https://github.com/obot-platform/node-hash-tool/pull/2
Note: The docs snippet plugin is too complex and [is slated to be removed](https://github.com/obot-platform/obot/issues/1236) in the medium to long-term. This should be the last time we use this flow for updating the docs.
=> docs: fetch updated tool authoring readme snippets

pkg/controller/routes.go
Adding the IncludeFinalizing will ensure they old finalizers are removed even when the object is deleting.
=> chore: ensure old finalizers are removed

ui/admin/app/components/composed/typography.tsx, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/tools/toolGrid/ToolCardActions.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/hooks/usePollSingleTool.ts, ui/admin/app/lib/model/toolReferences.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/toolreferenceService.ts, ui/admin/app/routes/_auth.tools._index.tsx
addreses #735
https://www.loom.com/share/e540e7d9556d48f9a49804b5081222d8?sid=179d2751-f225-452c-b449-76c34c3c923d
=> feat: allow users to force-refresh their custom tools

ui/admin/app/components/tools/toolGrid/ToolCardActions.tsx, ui/admin/app/hooks/usePollSingleTool.ts
- hides builtin tool actions from the tools page
- prevents stale data from preemptively stopping tool polling after refresh
=> Fix: hide builtin tool actions

ui/admin/app/routes/_auth.workflows._index.tsx
Addresses #1230 
* `mutate` was changing getWorkflows.data to object returned from `ThreadsService.getThreads.key()`
* don't believe this is needed? ClientLoader is calling preload on these two calls
=> fix: error workflows.reduce fix due to Workflows clientLoader mutate

ui/admin/app/components/tools/toolGrid/ToolCardActions.tsx
* built-in tools with oauth metadata will have the dropdown, need to make sure to exclude refresh tool along with delete tool option
=> fix: no "refresh tool" on built-in tool dropdown

go.mod, go.sum, pkg/api/authz/authz.go, pkg/api/handlers/sendgrid/webhook.go, pkg/api/router/router.go, pkg/emailtrigger/emailtrigger.go, pkg/services/config.go, pkg/smtp/smtp.go
Add sendgrid webhook endpoint to be able to receive sendgrid inbound parse event and trigger workflow.
A use case would be getting emails regarding to receipts and have dedicated workflows processing these emails.
=> Chore: add sendgrid webhook endpoints to receive webhook events

pkg/controller/handlers/knowledgefile/knowledgefile.go
The ingestion will trigger when/if the thread exists.
=> chore: ignore the thread not found error when ingesting

apiclient/types/toolreference.go, pkg/controller/creds/creds.go, pkg/controller/handlers/toolinfo/toolinfo.go, pkg/storage/openapi/generated/openapi_generated.go
Certain tools have credentials that don't require the use to authenticate them. For example, the sys.model.provider.credential is handled by the system and never needs user interaction.
This change introduces the processing of the noAuth metadata field to indicate which credentials don't need user auth. If a credential name is included in the noAuth metadata for a tool, then that credential name is disregarded for user auth. The sys.model.provider.credential is included by default for every tool.
This is more of a proposal. There have already been a couple of instances of us needing to exclude certain credentials from authentication. This will allow tools to tell us that a credential doesn't need authentication instead of us playing whack-a-mole as we go along.
Issue: …
=> enhance: allow tools to indicate which credentials don't need auth

pkg/controller/handlers/knowledgeset/knowledgeset.go, pkg/storage/apis/obot.obot.ai/v1/knowledgeset.go, pkg/storage/openapi/generated/openapi_generated.go
We are issuing a  run to delete knowledge dataset when a thread and knowledge set has been created first but with no content on it. Seems unnecessary to do so that. What is happening today is that when user chats with an agent, a new thread with knowledge set created and we immediately run a `knowledge-delete` run with it even there is no dataset created with it.
=> Fix: don't delete knowledge dataset when it is not being created

DEVELOPMENT.md, Dockerfile, pkg/controller/controller.go, pkg/controller/handlers/toolreference/toolreference.go, pkg/controller/routes.go, pkg/credstores/credstore.go, pkg/services/config.go, pkg/storage/server.go, run.sh, tools/package-tools.sh
This change adds support for consuming tools from more than one tool registry at a time.
It replaces the `OBOT_SERVER_TOOL_REGISTRY` option with `OBOT_SERVER_TOOL_REGISTRIES`. The new option accepts a comma-delimited string of registry URIs.
e.g.
```bash
export OBOT_SERVER_TOOL_REGISTRIES='github.com/obot-platform/tools,github.com/obot-platform/enterprise-tools'`
```
When overriding a remote registry with a directory in the local filesystem, the `GPTSCRIPT_TOOL_REMAP` environment variable is used to provide tool reference remapping in GPTScript/Obot.
e.g. Replacing `github.com/obot-platform/tools` with `../tools`:
```bash
export GPTSCRIPT_TOOL_REMAP='github.com/obot-platform/tools=../tools'
```
e.g. Replacing `github.com/obot-platform/tools` with `../tools` and …
=> Support multiple tool registries

.github/workflows/docker-build-and-push.yml
Add a GitHub workflow step to build and publish enterprise images to ghcr.io on push to main and tags.
Depends on https://github.com/obot-platform/obot/pull/1193, https://github.com/obot-platform/enterprise-tools/pull/1, and https://github.com/obot-platform/tools/pull/337
Part of #877
=> chore: build and publish enterprise images

ui/admin/app/components/workflow/triggers/EmailReceiverEntry.tsx, ui/admin/app/lib/model/email-receivers.ts, ui/admin/app/lib/model/workflow-trigger.ts
Addresses #1188 
Per Donnie: `If the SMTP server is not enabled, then the email address field will not be set.` so `emailAddress` may not be set. Slightly modified the `isEmailReceiver` check to get email trigger types to come through.
=> fix: show email triggers in workflow triggers page

pkg/events/events.go
Checking the live state events initially will ensure that the events watcher will see any prompts that happen before other call events.
Issue: https://github.com/obot-platform/obot/issues/1290
=> fix: check live state events first when watching events

docs/docs/03-tools/02-integrating-oauth.md, ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentIntroForm.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/NoMessages.tsx
* moves introductions above capabilities
* add markdown support note & support to introduction message
=> fix: agent intro & markdown support

pkg/api/handlers/modelprovider.go, pkg/api/router/router.go, pkg/availablemodels/availablemodels.go, pkg/controller/handlers/toolreference/toolreference.go, ui/admin/app/components/model-providers/ModelProviderForm.tsx, ui/admin/app/hooks/useAsync.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/modelProviderApiService.ts
Important: This draft PR contains a couple of changes.
1. Change to the handler to populate ToolReference.Status.Error with an error message if available models couldn't be fetched
2. Change to the UI when calling `/available-models/{model-provider-id}` so it shows the error message to the user
3. Change to the UI to call /validate and only if that succeeds, save the config and call /available-models
- If it fails, don't save the config and display an appropriate error
4. Add the /validate endpoint for model providers which calls the subtool `validate from <model-provider-tool>` to validate the config (if available)
Tested with the "reference implementation" which is the gemini-vertex provider: https://github.com/obot-platform/obot/pull/986 / …
=> feat: model provider configuration validation

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/tools/ToolIcon.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/ToolTooltip.tsx, ui/admin/app/components/tools/toolGrid/BundleToolList.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/ui/dialog.tsx
Addresses #1129
- ensure opening a dialog always autofocuses the close button if available
- remove tooltips from tool icons
=> fix: prevent focus on tool dialog contents

ui/admin/app/components/agent/AgentIntroForm.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/NoMessages.tsx, ui/admin/app/components/oauth-apps/OAuthAppForm.tsx, ui/admin/app/components/ui/markdown.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
* shared Markdown component that takes in repeated props
* tweak to AgentForm.reset (if one of the fields is not supplied from `agent`, it fails the safeSchema check)
* add rehype-raw & rehype-sanitize to allow embedded html rendering and sanitize html
=> fix: markdown embedded html & agent intro not firing onChange

docs/docs/05-configuration/03-auth-providers.md
This is the user-facing documentation explaining how to use auth providers.
=> docs: auth providers

ui/admin/app/components/chat/MessagePane.tsx
Addresses #1342 
Issue is due to centering the NoMessages, once it's too tall, the contents get cut off. 
* To fix, conditionally apply the flex & justify-center if at an empty state & the content of NoMessages is smaller than the height of the chat container
Other option is to remove the justify-center and allow intro/starter messages to start at top of the chat box instead of vertically centered.
=> fix: agent intro, avoid centering if intro is too large

ui/admin/app/components/chat/ChatActions.tsx, ui/admin/app/components/chat/chat-actions/KnowledgeInfo.tsx, ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/ui/button.tsx, ui/admin/app/hooks/knowledge/useKnowledgeFiles.ts, ui/admin/app/lib/service/api/knowledgeFileApiService.ts, ui/admin/app/lib/service/api/modelProviderApiService.ts, ui/admin/app/lib/service/api/primitives.ts, ui/admin/app/routes/_auth.threads.$id.tsx
- also add ability to refresh files/knowledge in thread sidebar
=> fix: hide error toast for reveal api during initial model provider configuration

ui/admin/app/components/ui/scroll-area.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
addresses #1190
before:
after:
=> fix: prevent scroll area from expanding with `code` tags

ui/admin/app/components/chat/CallFrames.tsx
When contructing the debug view, we would ignore certain frames, but it
seems we should not ignore frames where the tool is named obot, because
that is the name of the root frame for threads from the obot agent.
=> Fix: Don't ignore obot frame in debug view

ui/admin/app/components/auth-and-model-providers/ProviderIcon.tsx
=> fix: github icon darkmode:invert

pkg/api/handlers/agent.go, pkg/api/handlers/authprovider.go, pkg/api/handlers/availablemodels.go, pkg/api/handlers/env.go, pkg/api/handlers/modelprovider.go, pkg/controller/handlers/toolreference/toolreference.go, pkg/gateway/server/dispatcher/dispatcher.go, pkg/system/tools.go
The generic "auth-provider" and "model-provider" credential contexts will be used when looking for credentials for auth and model providers, respectively.
Additionally, use the ErrNotFound from the gptscript SDK instead of looking for "credential not found" in the error string.
=> enhance: add ability to pre-configure auth and model providers

ui/admin/app/components/ui/markdown.tsx
=> feat: allow images in markdown

chart/templates/deployment.yaml, chart/values.yaml, docs/docs/05-configuration/03-auth-providers.md, pkg/api/authz/authz.go, pkg/api/router/router.go, pkg/bootstrap/bootstrap.go, pkg/services/config.go
This makes the following changes to how initial auth and bootstrap work:
- The bootstrap token is now stored as a credential, based on the very first value set for it: either randomly generated, or from OBOT_BOOTSTRAP_TOKEN
- OBOT_BOOTSTRAP_TOKEN can always be used to override it
- The bootstrap user is only available until there is another admin user in the database, after which it is no longer available
- It can be made available again by setting OBOT_SERVER_FORCE_ENABLE_BOOTSTRAP=true
- `/api/bootstrap` returns a JSON string `{"enabled":true}` if bootstrap login is enabled (auth is enabled and bootstrap is enabled), or `{"enabled":false}` if auth is disabled or bootstrap is disabled
=> fix: bootstrap: disable bootstrap when another admin user exists

pkg/gateway/client/user.go, pkg/gateway/server/user.go, pkg/proxy/proxy.go
Previously, after the user logs in, we would store which auth provider they used in a cookie. This was causing problems with otto8. This PR changes it so that the auth provider gets stored within the same cookie. The logic is a bit messy, but we basically just intercept and read/modify the cookie before we send it to the oauth2proxy, and when it sets the cookie in the browser, we also intercept it there to insert the info about which auth provider it is.
Because it needed to be taken care of, this PR also filters the bootstrap user out of `/api/users` and update the "last admin" error logic to exclude the bootstrap user there as well.
=> fix: store auth provider in the same cookie as the token

pkg/api/handlers/authprovider.go
This fixes a bug that occurs when the generated cookie secret has space on either end. The auth provider was trimming this space off, resulting in a secret that is too short, since it needs to be exactly 32 bytes.
=> fix: cookie secrets: check length after trimming spaces

ui/admin/app/hooks/auth/useAuthStatus.ts, ui/admin/app/routes/_auth.tsx
preload auth providers to prevent flash of banner when data is loading
@ivyjeong13 feel free to merge this after review. Thanks!
=> fix: prevent flash of setup banner while loading auth providers

pkg/api/handlers/authprovider.go
Sorry, this was a big oversight on my part. The cookie secret was always ending up the same, since I wasn't doing the initial generation outside of the loop.
=> fix: cookie secret generation: actually generate it

ui/admin/app/lib/service/api/authProviderApiService.ts
* mutes toast error when reveal auth provider 404 occurs
Uses `toastError` from #1347
=> fix: mute reveal auth provider toast error

ui/admin/app/components/agent/ToolEntry.tsx, ui/admin/app/components/ui/select.tsx
* Safari doesn't play nice with min-width / `min-w-fit`
* Use flex-shrink-0 instead for icons that start shrinking if it's sibling is too wide or the parent container shrinking causes the icon to shrink.
Addresses #1393
=> fix: safari icons stretching, use flex-shrink-0 instead

ui/admin/app/components/react-markdown.tsx
* makes sure target="_blank" is added to embedded `<a href="">` components
Addresses #1344
=> fix: add MarkdownLink to CustomMarkdownComponents

pkg/proxy/proxy.go
If the user had an old access token with a now-deconfigured auth provider and went to `/oauth2/start`, they would end up getting a `credential not found` error. This makes the error message a bit clearer, and deletes their cookie, so that if they try again, they will just end up using whichever auth provider is available.
This is a minor fix and does not need to go in before the release.
=> fix: return error when trying to use an unconfigured auth provider 

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/invokeService.ts
run agent invocations asynchronously to stop opening unnecessary event streams in the UI.
=> chore: switch to async agent/workflow invocations

pkg/cli/internal/token.go
There was no need for us to be storing info about auth providers here. Each time the user authenticates with a new Obot instance, they will go through the auth flow, and the token will be saved locally. We won't need to know which auth provider it used again.
=> fix: cli: don't store auth provider info

ui/admin/app/components/agent/icon/AgentIcon.tsx, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/icons/AssistantIcon.svelte
* fix -- wrong agent logo in dropdown of agents on user-ui
flex-shrink-0 fixes logo shrinking with longer text:
Addresses #1474
=> fix: user-ui agent logo in dropdown

pkg/services/config.go
This variable is not sensitive. It contains the path to a file that is also not sensitive. So it is safe to pass down to all tools. It is needed specifically by some of our credential helper tools.
=> fix: pass the encryption config var to tools

.github/workflows/user-ui.yml, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/icons/AssistantIcon.svelte
This PR made me realize that user ui only PRs will never pass the lint check
https://github.com/obot-platform/obot/pull/1484
=> Chore: Add lint check for user ui

ui/user/src/lib/components/messages/MessageIcon.svelte
Agent icon was not showing up in chat because we weren't passing the
current agent id in properly.
=> Fix: Resolve agent icon in chat

.github/workflows/docs.yml
Our pull request require a check called "build" to pass.
=> Chore: Rename docs build job

pkg/controller/handlers/cronjob/cronjob.go, pkg/controller/routes.go, pkg/storage/apis/obot.obot.ai/v1/cronjob.go, pkg/storage/apis/obot.obot.ai/v1/emailaddress.go, pkg/storage/apis/obot.obot.ai/v1/webhook.go
Removing existing cleanup method so that we can rely on client to decide when to remove triggers that are attached to a workflow.
https://github.com/obot-platform/obot/issues/1175
=> Fix: remove existing cleanup method

apiclient/types/emailreceiver.go, apiclient/types/zz_generated.deepcopy.go, pkg/api/handlers/emailreceiver.go, pkg/api/handlers/webhooks.go, ui/admin/app/components/webhooks/WebhookConfirmation.tsx, ui/admin/app/hooks/workflow-triggers/useWorkflowTriggers.ts
When email receiver is first created in ui, the emailAddress will always return with random string at the start even if alias is set. This is problematic as it will change to use alias email on refresh once controller has set the alias. 
https://github.com/obot-platform/obot/issues/1412
=> Fix: Fix alias api when email receiver is first created

pkg/api/handlers/agent.go, ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentAlias.tsx, ui/admin/app/components/agent/AgentContext.tsx
https://github.com/obot-platform/obot/issues/1254
Changed the alias logic in the frontend to match the behavior in backend. The idea is that when agent.AliasAssigned is null it means that the agent needs controller reconcilation and UI should start polling until it reaches a final state.
=> Fix: make sure only to load alias when aliaAssigned is true

.github/workflows/test-docker-build.yml
Rename the `Build Docker Image` GitHub workflow to `Test Docker Build` for clarity.
=> chore: rename docker build github workflow

pkg/gateway/types/oauth_apps.go
If the tenant ID is blank, then it will default to "common"
=> chore: remove tenant ID validation for microsoft365 oauth app

pkg/controller/data/agent.yaml
Issue: https://github.com/obot-platform/obot/issues/1528
=> chore: add oauthApps field to the default Obot agent

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/routes/_auth.threads._index.tsx
Addresses #1431 
Addresses #1355 
https://github.com/user-attachments/assets/18ffe479-76bb-4218-a608-4021e07d88d3
https://github.com/user-attachments/assets/41b1853d-ec13-4879-ab89-0dafd2ef32a0
* if user clicks Advanced, the section scrolls to bottom to bring contents into view
* filter out threads with `deleted` property as they're being deleted in the background
=> fix: threads refresh fix & advanced options scroll to bottom

ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/credentialApiService.ts
addresses #1510
https://www.loom.com/share/67c9aa29fce34dbc82670b72183194f2?sid=d459e9ed-eb26-45d1-90fa-cbb2c5acddb1
=> feat: add credential list to threads page sidebar

pkg/controller/handlers/knowledgeset/knowledgeset.go
We will need to wait for workspace name to be set, otherwise thread will have its own workspace created which will lose the file that user uploads too.
=> Fix: don't process to create threads when workspace name is not set

pkg/controller/data/agent.yaml
Issue: https://github.com/obot-platform/obot/issues/1528
=> chore: remove oauth-based apps from default agent

.github/workflows/release.yml
This will create tagged releases in the tools repos when we release Obot. This will make it easier to identify which commit of the tools repos are in which release.
If the tag already exists in a tools repo, then this won't change that release.
Requires: https://github.com/obot-platform/tools/pull/392 and https://github.com/obot-platform/enterprise-tools/pull/18
=> chore: add the ability to create releases for tools repos

go.mod, pkg/api/server/server.go, pkg/proxy/proxy.go
This PR refactors the way we store auth provider information with our access token cookies. Before, we were intercepting the cookies and inserting/removing auth provider information inside of them. This was a bit error-prone and unreliable. A much more simple solution is to just expect the provider info to be present in the name of the cookie.
In the case that there are multiple access token cookies present, we take the one that expires the farthest from now, under the assumption that that is what the user most recently logged in with. This shouldn't happen under ordinary circumstances, but could happen during development.
This PR also fixes a bug around token refresh that I accidentally introduced, where a whole ton of cookies would get created due to a malformed `Set-Cookie` header.
=> fix: store auth provider info in cookie name

pkg/api/authz/thread.go
Issue: https://github.com/obot-platform/obot/issues/1559
=> fix: allow non-admin access to a user's own thread files

docs/docs/05-installation/00-Installation.md
Fix the typo for the image path where `ghcr` was typed as `ghrc`
Existing
`ghrc.io/obot-platform/obot:latest`
Fixed
`ghcr.io/obot-platform/obot:latest`
=> Fix image path typo in Installation doc

ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/composed/PaginationActions.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/ui/input.tsx, ui/admin/app/components/ui/skeleton.tsx, ui/admin/app/hooks/pagination/usePagination.tsx, ui/admin/app/lib/service/api/invokeService.ts, ui/admin/app/lib/service/api/threadsService.ts, ui/admin/app/lib/service/pagination.ts
Addresses #1580 
- creates some rough abstractions for client side pagination (used to mock server side pagination until we suport it in backend)
- hooks up pagination to thread files view
- updates skeletons to take children
https://www.loom.com/share/781c47583175404cbef1f5a15adafacd?sid=e0d3edb6-a5d9-4567-97af-f7ff228a70e5
=> feat: implement pagination for thread files

ui/admin/app/components/agent/AgentContext.tsx, ui/admin/app/components/agent/AgentDropdownActions.tsx, ui/admin/app/components/agent/DeleteAgent.tsx, ui/admin/app/components/agent/UserAuthorizationSelect.tsx, ui/admin/app/components/agent/shared/AgentSelect.tsx, ui/admin/app/components/agent/shared/WorkspaceFilesSection.tsx, ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/knowledge/OAuthSignDialog.tsx, ui/admin/app/hooks/toolAuth/useToolAuthPolling.ts, ui/admin/app/lib/service/api/agentService.ts, ui/admin/app/lib/service/api/apiErrors.tsx, ui/admin/app/lib/service/api/primitives.ts, ui/admin/app/lib/service/api/service-primitives.ts, ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.threads.$id.tsx, ui/admin/app/routes/_auth.threads._index.tsx
Addresses #1581 
Refactor work performed only on agentService.ts (subsequent work can be done incrementally)
Improvements:
- provides a programatic way to create service methods with configurable capabilities
- abstracts a lot of the mess  useSWR
- loosens coupling with useSWR as a library (foreshadowing..?)
- provides builtin support for AbortControllers
- switches SWR keys to be arrays instead of objects. This allows us to meaningfully invalidate the api cache using partial keys
Things to Note:
- Going forward all service methods will only be able to take 1 parameter which must always be an object. It's a bit more restrictive, but it shouldn't prevent us from doing anything and I think it's worth it for the DX
Future work:
- we may want to improve the way keys are passed to …
=> chore: update service method primitives

ui/admin/app/components/agent/__tests__/Agent.test.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/workflow/__tests__/Workflow.test.tsx, ui/admin/app/lib/model/threads.ts, ui/admin/app/routes/__tests__/threads._index.test.tsx, ui/admin/app/routes/_auth.threads._index.tsx, ui/admin/test/mocks/models/threads.ts
What causes a rerender of `DataTable` is when `data` changes. Because `userMap` is not tied to that data, a rerender does not fire when getUsers.data is updated. Two solutions: Either preload to make sure the data is available before rendering or update `data` so it accounts for that information and does a rerender.
=> fix: threads page, users initially showing empty

ui/admin/public/assets/vllm-logo.svg
previous vLLM logo had a white background - new logo is their just their logo without the text "vLLM"
addresses https://github.com/obot-platform/obot/issues/1104
Looks like this now:
=> update vllm logo

ui/admin/app/components/composed/SetupBanner.tsx, ui/admin/app/components/composed/__tests__/SetupBanner.test.tsx, ui/admin/test/mocks/handlers/default.ts, ui/admin/test/mocks/models/authProvider.ts, ui/admin/test/mocks/models/modelProvider.ts, ui/admin/test/mocks/models/users.ts, ui/admin/test/setup.ts
* fix for configure banner still showing model provider needs configuring even though it has been configured
* adds back in the filter instead of every check at checking isSetupPage 
* adds test cases for checking!
Addresses #1639
=> fix: config banner still showing model provider needs configuring even if configured

apiclient/types/modelprovider.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx, ui/admin/app/lib/model/providers.ts
Before: see https://github.com/obot-platform/obot/issues/1638
After (Cookie Secret hidden for all auth providers): 
Related Tool PRs: https://github.com/obot-platform/tools/pull/405 & https://github.com/obot-platform/enterprise-tools/pull/24
=> change: allow hiding provider parameters in the UI

pkg/api/handlers/authprovider.go, pkg/gateway/server/dispatcher/dispatcher.go, pkg/gateway/server/oauth.go, pkg/gateway/server/token.go, pkg/proxy/proxy.go, pkg/services/config.go
for https://github.com/obot-platform/obot/issues/1630
This is (another) refactoring of how we handle auth cookies. Now, instead of doing one cookie per auth provider, we are just doing one cookie period. We figure out which auth provider is associated with it by storing its hash in a cache, but that only lasts for 24h before it gets removed. If it's not in the cache, we try it with each configured auth provider until we find one that recognizes it, and then we cache that auth provider in association with that token hash.
=> enhance: use just one auth cookie for Obot

ui/admin/app/components/knowledge/AddKnowledgeButton.tsx, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/ToolOauthConfig.tsx, ui/admin/app/components/tools/ToolTooltip.tsx, ui/admin/app/components/tools/__tests__/ToolCatalog.test.tsx, ui/admin/app/components/tools/toolGrid/ToolCardActions.tsx, ui/admin/app/hooks/oauthApps/useOAuthApps.ts, ui/admin/test/mocks/models/toolReferences.ts
https://github.com/user-attachments/assets/176bfbc2-5c6d-4a15-9c13-baef08adc513
* opens up the auth config instead when clicking 'Setup' in the Tool Tooltip
* fix for tool that doesn't have bundle but has oauth not showing it requires configuration
Addresses #1408
=> fix: setup tooltip takes user to auth config directly

ui/admin/app/components/agent/AgentContext.tsx, ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/workflow-triggers/ScheduleForm.tsx, ui/admin/app/hooks/cronjob/useCronjob.tsx, ui/admin/app/hooks/workflow-triggers/useWorkflowTriggers.ts, ui/admin/app/lib/service/api/agentService.ts, ui/admin/app/lib/service/api/credentialApiService.ts, ui/admin/app/lib/service/api/cronjobApiService.ts, ui/admin/app/lib/service/api/service-primitives.ts, ui/admin/app/lib/service/api/workspaceTableApiService.ts, ui/admin/app/lib/service/revalidation.ts, ui/admin/app/routes/_auth.workflow-triggers._index.tsx, ui/admin/app/routes/_auth.workflow-triggers.schedule.$trigger.tsx, ui/admin/app/routes/_auth.workflows.$workflow.tsx
- switches service method default cache keys back to an object structure
- service fetchers must now provide a key method that returns a UNIQUE string to be used as an identifier
- keys will be autogenerated as an object with the provided key, and parameters
- revalidation will invalidate cach keys that match the service method's key, AND partially match the provided revalidation params
=> chore: create safer, fault tolerant method of cache key invalidation with service method primitives

ui/user/src/lib/components/messages/Message.svelte
=> feat: add description to prompt credentials in user UI

pkg/api/handlers/modelprovider.go
Issue https://github.com/obot-platform/obot/issues/1385
=> fix: use http 422 instead of 407 during model provider validation so that the error shows up properly

ui/admin/app/hooks/oauthApps/useOAuthApps.ts
* quick fix oauth apps not showing as configured on load, allowing revalidation on mount
* longer fix: looking into why cache is initially empty (though it should have the data from preload)
=> fix: allow revalidation with useOauthAppMap

pkg/controller/handlers/toolinfo/toolinfo.go, pkg/controller/routes.go
When removing the last tool that uses a credential, this change will remove the
old credential. The effect is that the user will have to authenticate the tool
again if a tool requiring that credential is added.
Issue: https://github.com/obot-platform/obot/issues/1570
=> fix: remove old credentials from when removing tools

pkg/api/handlers/invoke.go
The invoke repsonse doesn't have a run, so we should check for the run before
trying to get the run's Name.
=> fix: stop panicking when invoking workflows

ui/admin/app/lib/service/api/__tests__/service-primitives.test.ts, ui/admin/app/lib/service/api/service-primitives.ts
- additionally extracts types for the `createFetcher` method
=> chore: add tests for service primitives

apiclient/types/toolreference.go, pkg/api/handlers/toolreferences.go, pkg/controller/controller.go, pkg/controller/handlers/toolreference/migrate.go, pkg/controller/handlers/toolreference/toolreference.go, pkg/controller/routes.go, pkg/storage/apis/obot.obot.ai/v1/toolreference.go, pkg/storage/openapi/generated/openapi_generated.go, pkg/tools/resolve.go, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/lib/model/toolReferences.ts, ui/admin/app/routes/_auth.tools._index.tsx, ui/admin/test/mocks/models/toolReferences.ts
This PR implements the tool index refactoring logic defined at https://github.com/obot-platform/obot/issues/1026. It has both frontend and backend changes to support new indexing logic.
Backend:
- Dropping `all: true` and always import the first tool and its shared tools from gptfile. 
- Dropping bundle metadata and always relied on share tools
- Add api to support bundle tool and bundle child tools
- Apply same code to import both custom and built-in tools.
- Add tool commit
Frontend:
- Stop using category as a way to group bundle tool
- Group tool and bundle using new api fields.
- Add tool commit
Should fix
- https://github.com/obot-platform/obot/issues/1525
- https://github.com/obot-platform/obot/issues/1526
- https://github.com/obot-platform/obot/issues/1527
=> Chore: Refactor tool indexing

ui/admin/app/components/ui/button.tsx, ui/admin/app/lib/service/api/workspaceTableApiService.ts, ui/admin/app/routes/_auth.threads.$id.tsx, ui/admin/app/routes/_auth.threads._index.tsx
- loading states now replace all content with a loading spinner
- prevents buttons from expanding horizontally during loading states
- allows for simpler code with button internals
=> enhance: simplify button loading state

apiclient/types/thread.go, pkg/api/handlers/agent.go, pkg/api/handlers/assistants.go, pkg/api/handlers/modelprovider.go, pkg/api/handlers/threads.go, pkg/controller/handlers/threads/threads.go, pkg/controller/routes.go, pkg/invoke/invoker.go, pkg/storage/apis/obot.obot.ai/v1/thread.go, pkg/storage/openapi/generated/openapi_generated.go
This change introduces the concept of an ephemeral thread. These are threads
that are typically used for system-based or temporary tasks. Such threads will
be cleaned up 12 hours after their creation.
Issue: https://github.com/obot-platform/obot/issues/1723
=> enhance: cleanup ephemeral threads after 12 hours

ui/admin/app/components/composed/ComboBox.tsx, ui/admin/app/components/composed/DataTable.tsx, ui/admin/app/components/sidebar/Sidebar.tsx, ui/admin/app/routes/_auth.task-runs._index.tsx, ui/admin/app/routes/_auth.tasks._index.tsx
* rearrange sidebar nav items per Craig's request
* fix combobox highlighting items with same name (but different id)
fixes:
adds agent name if the workflow has a duplicate title with someone else:
=> fix: rearrange sidebar nav items & combobox multi-highlight name fix

ui/admin/app/components/agent/AgentForm.tsx
=> fix: expand agent name/description fields to take up full width

ui/admin/app/lib/model/oauthApps/providers/google.ts
Added webmaster and webmaster.readonly scopes for Google Search Console. Also added Google Search Console as an API to enable.
Follow up doc update for obot-platform/tools#430
=> chore: add additional scopes and apis to google oauth instructions

pkg/api/authn/noauth.go, pkg/bootstrap/bootstrap.go, pkg/gateway/client/auth.go, pkg/gateway/client/identity.go, pkg/gateway/db/db.go, pkg/gateway/types/identity.go, pkg/services/config.go
=> fix: identity: use the provider user ID as primary key

apiclient/types/user.go, pkg/api/handlers/authorizations.go, pkg/gateway/server/user.go, pkg/gateway/types/users.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/components/auth-and-model-providers/constants.ts, ui/admin/app/components/user/UserMenu.tsx, ui/admin/app/components/user/__tests__/UserMenu.test.tsx, ui/admin/app/lib/model/auth.tsx, ui/admin/app/lib/model/users.ts, ui/admin/app/routes/_auth.auth-providers.tsx, ui/admin/test/mocks/handlers/default.ts, ui/admin/test/server.ts
* uses username for github, otherwise defaults to email
* Addresses #1397 
github:
google:
TODO:
=> fix: show github handle instead of email for github auth provider

pkg/api/handlers/assistants.go
The user UI uses a different invoke API than the old admin UI. This change
ensures that chat runs created from the user UI are prioritized above workflow
runs.
Issue: https://github.com/obot-platform/obot/issues/1694#issuecomment-2661147824
=> fix: make assistant runs chat runs

pkg/tools/resolve.go
When looking for subpath from subtool, just check if path starts with http:// or https:// to see if it is a remote tool. If not, should be able to resolve the correct gptfile by calculating rel path.
This should fix the issue where hubspot subTool referenced in different gptfile not showing up. The previous fix didn't work out due to the path being absolute path.
=> Fix: use relative path correctly when it is not a remote source

ui/admin/app/components/signin/SignIn.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx
Addresses #1557 -- clicking go back on 403 error.html should redirect to proper url
Note: Requires merge of 
Addresses #1273 -- "Capabilities" instead of "Capability"
=> fix: capabilities tools category and 403 oauth redirect

pkg/gateway/server/oauth_apps.go, pkg/gateway/types/oauth_apps.go
This PR supports pulling slack bot token from oauth process. This requires tools to specify `scope` instead of `user_scope` to get token from bot.
Require https://github.com/obot-platform/tools/pull/451.
=> Enhance: Support slack bot token

ui/admin/app/components/composed/typography.tsx
* if content is short enough, don't render tooltip -- maybe overkill to check the ref? 😅 
* cursor-help instead of cursor-pointer
=> fix: tools description help cursor & conditional tooltip based on content length

pkg/tools/resolve.go, ui/admin/app/lib/model/oauthApps/providers/slack.ts
This PR adds instruction to slack oauth app setup to add bot token scope in order to use Slack Bot tool. Also fixed an issue in indexing tools where specific gpt file is specified.
=> Fix: add instruction for slack

ui/admin/app/components/chat/Chatbar.tsx, ui/admin/app/components/task/steps/StepBase.tsx
* fixes min-height on chatbar & tasks steps looking like this:
=> fix: autosize min-height on task steps & chatbar

ui/admin/app/components/ui/markdown.css, ui/admin/app/components/ui/markdown.tsx
* adds paste support to format to markdown
* adds source/diff in toolbar in case parsing errors
* fix ul/ol styling in mdx-editor
* add codeblock support
Addresses #1759
=> fix: wysiwyg list styling & add source mode for markdown copy & paste

ui/user/src/lib/components/navbar/Files.svelte
* adds overflow for files list
Addresses #1769
=> fix: can't scroll when there's too many files

pkg/gateway/server/oauth_apps.go, pkg/gateway/server/server.go, pkg/render/render.go, pkg/services/config.go
for https://github.com/obot-platform/obot/issues/1751
With this change, newly configured oauth apps will have their client secrets stored as credentials so that they get encrypted.
Existing oauth apps, when upgrading to this code, will continue to have their client secrets in the `oauthapp` table, alongside the rest of their configuration. They will not get the new credential created unless they are reconfigured. Once reconfigured, the old revision will still exist in the database due to how kinm manages object revisions, but they should get pruned eventually.
=> fix: oauth apps: store client secret as a credential

pkg/storage/apis/obot.obot.ai/v1/thread.go
When a thread's agent gets deleted, the thread itself should be deleted also. This fixes that.
=> fix: delete threads if the agent was deleted

ui/admin/app/components/agent/AgentForm.tsx, ui/admin/app/components/agent/AgentIntroForm.tsx
To address: https://acorn-io.slack.com/archives/C07P0EZR917/p1740513904681939
* seems like these are firing every time with a key change which may be causing the lag and periodic loss of key input
Wondering should we be resetting whenever there's an update to agent?
=> fix: avoid excessive form resets

pkg/gateway/server/oauth_apps.go
Need to use Error.As to assert not found error and fallback to use app.spec.clientSecret.
=> Fix: use error.As to fallback

ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/services/chat/types.ts
Addresses #1823 
* slight update to credentials based on api call -- `toolName` instead of `name`
* `icon` was also available so threw that in too!
=> fix: update credentials in user-ui

go.mod, pkg/api/authz/authz.go, pkg/api/router/router.go
The /debug/metrics endpoint is exposed to any unauthenticated user so that the
prometheus service can access the metrics.
=> chore: expose workqueue metrics

ui/admin/app/components/ui/markdown.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
* copy & paste event handler should only trigger when user is focused on _contentEditable class, otherwise copy & paste is being triggered on image/link dialog and link/image url is getting pasted into content
Addresses #1759 
Related to #1817
=> fix: copy & paste listening only on markdown contentEditable

ui/admin/app/components/agent/shared/constants.ts, ui/admin/app/lib/model/toolReferences.ts, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/model/tools.ts
Addresses #527
- ensures that agent required tools are disabled so the user cannot remove them
=> fix: stop filtering agent level tools from the tools dropdown

pkg/controller/handlers/alias/alias.go
Workflows were changed to not support aliasing. This controller would error
continuously. Since this will never recover, it makes sense to delete them.
=> fix: delete invalid aliases

Makefile, go.mod, go.sum, pkg/api/handlers/threads.go, pkg/controller/handlers/inactive/inactive.go, pkg/controller/handlers/runs/runs.go, pkg/controller/handlers/threads/threads.go, pkg/controller/routes.go, pkg/services/config.go, pkg/storage/apis/obot.obot.ai/v1/inactive.go, pkg/storage/apis/obot.obot.ai/v1/run.go, pkg/storage/apis/obot.obot.ai/v1/thread.go
Inactive runs will not be processed by the controller and will be removed from
its cache. These runs will still be accessible from the API.
This logic is implemented such that other objects can be marked as inactive and
the controller will similarly ignore them.
=> feat: mark finished runs as inactive

ui/user/src/lib/components/messages/Message.svelte
As per @ibuildthecloud's request 
=> chore: revert loading ball to old loading indicator

pkg/controller/handlers/workflowexecution/workflowexecution.go
Copy user IDs from the project thread to workflowexecutions,
ensuring the user's preferred timezone is injected into the
resulting run. Before this, running tasks always thought the
user's preferred timezone was UTC.
https://github.com/obot-platform/obot/issues/1951
=> fix: propagate user timezone to tasks

pkg/api/server/server.go, pkg/gateway/client/identity.go, pkg/gateway/types/users.go
**Reviewers**: please double-check my logic in this, as well was my design choices surrounding migration that I outlined below.
for https://github.com/obot-platform/obot/issues/1807
This PR adds a distinction between users with a verified email address or an unverified email address. Google and GitHub verify email addresses, so we automatically treat those as verified, and everything else as unverified.
When checking to see if a new identity matches an existing user, we only look for an existing user if the new identity has a verified email address, and the existing user does too. This is the only way we can safely continue to match identities to users based on email addresses.
There is no automatic migration to do. The new `VerifiedEmail` field on the user starts out as null. We fill it …
=> enhance: distinguish between verified and unverified email addresses

apiclient/types/project.go, pkg/api/handlers/projects.go, pkg/api/handlers/threads.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/components/composed/Filters.tsx, ui/admin/app/components/composed/typography.tsx, ui/admin/app/components/sidebar/Sidebar.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/user/UserMenu.tsx, ui/admin/app/hooks/useRouteInfo.ts, ui/admin/app/lib/model/project.ts, ui/admin/app/lib/model/threads.ts, ui/admin/app/lib/model/users.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/routers/baseRouter.ts, ui/admin/app/lib/routers/userRoutes.ts, ui/admin/app/lib/service/api/projectApiService.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/__tests__/chat-threads._index.test.tsx, ui/admin/app/routes/_auth.chat-threads._index.tsx, ui/admin/app/routes/_auth.obots._index.tsx, ui/admin/app/routes/_auth.obots.tsx, ui/admin/test/mocks/models/projects.ts, ui/admin/test/mocks/models/threads.ts
addresses #1958
- adds top level obot page
- adds filters for `Spawned from`, `Agent`, `Created By`
- adds `Obot` filter for the `/chat-threads` page
- defaults to filtering out "spawned" obots
- provides actions for opening an obot in the User UI, and deleting the obot (with confirmation)
=> feat: add top level obot page to admin ui

pkg/api/handlers/agent.go, pkg/api/handlers/files.go
Issue: https://github.com/obot-platform/obot/issues/1831
=> enhance: allow 100MB workspace file uploads

ui/user/src/app.css, ui/user/src/app.html, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/editor/FileEditors.svelte, ui/user/src/lib/components/sidebar/Tasks.svelte, ui/user/src/lib/components/sidebar/Threads.svelte
* get scrollbars consistent
* some minor styling updates for spacing cleanup, etc.
light mode:
=> fix: consistency scrollbars ui

ui/user/src/lib/components/Thread.svelte
=> fix: reset to instant-scroll when switching threads

pkg/controller/handlers/runs/runs.go, pkg/controller/handlers/threads/threads.go, pkg/controller/routes.go
A previous change made "old" runs inactive. Inactive runs are not cached nor
watched by the controllers.
This wasn't a problem until the cached GET behavior was changed to no longer do
an uncached get when a not-found error occurs. Now we need to ensure that every
thread's latest and current runs are active.
=> fix: ensure threads current and latest runs are active

ui/user/src/lib/components/edit/GenerateIcon.svelte
The current prompt for generating Obot icons results in generic humans being generated for most Obot descriptions. Tweak the prompt to generate more unique characters.
=> enhance: default generated obot icon prompt

ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/lib/model/threads.ts, ui/admin/app/routes/_auth.chat-threads.$id.tsx, ui/admin/app/routes/_auth.chat-threads._index.tsx, ui/admin/app/routes/_auth.task-runs.$id.tsx, ui/admin/app/routes/_auth.task-runs._index.tsx, ui/admin/app/routes/_auth.tasks.$id.tsx, ui/admin/app/routes/_auth.tasks._index.tsx, ui/admin/test/mocks/models/threads.ts
`Thread.agentId` and `Thread.workflowID` were renamed respectively to `Thread.assistantID`, and `Thread.taskID` in the backend, but were not updated in the admin UI models.
The solution: update the models in the admin ui to reflect the backend changes
=> fix: broken chat thread and task run lists in admin ui

apiclient/types/modelprovider.go, pkg/api/handlers/providers/modelproviders.go, pkg/controller/handlers/toolreference/toolreference.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/lib/model/providers.ts
Now we can use `modelProvider.error` [in the UI code](https://github.com/obot-platform/obot/blob/main/ui/admin/app/components/auth-and-model-providers/ModelProviderLists.tsx) to put some icon or whatever there.
I'm not sure if we should call it "Not configured" in case of an error, as we don't have error classes and it could as well be a network issue. Maybe a "Defunct" like message would be more appropriate.
Ugly example:
Issue: https://github.com/obot-platform/obot/issues/819
=> change: handle openaiAPI-style errors + expose modelProviderStatus.error to the UI

ui/user/src/lib/components/ToolPill.svelte, ui/user/src/routes/home/+page.svelte
* adds white bg for tools in homepage obot card
* adds counter pill when tools exceed 3 tools
* adds tooltip for hover over of tool pills
=> fix: homepage tool dark icon & counter tool pill

pkg/controller/handlers/runs/runs.go, pkg/controller/handlers/runstates/migrate.go, pkg/gateway/client/runstate.go
The incorrect gorm error was used to detect "already exists" errors. That is
fixed here. Additionally, the old RunStates are now only cleaned up in one spot,
and the new RunStates are cleaned up when a run is deleted.
=> enhance: better error detection when migrating run states

pkg/controller/handlers/runstates/migrate.go, pkg/gateway/client/runstate.go
The gorm errors are not proper for detecting already exists errors. To work around this in all database cases, we try to get before creating to properly detect the error.
=> fix: get before creating run states to detect already exists

ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/edit/Tools.svelte
=> enhance: round out tool borders in edit tool list and catalog (creates consistency with other tool icons)

ui/user/src/lib/components/sidebar/Threads.svelte
Replaced fixed-width constraint with auto-width to ensure full text visibility
in the thread menu. Also renamed "Edit" button to "Rename" for better clarity
of purpose.
Addresses https://github.com/obot-platform/obot/issues/2121
=> fix(ui): improve thread menu width and clarify rename action

pkg/api/handlers/tasks.go, pkg/emailtrigger/emailtrigger.go, pkg/storage/apis/obot.obot.ai/v1/emailaddress.go, ui/user/src/lib/components/tasks/Trigger.svelte
I changed the task.alias to be a short version of 12 character, this will be used for webhook and email trigger. 
Make the email address from task prefixed with task name to be more user friendly, and in the backend we will only match the receiver that match the alias in the last part.
demo: https://www.loom.com/share/071ea961f7d74e34bf99de4f6dadf0b9
=> Fix: change task's alias, matching alias from email

ui/user/src/lib/components/Thread.svelte
addresses #2171
https://www.loom.com/share/9b2be141e85b411a86c87e72ae73558e?sid=d44a1225-8b29-4e15-a280-07c708f6c9c0
=> fix: prevent tooltips from overlaying popovers in input actions

ui/user/src/lib/components/edit/ToolCatalog.svelte
Addresses https://github.com/obot-platform/obot/issues/2120
e.g. before change (unsorted)
e.g. after change (sorted)
Screenshot 2025-03-14 at 11.26.57 PM
=> enhance: lexicographically sort tool catalog

ui/user/src/lib/components/Thread.svelte
There should only be one divider below the Obot details in a chat.
=> fix: rm extra divider in chat

ui/user/src/routes/home/+page.svelte
* rearranges padding so sticky header takes up viewport width
* removes ::after
=> fix: my obots header sticky fix

ui/user/src/lib/components/Thread.svelte
=> fix: use bug icon for issue reporting in mobile view

ui/user/src/app.css
Quick fix to make dialogs centered by default.  Maybe that's bad, but I'm guessing something changed between tailwind 3 and 4 regarding this.
=> bug: dialogs are not centered by default

ui/user/src/lib/components/navbar/Menu.svelte
=> bug: move menu up one layer to not get overlap on the home page

ui/user/src/app.css, ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/components/sidebar/Threads.svelte
* fixes for the profile nav (md:w-72 not great for long emails, use w-fit instead)
* fix for file editors overflow
* remove `composes` (This is my b, having Cursor translate css for me to speed up converting 😓) (checked: button-primary list-button-primary button-secondary button-small) ex:
=> fix: editors overflow & profile nav width

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte
Add copy and edit buttons to chat messages that allow users to copy Obot responses to the clipboard and edit them as a file.
Addresses https://github.com/obot-platform/obot/issues/2100
https://github.com/user-attachments/assets/96290daf-3b81-4fb1-a3ad-4a0c6dd18a39
=> feat: add copy and edit buttons to obot responses

ui/admin/app/lib/utils/time.ts, ui/admin/app/routes/_auth.users.tsx
Previously, depending on the time the user was created, it seemed like a user
was active before the user was created. This is because activity is at the day
granularity. This change makes the created field also displayed at the day
granularity.
=> fix: display user "created" field as relative to the day

ui/user/src/lib/actions/popover.svelte.ts, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/Credentials.svelte
* add `disablePortal` option in popover action
* fixes credentials list popover being blocked by `dialog` ancestor natively moved to #top-level viewport layer
=> fix: credentials list popover blocked by dialog

ui/user/src/lib/components/messages/Message.svelte
Addresses https://github.com/obot-platform/obot/issues/2292
=> fix: hide copy and edit buttons when message has no content

ui/user/src/lib/components/Notifications.svelte
* line clamp of 3 to avoid large error notifications from disrupting experience
Addresses #2115
=> fix: line clamp on error notifications

go.mod, go.sum, pkg/invoke/invoker.go
https://github.com/gptscript-ai/gptscript/pull/956
Using gptscript sdk to terminate thread and get proper message back. suggested by darren https://acorn-io.slack.com/archives/C07P0EZR917/p1743120573464899
https://github.com/obot-platform/obot/issues/1982
=> Fix: gracefully abort thread using sdk

aws-encryption.yaml, azure-encryption.yaml, gcp-encryption.yaml, pkg/credstores/credstore.go, pkg/encryption/encryption.go, pkg/gateway/client/client.go, pkg/gateway/client/runstate.go, pkg/gateway/server/server.go, pkg/services/config.go
RunStates can have some personally identifiable information in them depending on
tool calls. This change encrypts the sensitive parts of the run state object.
=> Encrypt-run-states

pkg/gateway/client/runstate.go
The dataCtx is supposed to be optional, but some implementations don't treat is that way. Instead, pass a blank default value.
=> fix: pass non-nil dataCtx when encrypting

ui/user/src/app.css, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/CollapsePane.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/edit/Tools.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/components/sidebar/Threads.svelte, ui/user/src/lib/components/tasks/OnDemand.svelte, ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/o/[project]/+page.svelte
- Bring up sidebar by default when layoutEditor is not open
- When going into Obot, start a new Thread (as if you clicked Create New Thread) if there are no threads OR select the first thread in the list
- Update tools to show Thread Tools /projects/{projectId}/thread/{threadId}/tools GET & PUT
- Clicking Tools in the Input show just open the Tool Catalog straight away
- Change Tool Catalog UI to show Selected and Available at same time (preferably without checkboxes and showing UI similar to the selected only list)
- Add Description: In Tools Collapse Pane: "Tools added here are available to all threads"
- Change description for Task On Demand args to textarea (Knock out here since it's pretty quick)
=> tool catalog ui & use thread tools endpoint

apiclient/types/tasks.go, pkg/api/handlers/cronjob.go, pkg/controller/handlers/cronjob/cronjob.go, pkg/storage/apis/obot.obot.ai/v1/cronjob.go, pkg/storage/openapi/generated/openapi_generated.go, ui/user/src/lib/components/tasks/Schedule.svelte, ui/user/src/lib/components/tasks/Type.svelte, ui/user/src/lib/services/chat/types.ts
This PR added support to set timezone to current browser's timezone in scheduled task. This is so that the cron schedule runs the task per user's timezone. If user is in the different time zone when viewing the task, ui will display the timezone in order to show the difference. The timezone will be reset once user change the selection. 
https://github.com/obot-platform/obot/issues/1480
=> Fix: support setting timezone in user ui

ui/user/src/lib/components/ObotCard.svelte, ui/user/src/lib/components/ReLoginDialog.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/services/chat/http.ts, ui/user/src/lib/services/chat/types.ts, ui/user/src/lib/sort.ts, ui/user/src/routes/+layout.svelte, ui/user/src/routes/+page.ts, ui/user/src/routes/catalog/+page.svelte
https://www.loom.com/share/6aa8882575da44abb975bb9b469b94f3
* handling 401 when loading a page: prompts log-in with redirect
* handling 401 when user has already logged in: receives session expired dialog and log in button
* add owner tag to obot card
* also includes hardcoded sort based on obot name for featured: 
Gmail Unsubscriber      
Slack2GitHub
Job Hunt Helper           
Granite Gains
=> enhance: obot card owner tag & 401 handling

ui/user/src/lib/components/FeaturedObotCard.svelte, ui/user/src/lib/components/ObotCard.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/url.ts, ui/user/src/routes/+page.svelte, ui/user/src/routes/+page.ts, ui/user/src/routes/catalog/+page.svelte, ui/user/src/routes/home/+page.svelte, ui/user/src/routes/o/[project]/+page.ts
From Will's Feedback:
https://www.loom.com/share/3889568825ab41368cdfcfe76ae55071
Sidebar Obot Selector Dropdown:
Log In & Visiting Root:
Homepage: 
* Obot Card:
* For new user:
Obot Catalog:
=> enhance: homepage & obot redirect/selector updates

pkg/api/handlers/version.go, pkg/api/router/router.go, ui/admin/app/lib/model/version.ts, ui/admin/test/mocks/models/version.ts, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/services/chat/types.ts
I think we plan on changing this in another follow-up to put the button somewhere else, but we might as well now hide it when it's not needed.
=> fix: only show log out all button if using db for session storage

apiclient/task.go, pkg/api/handlers/tasks.go, pkg/controller/handlers/workflowstep/invoke.go, pkg/invoke/invoker.go, pkg/invoke/step.go, pkg/storage/apis/obot.obot.ai/v1/workflowexecution.go, pkg/storage/openapi/generated/openapi_generated.go
It is possible for users to construct tasks that call other tasks. A problem arises when a task call cycle is accidentally constructed because the task will never complete. This change tracks task breadcrumbs so the task invoke tool can detect cycles.
=> fix: detect task calling cycles

pkg/controller/handlers/workflowexecution/workflowexecution.go, pkg/controller/handlers/workflowstep/invoke.go
If a workflow execution failed for some reason, this was not being reported correctly in the external call information. It would look like the task would run forever.
This change will detect errors and report them on the external run output.
=> fix: report errors for workflow executions

aws-encryption.yaml, azure-encryption.yaml, gcp-encryption.yaml, pkg/gateway/client/apiactivity.go, pkg/gateway/client/client.go, pkg/gateway/client/identity.go, pkg/gateway/client/runstate.go, pkg/gateway/client/user.go, pkg/gateway/db/db.go, pkg/gateway/db/migrations.go, pkg/gateway/server/oauth.go, pkg/gateway/server/router.go, pkg/gateway/server/tokenreview.go, pkg/gateway/server/user.go, pkg/gateway/types/activity.go, pkg/gateway/types/identity.go, pkg/gateway/types/users.go, pkg/services/config.go
To make this work, some hashed values are also added to the database to ensure that getting users and identities still works as expected. That is, we still need to get/update user by username. Therefore, we store a hash of the username in the database for selecting. Similar for some other fields.
Another field was added to users and identities: encrypted. This field tracks if a user or identity is encrypted in the database for migration and enabling encryption when it was off to begin with. This new field is really an implementation detail, which means that all gets/updates/creates for users and identities should be done through the client forever more.
Necessary migrations are also added for the hashed fields that are now required for users and identities.
=> enhance: add encryption to PII in users and identities

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/editor/Milkdown.svelte, ui/user/src/lib/services/chat/messages.ts, ui/user/src/lib/services/chat/thread.svelte.ts
* added an onItemsChanged optional fn to pass into the instantiated Thread class
Addresses #2437 
Slack convo for reference: https://acorn-io.slack.com/archives/C07P0EZR917/p1744065127996349
I did try removing the `readonly` on `items` and fiddled with it to trigger reactivity but it looks like svelte triggers reactivity based on assignment so changing something on `this.#items` will not necessarily trigger a render like changing `layout.items` would.
=> fix: layout.items updates on message file item changes

ui/user/src/lib/components/messages/Message.svelte
Change how authentication method selection prompts are displayed in the
user UI so that:
- The submit button isn't displayed
- The field name and "not visible to AI" disclaimer are
hidden
- The text of the cancel button is changed to "Nevermind, don't
authenticate"
- Buttons are all the same width and are centered below the description
https://github.com/user-attachments/assets/bfbeb3ad-1315-4361-8e8e-7e07c80b650f
https://github.com/user-attachments/assets/afdd52eb-a22c-4c1b-bfda-573e2555ce55
https://github.com/user-attachments/assets/797fb60e-7738-4ef4-9d2e-6430b4affab3
Note: The logic to use this formatting for the prompt form is predicated
on having a single field named "Authentication Method" that has defined
`options`. This is probably not the best way to discriminate here.
Another …
=> enhance: refactor authn method selection prompts

pkg/gateway/server/oauth_apps.go, pkg/storage/apis/obot.obot.ai/v1/slacktrigger.go, pkg/storage/openapi/generated/openapi_generated.go
It turns out that assigning slack receiver name to trigger doesn't work well in copied obot, it is hard to trace the original slack receiver. Just relying on parent thread to delete should be fine for now.
=> Fix: don't assign slack receiver to triggers

go.mod, go.sum
This will bring in the fixes from https://github.com/gptscript-ai/gptscript/pull/959
=> chore: bump gptscript dependency

pkg/gateway/client/user.go, pkg/gateway/server/activeusers.go, pkg/gateway/server/logout_all.go, pkg/gateway/server/user.go
There were a couple issues keeping a user from being able to do this. First, when encryption is enabled, the user was not able to remove their account because it could not be found. This change switches the delete user method to use the hashed_username field.
Secondly, when the user successfully removed their account, the cookie they used to authenticate would still be valid. The UI would immediately called /api/me and the user would be authenticated and a new user created. This change tells the browser to remove the cookie so this does not happen.
=> fix: allow user to delete their account from the UI

pkg/gateway/client/identity.go, pkg/gateway/client/user.go, pkg/gateway/server/user.go
When a user is created, the ID is 0 until it is inserted into the database. Therefore, this field is not safe to use in the data context because it will be different when we try to decrypt it.
This change also includes a force query parameter for the encrypt-all-users API that will force re-encryption of all users regardless if those users are already encrypted.
=> fix: stop using the user ID in the data context for encryption

pkg/api/authn/anonymous.go, pkg/api/authn/token.go, pkg/api/authz/authz.go, pkg/services/config.go
Admins still have access to this endpoint. A new metrics group is added that also has access. The Otel bearer token is the only user in that group.
=> enhance: move the /debug/metrics endpoint behind authentication

main.go
Add tzdata so that we can use time.LoadLocation to calculate time for cronjob to run in correct timzone. The image we use don't have it.
https://github.com/obot-platform/obot/issues/1480
=> Fix: add tzdata

pkg/controller/data/default-models.yaml, pkg/controller/handlers/toolreference/toolreference.go, pkg/services/config.go, ui/admin/app/components/model/constants.ts
As discussed in Slack, bump default OAI model from `gpt-4o` to `gpt-4.1`
=> enhance: bump default openAI model from gpt-4o to gpt-4.1

ui/user/src/lib/components/Confirm.svelte
* moved the stylings in `<div role="dialog" class="relative max-h-full w-full max-w-md">` up a level & removed the div from structure
* Tested on Safari & Chrome
=> fix: ConfirmDialog safari, move stylings up to dialog element

pkg/controller/handlers/threads/threads.go, pkg/storage/apis/obot.obot.ai/v1/thread.go, pkg/storage/openapi/generated/openapi_generated.go
This PR fixed an issue so that if a task is shared from a shared project, modification to the task will not be reverted.
https://github.com/obot-platform/obot/issues/2539
=> Fix: only copy task from shared parent once

ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/edit/Credentials.svelte, ui/user/src/lib/components/navbar/Credentials.svelte
When adding tools into thread, the credential user added in the message will not be showing in credential dialog. This is because in frontend we only match the project tools, not thread tools. This pr changes to respect the thread tool if thread is is actively set in url.
https://www.loom.com/share/c6d1e6983fa54c5984a4e7f5b50a8f25
https://github.com/obot-platform/obot/issues/2403
=> Fix: make sure include thread tools when listing credentials

ui/admin/app/components/agent/shared/constants.ts, ui/admin/app/lib/model/toolReferences.ts, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/o/[project]/+page.ts
- Allow users to enable/disable capabilities in the project (Obot)
scoped tool picker in the user UI
- Mark memory bundle as a capability in the admin UI
Note: Explicitly hidden capabilities like threads and knowledge are still
hidden in both tool picker scopes.
Addresses https://github.com/obot-platform/obot/issues/2603
=> enhance: enable optional capabilities in project scoped tool picker

pkg/gateway/client/session.go, pkg/gateway/client/user.go
This ensures that the sessions are deleted successfully from the session storage.
Issues: https://github.com/obot-platform/sensitive-issues/issues/31, https://github.com/obot-platform/obot/issues/2581
=> fix: decrypt identities when deleting a user

pkg/render/render.go
The end of the space in a task name is breaking the chat.
=> Fix: trim space for task name

pkg/invoke/invoker.go
=> fix: fix possible nil pointer deref when checking error messages

ui/admin/app/components/sidebar/Sidebar.tsx
File scanners should be available regardless of whether authentication is enabled.
=> fix: remove authentication requirement for file scanners

pkg/gateway/client/session.go
Turns out that it was possible to get into a state where the user would get a 500 when trying to log out of all other sessions. This would happen if they had an identity tied to a previously configured but now deconfigured auth provider, so that sessions table didn't exist. This fixes that by checking for the table before we try to delete sessions from it.
=> fix: check table existence before deleting sessions

ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/components/sidebar/McpServers.svelte, ui/user/src/routes/mcp/+page.ts
temporary changes:
* add the matching bundle tool along with added mcp server
* show bundle tools in MCP Servers in the agent sidebar
* added sort update for obots dropdown here, addresses #2630
=> chore: temporarily use bundle tools for mcp servers

.github/workflows/test.yaml, Makefile, go.mod, pkg/controller/handlers/cronjob/cronjob.go, pkg/controller/handlers/cronjob/cronjob_test.go
This fixed the timezone bug where it is not respecting the correct timezone when running for the second time. It also adds some tests for it.
---
**Tracking Issue:** #2732
See the tracking issue for details and context from the Slack thread. This PR aims to resolve the bug where only the first scheduled run respects the timezone, but subsequent runs do not.
=> Fix: fix timezone for triggering tasks

pkg/gateway/client/user.go
If we don't dereference, then there is no point in copying.
=> fix: dereference the user pointer when copying

pkg/gateway/client/identity.go, pkg/gateway/client/session.go, pkg/gateway/server/user.go
This change also includes a migration to ensure that identities that do have their provider user ID double-encrypted are fixed.
=> fix: ensure identities aren't double-encrypted when encrypting all users

chart/templates/pvc.yaml
This PR simply adds the use of the persistence.storageClass value to set the storageClassName on the pvc if it is provided.
=> add storageClass name to pvc

ui/user/src/lib/components/messages/Message.svelte
styling set on global `pre` element from app.css sets a light font color
* added text color styling on toolDetails snippet level to prioritize over it
* Addresses #2632
=> fix: output details unreadable

ui/user/src/routes/s/[id]/+page.svelte
Normalize ChatBot UX so that agent owners have the same experience as
consumers of their ChatBot. This means that when they access a share
link, they will now interact with a shared "copy" instead of directly
with the parent project.
This commit also includes changes to ensure the ChatBot user warning is
properly closed after the user accepts.
=> enhance: normalize chatbot ux across personas

pkg/controller/handlers/workflowstep/workflowstep.go
Normalizing the step ID like this was causing problems for running individual loop steps. After the `loopdata` step would run, the subsequent steps to run for each element would enter a `Blocked` state, because the WorkflowExecution said to stop after the root step ID, and we were cutting off the `{loopdata}` part from the loopdata step when comparing it here, causing it to match the root step ID, thus causing the element steps not to run at all, thinking we had already passed the point where we wanted to stop.
=> fix: tasks: fix how step IDs are matched when running a single step

ui/user/package.json, ui/user/pnpm-lock.yaml
if you ran our linting locally (on a mac at least) it would fail with:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@eslint/js' imported from /Users/thedadams/code/obot/ui/user/eslint.config.js
Did you mean to import "@eslint/js/src/index.js"?
at Object.getPackageJSONURL (node:internal/modules/package_json_reader:267:9)
at packageResolve (node:internal/modules/esm/resolve:768:81)
at moduleResolve (node:internal/modules/esm/resolve:854:18)
at defaultResolve (node:internal/modules/esm/resolve:984:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38) …
```
=> Chore: update eslint dep so linting works locally

apiclient/types/mcpserver.go, pkg/api/handlers/mcp.go, pkg/api/router/router.go, pkg/render/render.go, pkg/storage/openapi/generated/openapi_generated.go
This change also returns a tool reference name for an MCP catalog entry if it is really from one of our tool bundles.
=> fix: allow chatting when MCP servers are not configured

chart/templates/deployment.yaml, chart/values.yaml
Currently, there is no way to specify extra env vars via secrets. The existing `extraEnv` option also does not support `valueFrom` references.
Additionally, this PR adds extraVolumes and extraVolumeMounts, which are useful e.g. to mount custom CA certificates.
=> feat: extraEnvFrom, extraVolumes, extraVolumeMounts

ui/user/src/lib/components/Sidebar.svelte
Show chatbot memories in the sidebar.
Addresses https://github.com/obot-platform/obot/issues/2810
https://github.com/user-attachments/assets/8812c7cb-b6ef-42b9-97b9-b8e067453ee7
=> enhance: show memory for chatbots

ui/user/src/lib/components/edit/ThreadModelSelector.svelte
for https://github.com/obot-platform/obot/issues/2873
The issue here is simply that we were not re-fetching data in this component when the thread ID changed. This fixes that.
=> fix: ui: display proper model for the thread

pkg/render/mcp.go, pkg/render/render.go
When rendering the MCP servers, the thread is the chat thread and not the project thread. This change will use the project's thread name instead of the thread's name to avoid launching MCP servers for every chat thread.
=> fix: use project's name for MCP scope to avoid launching too many MCPs

ui/user/src/lib/components/agents/AgentCatalog.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/routes/+page.svelte, ui/user/src/routes/+page.ts, ui/user/src/routes/catalog/+page.svelte
* fix clicking an agent template or mcp in the unauthenticated page
* reroutes to /catalog?type={type}&id={agentTemplateId or mcpCatalogId} to show the catalog and a preselected agent template or MCP Server to set up
=> fix: unauthenticated agents & mcp section links

ui/user/src/lib/components/SensitiveInput.svelte, ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte
* small QOL, adds sensistive input to allow option to reveal/hide value of an input (basically, eyeball thingy)
=> enhance: sensitive input for mcp server config

.gitignore, pkg/controller/handlers/toolreference/toolreference.go
This adds a `categories: "Official"` metadata field to all of our tool bundles. The UI can use this to make certain ones as official.
=> enhance: tools: mark tool bundles as official

pkg/controller/handlers/toolreference/toolreference.go
I just noticed this when looking at a PR I made the other day. We are supposed to return nil here if we're not updating, rather than going through and calling `req.Create`.
=> fix: add missing return when updating mcp catalog entries

ui/user/src/lib/components/tasks/Step.svelte
Addresses #2945
- use index as an each block's key.
- do not use bind in the iteration loop steps.
=> fix: loop step input blur after typing

pkg/controller/handlers/toolreference/toolreference.go
This fixes a bug that I sadly introduced in this PR: https://github.com/obot-platform/obot/pull/2906/files
I inverted the logic inadvertently.
=> fix: update catalog entries when the tool changes

ui/user/src/lib/components/mcp/McpInfoConfig.svelte
This whole bit of code is a hack but the idea is that these tools don't
need additional auth or configuration when added as an mcp-server.
Need to update to obot-search-bundle because we made this tool a bundle.
=> Fix: Don't auth the obot-search-bundle

pkg/controller/data/agent.yaml
The Google Search bundle has been removed from the tool index. Remove it from the `a1-obot` Agent definition.
=> chore: rm google-search bundle from agent definition

pkg/api/handlers/projects.go, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/SidebarConfig.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte, ui/user/src/lib/context/layout.svelte.ts, ui/user/src/lib/services/chat/mcp.ts, ui/user/src/routes/s/[id]/+page.svelte, ui/user/src/routes/s/[id]/+page.ts
This change adds a modified MCP Servers section to the sidebar for chatbot users that allows them to:
- identify MCP servers that have _not_ been configured by them (or the
author)
- manage local credentials for the chatbot's MCP servers
https://github.com/user-attachments/assets/d6a56794-b7a0-43af-b7b6-585c6dfa8aa1
=> enhance: enable chatbot users to configure creds for mcp servers

chart/values.yaml, pkg/mcp/loader.go, pkg/services/config.go
Certain environments, like our hosted environments, shouldn't allow MCP servers with localhost, 127.0.0.1, etc hosts because this would allow connecting to the wrong MCP server. This change adds such configuration.
=> enhance: add configuration to block MCP servers with localhost

ui/user/src/lib/components/mcp/McpCard.svelte
Addresses #3026 
* defaults to server icon if mcp server doesn't have `icon` or is empty string
=> fix: add placeholder icon if mcp server icon isnt set

pkg/mcp/loader.go, pkg/mcp/types.go
It is possible to add the same MCP server configuration twice, but this won't create a new MCP server instance. This change will ensure that a separate server instance is created.
This does create a new problem: conflicting tool names. However, that is easier to fix on the fly because the tools are dynamically generated.
=> chore: make the scope slightly more narrowly scoped

pkg/api/handlers/mcp.go, pkg/mcp/types.go, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte
This change expands environment variables (in the form `${ENV_VAR}`) present in the command, args, and/or URL of an MCP server's config to be expanded at MCP-server "start time".
=> Expand MCP environment variables in args/commands/urls

ui/user/src/lib/components/mcp/McpCard.svelte
* also account for markdown in description of MCPCard
=> fix: description markdown in MCPCard

ui/user/src/routes/s/[id]/+page.ts
Update the `/s/` page route so it doesn't attempt to fetch the agent
project for a given share link on page load. This avoids a 403 the
prevents the page from loading when the user doesn't have direct access to the
agent.
Addresses https://github.com/obot-platform/obot/issues/3069
=> fix: 403 using share links

pkg/api/handlers/mcp.go
Previously, when operating on the tools for an MCP server, the API would return a 500 when the server wasn't properly configured. This change will return a 400, which is more appropriate.
=> fix: return a bad request status when MCP servers aren't configured

pkg/storage/apis/obot.obot.ai/v1/thread.go
Ensure template projects are deleted when the project they were copied from no longer exist.
Addresses https://github.com/obot-platform/obot/issues/2852
=> fix: gc template projects with missing source project

pkg/controller/handlers/task/task.go
The alias is in the email address and used to identify which receiver to use to execute the workflow.
Issue: https://github.com/obot-platform/obot/issues/3107
=> fix: set an alias on the email receiver when creating

ui/user/src/lib/components/ModelProviders.svelte, ui/user/src/lib/components/SidebarConfig.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/services/chat/operations.ts
Addresses request in #3093 
* if tools call returns with 400, display option to go and configure the MCP server
* also fixes styling padding that is messing up other sidebar config views (md:px-4 lg:px-32 padding)
=> fix: tools thread dialog configure option

ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/i/[code]/+page.svelte
Addresses #3007 
Related Loom: https://www.loom.com/share/2bb3043fedd642d5b71f2c9d45965ab7
* user gets a view of having already accepted the invitation instead of an error notification
=> fix: avoid error if user has already accepted agent invitation

pkg/api/authz/threadshare.go, ui/user/src/lib/errors.ts
Allow authz to succeed when the `public_share_id` is not found. This
allows API requests to proceed and return a 404 when users are trying to
access a chatbot from an inactive share link (e.g. the chatbot was
disabled) and causes the UI to load the generic "page not found" page
instead of the "403" page. This change also adds details to the "page
not found" page explaining that the chatbot at the given path does not
exist.
Note: The two routes affected by this change are `GET` and `POST` on `/api/shares/{public_share_id}`
which both respond with a 404 when no share exists with the given `public_share_id`.
Addresses: https://github.com/obot-platform/obot/issues/2792
=> fix: allow authz when public share id not found

pkg/events/events.go
for https://github.com/obot-platform/obot/issues/2975
Without this part of the condition, this `wait.For` might end up selecting the previous (second-to-last) run in the workflow, which would then cause it to select the last one again, and get into a loop for a little while, causing some jitter to happen in the frontend. The next workflow run obviously cannot be the same one as the current run's `PreviousRunName`, so we make sure it isn't.
=> fix: prevent tasks from jittering

go.mod, go.sum, pkg/api/handlers/mcp.go, pkg/render/render.go
Previously, this change would not distinguish between allowedTools being nil and having length zero, interpretting both to mean that all tools for the MCP server to be allowed.
Now, if the allowedTools is non-nil and length zero, then this will be treated as not allowing any tools from the MCP server.
=> fix: allow MCP servers with no tools allowed

tools/dev.sh
Be more precise targeting service process groups to clean up and reduce log noise when killing process groups.
=> chore: improve dev script process group cleanup

apiclient/types/mcpserver.go, pkg/api/authz/authz.go, pkg/api/authz/mcpserver.go, pkg/api/authz/resources.go, pkg/api/handlers/mcp.go, pkg/api/router/router.go, pkg/mcp/types.go, pkg/storage/apis/obot.obot.ai/v1/mcpserver.go, pkg/storage/openapi/generated/openapi_generated.go
This PR allows the admin to configure MCPServers directly within MCPCatalogs, to be used by the same users who are authorized in that catalog.
I have some questions and comments on my own PR that I would like reviewers to take a look at.
=> feat: allow admin to create MCPServers inside MCPCatalogs

apiclient/types/user.go, pkg/gateway/client/user.go, pkg/gateway/types/users.go, pkg/storage/openapi/generated/openapi_generated.go
Fixed an issue in case github name is not set, we use github username as displayName
https://github.com/obot-platform/obot/issues/3232
=> Enhance: fallback to github username, return displayName in api

ui/user/src/lib/actions/tooltip.svelte.ts, ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/Table.svelte, ui/user/src/lib/components/admin/AccessControlRuleForm.svelte, ui/user/src/lib/components/admin/BackLink.svelte, ui/user/src/lib/components/admin/CatalogServerForm.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/admin/SearchMcpServers.svelte, ui/user/src/lib/components/mcp/HowToConnect.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte, ui/user/src/lib/components/mcp/SingleMultiMcpForm.svelte, ui/user/src/lib/context/admin/mcpServerAndEntries.svelte.ts, ui/user/src/routes/mcp-servers/+page.svelte, ui/user/src/routes/v2/admin/access-control/+page.svelte, ui/user/src/routes/v2/admin/access-control/[id]/+page.svelte, ui/user/src/routes/v2/admin/mcp-servers/+page.svelte
Addresses feedback requests from @cjellick:
* when adding an MCP server, there should be an optional for "all" mcp servers similar to how you have the everyone option for users. they payload would be, like
"resources": [{type: "selector", id: "*"}]
* Can you add the MCP server’s icon to the table of mcp servers that the admin sees? I think this will just liven it up a bit
* For entries that are coming from a git source and thus their configuration is grey out, can you add an explanation somewhere on that page stating that the entry isnt editable because it comes from an external source
* For connection examples we have, make the following changes:
Just have cursor, claude, vscode, and cline. Drop the others.
* In the json snippets, you are setting the name to “obot” like { "servers": { …
=> fix: feedback updates for new ui/ux mcp servers flow

pkg/api/handlers/mcpgateway/oauth/authorize.go
Getting a client during the OAuth process will certainly produce an error because, after we get the authorization URL, we are done with the client. If the channel is unbuffered and there is no reader, then the goroutine will leak.
=> fix: stop leaking goroutine during MCP OAuth process

go.mod, go.sum
Bump the nanobot module to pick up the fix ensuring capabilities are saved to sessions.
Fixes https://github.com/obot-platform/obot/issues/3334
=> chore: bump nanobot for mcp session init fix

apiclient/types/oauthapp.go, pkg/api/authz/resources.go, pkg/api/handlers/mcpgateway/oauth/authorize.go, pkg/api/handlers/mcpgateway/oauth/handler.go, pkg/api/handlers/mcpgateway/oauth/mcpoauthhandler.go, pkg/api/handlers/mcpgateway/oauth/statemanager.go, pkg/api/handlers/mcpgateway/tokenstore.go, pkg/gateway/client/mcpoauthtoken.go, pkg/gateway/types/tokens.go, pkg/storage/apis/obot.obot.ai/v1/oauthapp.go, pkg/storage/openapi/generated/openapi_generated.go
This URL needs to be static for authorization servers that don't support dynamic client authorization. Clients for such servers need to be created in advance, and having a dynamic callback URL is not feasible.
=> fix: make mcp oauth callback URL static

pkg/api/handlers/mcpgateway/handler.go, pkg/api/handlers/wellknown/handler.go, pkg/api/server/server.go
Apparently, the resource_metadata URL has a prescribed format. This change conforms to that prescribed format.
=> fix: return correct resource_metadata URL

pkg/api/handlers/mcpgateway/oauth/authorize.go
I found this bug while testing https://github.com/obot-platform/obot/issues/3282, though I am not sure if that issue was actually related to this.
=> fix: mcpgateway: always delete temporary client

go.mod, pkg/controller/handlers/mcpcatalog/github.go
This will hopefully help us to process catalog repos faster, compared to making tons of HTTP requests. Hopefully the rate limiting will be less severe, too.
This should help with https://github.com/obot-platform/obot/issues/3272
=> enhance: catalog source URLs: use go-git to clone

ui/user/src/lib/components/admin/AuditDetails.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/admin/McpServerK8sInfo.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/services/admin/eventstream.svelte.ts, ui/user/src/lib/services/admin/operations.ts, ui/user/src/lib/services/admin/types.ts, ui/user/src/routes/v2/admin/mcp-servers/c/[id]/instance/[ms_id]/+page.svelte, ui/user/src/routes/v2/admin/mcp-servers/c/[id]/instance/[ms_id]/+page.ts, ui/user/src/routes/v2/admin/mcp-servers/s/[id]/instance/[msi_id]/+page.svelte
* display k8s server info for catalog entry servers/server instances (server instances will show info about using a shared server)
Loom: https://www.loom.com/share/71471195af8746e581920d94c67c9c44 
Addresses #3381 
Merge after PR: https://github.com/obot-platform/obot/pull/3395/files#diff-d83b2475ac8bcad634d42b9cb4510b5cb92018d0e814e0234124e81162919bedR435 (Needs following endpoint)
=> feat: add k8s info for servers in catalog entry/server admin tabs

chart/templates/NOTES.txt, chart/templates/deployment.yaml, chart/templates/secret.yaml
also generates bootstrap token if user does not set one explicitly.
Signed-off-by: Taylor Price <tayworm@gmail.com>
=> chore: update deployment when configmap changes

.github/workflows/integration-test.yaml, Makefile, go.mod, go.sum, tests/integration/client.go, tests/integration/integration_test.go, tests/integration/project_api_test.go, tests/integration/setup.sh, tests/integration/tools/index.yaml, tests/integration/tools/mock-model-provider/main.go, tests/integration/tools/mock-model-provider/tool.gpt, tests/integration/tools/tool.gpt
This PR added basic integration test framework to obot. It launch a obot server with controller running, setting up mock model provider so that developer can write tests against api/controller code against full api.
Still actively adding more tests, this PR serves as a baseline for setting up groundwork and and test suite examples.
=> Enhance: Add integratin test and framework

ui/user/src/routes/mcp-servers/+page.svelte
This will avoid confusion when trying to chat with MCP servers with the same name.
Issue: https://github.com/obot-platform/obot/issues/3471
=> fix: include MCP ID when creating projects for chatting with MCP servers

ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/routes/v2/admin/mcp-servers/c/[id]/+page.svelte, ui/user/src/routes/v2/admin/mcp-servers/s/[id]/+page.svelte
Simplify the admin UX for editing MCP server descriptions by:
- removing the ability to edit descriptions in the Overview tab
- make the Configuration tab the only place descriptions may be edited
- adding some text directing admins to use the Configuration tab when
the description is empty
https://github.com/user-attachments/assets/e4c2e4ad-4257-4e5e-a4aa-fc950b42908c
https://github.com/user-attachments/assets/3b10173c-fca9-44f5-95f1-051e4b18f61e
Addresses https://github.com/obot-platform/obot/issues/3346
=> fix: remove support for editing mcp server descriptions from overview

ui/user/src/lib/components/mcp/McpServerInfo.svelte
Wait for requests to get tools, prompts, and resources to finish before
displaying MCP server capabilities to a user.
This ensure that even if a 424 (Failed Dependency) is returned by one of
the requests, it doesn't prevent the UI from showing the results of the
others to user in the capabilities section.
Addresses https://github.com/obot-platform/obot/issues/3492
=> fix: wait for all capabilities to load before displaying them 

pkg/api/handlers/mcpcatalogs.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go
We should prevent catalog from syncing within the same hour(unless there is a force resync event). Also, stop applying if we hit any error so we don't accidently delete all the catalogs.
https://github.com/obot-platform/obot/issues/3321
=> Fix: prevent catalog from refreshing within a hour

ui/handler.go, ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/stores/profile.svelte.ts, ui/user/src/routes/+page.ts
- Ensure bootstrap is enabled before redirecting for bootstrap login
- Redirect to `v2/admin` from `/` for admins and let that page redirect
to the correct admin dashboard for the user (bootstrap should always
go to `auth-providers`
- Serve correct build file for `/v2/admin` from UI handler in production
mode
- Set profile display name to `Bootstrap` when authenticated as the
bootstrap user
- Correct link name and image used for disabled subsection items in navbar
Addresses:
- https://github.com/obot-platform/obot/issues/3434
- https://github.com/obot-platform/obot/issues/3542
=> fix: bootstrap redirect and side bar subsections

ui/user/src/lib/components/admin/DefaultModels.svelte, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/v2/admin/model-providers/+page.svelte
Modify the `v2/admin/model-providers` UI route such that:
- The `DefaultModels` component is automatically opened after configuring a model provider IFF the provider adds models that can be used for unconfigured aliases
- Poll until the providers models are back-populated before checking if we should automatically open the default model aliases dialog (w/ a 10 second timeout)
Modify the `DefaultModels` component such that:
- The set of available providers is plumbed down as a property
- The `Set Default Models` button is disabled when no models are available
- The `Save` button is disabled until the selected models differ from the current default model aliases
- When the current default model alias for a usage isn't set, the suggested model is automatically selected from available models …
=> fix: empty default model aliases dropdowns

ui/user/src/lib/components/edit/ProjectConfiguration.svelte
Remove project scoped files from project configuration in the user UI.
Leave the components to make it easier to revive the feature should we
decide to down the road.
Depends on https://github.com/obot-platform/tools/pull/717
Addresses https://github.com/obot-platform/obot/issues/3555
=> chore: disable project files configuration

pkg/controller/handlers/mcpserver/mcpserver.go, pkg/controller/handlers/mcpserver/mcpserver_test.go
~~I thought these used to be mutually exclusive, but apparently they never were.~~
I updated the logic for this. We want to check for hostname drift if the server hasn't yet been marked with `needsURL`, because that would mean that there was a real change in the catalog that the admin has not yet applied. If `needsURL` is true, then there is no need to check for hostname drift, because we are waiting for the user to supply the new URL already.
=> fix: use correct logic for needsURL and checking for hostname drift

pkg/thread/threadmodel.go, ui/user/src/lib/components/edit/ThreadModelSelector.svelte, ui/user/src/routes/v2/admin/chat-configuration/+page.svelte
We should use model id to set on the model allow list. We don't set alias anymore for models, so it has to use id to look up model correctly.
@ivyjeong13 Sorry I told you the wrong thing.. I realize there is a bug in backend that would prevent model name from working in backend. So switched to use id now :-)
https://github.com/obot-platform/obot/issues/3592
https://github.com/obot-platform/obot/issues/3593
=> Fix: fix thread model, use model id instead

ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/mcp/McpResources.svelte, ui/user/src/lib/components/mcp/ProjectMcpResources.svelte, ui/user/src/lib/utils.ts
- Disable the `Add to Project` button in the side-nav's MCP Server resources dialog by default.     
- I added a property to the component that will allow us to quickly enable it should we   decide to resuscitate project workspaces down the road. 
- I didn't disable the dialog entirely b/c having a place to view and download an MCP server's resources at the project scope still seems reasonably helpful.
- Support adding, removing, downloading, and viewing thread scoped resources to the chat well.
https://github.com/user-attachments/assets/375d9acf-8442-45b6-ab2f-199a8e78718d
Follow up for https://github.com/obot-platform/obot/issues/3555
=> enhance: add thread scoped resources to chat well 

ui/user/src/lib/services/chat/messages.ts
When more progress comes in, this event will be replaced by the next event.
Issue: https://github.com/obot-platform/obot/issues/3630
https://www.loom.com/share/70f1bcc0ce754ab18607bccfc70cd808
=> fix: ignore events that have "waitingOnModel": true after more progress

ui/user/src/lib/components/admin/FilterForm.svelte
It is not possible to reveal the secret for an existing webhook filter, so this change removes the icon.
Issue: https://github.com/obot-platform/obot/issues/3662
=> fix: remove the reveal icon for secret when editing a filter

pkg/api/handlers/agent.go, pkg/api/handlers/assistants.go, pkg/api/handlers/invoke.go, pkg/api/handlers/projectmcp.go, pkg/api/router/router.go, pkg/controller/handlers/cleanup/projectmcp.go, pkg/invoke/invoker.go, pkg/invoke/system.go, pkg/mcp/mcp.go, pkg/mcp/types.go, pkg/render/render.go
This change will ensure that every MCP request made through chat will go through the MCP gateway. Additionally, a change is made so that admins can make these requests.
Issues: https://github.com/obot-platform/obot/issues/3668, https://github.com/obot-platform/obot/issues/3673
=> fix: ensure project MCP server requests go through the gateway

pkg/api/handlers/mcpgateway/auditlog.go, pkg/gateway/client/mcpauditlog.go
The response_status field is an integer, so we can't compare it to an empty string. This change uses proper types so we get the right data out of the database for all filter options.
=> fix: use proper types when looking for audit log filter options

pkg/api/authz/assistant.go, pkg/api/authz/authz.go, pkg/api/authz/mcpid.go, pkg/api/authz/mcpserver.go, pkg/api/authz/mcpserverinstance.go, pkg/api/authz/oauthclient.go, pkg/api/authz/project.go, pkg/api/authz/projectmcpserver.go, pkg/api/authz/run.go, pkg/api/authz/task.go, pkg/api/authz/template.go, pkg/api/authz/thread.go, pkg/api/authz/threadshare.go, pkg/api/authz/tool.go, pkg/api/authz/workflow.go, pkg/services/config.go
If an object was just created, then the cached get may fail for a short time. Use an uncached get when the cached get returns a not-found error to avoid unnecessary errors.
Issue: https://github.com/obot-platform/obot/issues/3670
=> fix: use uncached gets in authorizer to avoid creation race

pkg/api/handlers/mcpgateway/auditlog.go, pkg/gateway/client/mcpauditlog.go
Because we encrypt personally identifiable information like a user's display name, we have to list all users from the database and match the query in code.
This change also improves getting the total number of audit logs for a search. Instead of issuing a second search, the total count is processed at the same time as querying for audit logs.
There is a caveat here: when matching response_status against a search query, it only matches exactly. For example, no response_statuses will match if the query is "20"
I implemented both these fixes in the same PR to avoid conflicts.
Issues: https://github.com/obot-platform/obot/issues/3718, https://github.com/obot-platform/obot/issues/3720
=> Search user id response status

pkg/api/handlers/mcpgateway/auditlog.go, pkg/gateway/client/mcpauditlog.go, ui/user/src/lib/components/admin/audit-logs/AuditDetails.svelte, ui/user/src/lib/components/admin/usage/UsageFilters.svelte, ui/user/src/lib/components/admin/usage/UsageGraphs.svelte, ui/user/src/lib/services/admin/operations.ts, ui/user/src/lib/services/admin/types.ts, ui/user/src/routes/admin/usage/+page.svelte
- Add server-side support for filtering by multiple user IDs and MCP
server display names to `/api/mcp-stats`
- User server side filtering to filter usage stats
- Enable filtering usage by multiple users and mcp server names
Follow up for https://github.com/obot-platform/obot/issues/3579
Loom: https://www.loom.com/share/031530f2016c4bc39bcf87f8b83dcdfe?sid=d7f448f7-1e98-4e19-8f64-da4cbd6c4f42
=> enhance: server side usage filtering and multiple values filter

pkg/mcp/types.go
Forgot to do this earlier when I did it for environment variables.
=> fix: mcp servers: leave empty headers unset

pkg/api/handlers/mcp.go
There was a bug here where the headers would not get copied over from the catalog entry when an admin user instantiates it into a server, because we were overriding the entire `remoteConfig` with just the URL (without any headers), as that is what the UI passes in for this request.
=> fix: mcp servers: don't overwrite headers for admin

ui/user/src/lib/components/Calendar.svelte
Addresses #3723 
- !start || start is the same as date || end is the same as date => collapse range
- if the date is before start => expand backward
- Else expand forward
=> fix: support date range expand and collapse

ui/user/src/lib/components/admin/audit-logs/AuditDetails.svelte, ui/user/src/lib/components/admin/audit-logs/AuditFilters.svelte, ui/user/src/lib/services/admin/operations.ts, ui/user/src/routes/admin/audit-logs/+page.svelte, ui/user/src/routes/admin/audit-logs/AuditLogs.svelte
Addresses #3711 
- Add the ability to disable logging errors when fetching by user ID.
- trim user ID
- Cache the fetch user promise for 1 minute
=> fix: hide user not found errors and make it possible to filter by user after user is deleted

ui/user/src/lib/components/admin/usage/UsageFilters.svelte
Addresses https://github.com/obot-platform/obot/issues/3755
=> fix: use display names for usage user filters

pkg/api/handlers/mcp.go, pkg/api/handlers/mcpgateway/oauth/authorize.go, pkg/api/handlers/mcpgateway/oauth/mcpoauthhandler.go, pkg/api/handlers/projectmcp.go
A previous implementation closed the client we used to check for OAuth because we didn't want this extra client lying around. It would cause problems down the road.
A recent change separated clients by session. The upshot is that we no longer need to close this OAuth client, and it can remain active to make future checks quicker.
There was a bug here as well: the ShutdownServer call was shutting down all clients for a given server instead of just the OAuth client.
=> fix: stop closing OAuth clients

ui/user/src/lib/components/admin/usage/UsageGraphs.svelte
Addresses https://github.com/obot-platform/obot/issues/3764
=> fix: hide filters on usage tab for multiuser servers

go.mod, go.sum
This pulls in the change to reduce the default max tokens to 400k for gpt-5.
=> chore: bump gptscript

pkg/controller/handlers/mcpcatalog/github.go
We want to skip repo from size checking if it is from obot-platform(which we trust). This can save us some api call to github to avoid rate limit issue.
=> Fix: skip repo size check if it is obot-platform

ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/admin/ConfigureBanner.svelte, ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/stores/adminConfig.svelte.ts, ui/user/src/routes/admin/auth-providers/+page.svelte, ui/user/src/routes/admin/mcp-servers/+page.svelte, ui/user/src/routes/admin/model-providers/+page.svelte
* adds ConfigureBanner like legacy admin
Also addresses #3852 
* created adminConfigStore to reduce calls to auth-providers/model-providers between route navigation
=> enhance: add configure info banner for auth/model providers

ui/user/src/lib/services/chat/messages.ts
Fix https://github.com/obot-platform/obot/issues/3875
When files are first created it doesn't get assigned with thread id, this caused thread id to be missing when trying to download it and it will get an error.
=> Fix: fix file not being able to download when created

ui/user/src/lib/components/admin/audit-logs/AuditLogsPageContent.svelte
Addresses #3845, #3846
- Start/End time info will be shown in the calendar component and should not be included in the pills filters section.
=> fix: exclude start/end time from pills filters

ui/user/src/lib/components/mcp/MyMcpServers.svelte
When the UI sends the request to create an MCP server, the remote config section will be non-nil. This leads to MCP servers with `https://` as their URL when no such URL should be set.
This change fixes that by checking the runtime.
=> fix: stop sending URL if URL is not set

ui/user/src/lib/components/admin/usage/UsageFilters.svelte, ui/user/src/lib/components/admin/usage/UsageGraphs.svelte, ui/user/src/routes/admin/usage/+page.svelte
- lexicographically sort usage filter options
- ensure filter button and pills are present when there are no
usage stats available
- partially source server name filter options from catalog/servers
to ensure options are available when no stats are available
Addresses:
- https://github.com/obot-platform/obot/issues/3807
- https://github.com/obot-platform/obot/issues/3750
=> fix: usage filters

pkg/gateway/client/mcpauditlog.go
Corrects the query to use opts.CallIdentifier instead of opts.CallType for filtering call_identifier, ensuring the intended filter is applied.
=> fix: use correct call_identifier filter in audit log query

ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/admin/audit-logs/AuditFilter.svelte, ui/user/src/lib/components/admin/audit-logs/AuditFilters.svelte, ui/user/src/lib/components/admin/audit-logs/AuditLogsPageContent.svelte
Addresses #3898 
- Show server ID and server catalog entry name fields in the MCP server audit logs page.
- In case the user selects a single server, the server ID is disabled.
- In case the user selects a single server, the catalog entry name is disabled.
- In case the user selects a multi-user server, the server ID shows only the available instances of the selected server.
- The server name filter will be disabled in the MCP server audit logs tab.
Changes to Audit filter:
- Add disabled property
- When no option is available, make the filter disabled.
=> fix: show filter by server id/ catalog entry name in mcp audit logs

ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/admin/+page.ts, ui/user/src/routes/admin/auth-providers/+page.ts
When authentication is enabled on a fresh install, a "too many redirects" error is presented to the user after they enter the bootstrap token. Checking whether the current user is admin seems to stop this.
I found that this redirect and [this one](https://github.com/obot-platform/obot/blob/main/ui/user/src/routes/admin/+page.ts#L20) contend with each other and redirect until the error occurs.
=> fix: stop redirect loop on fresh installs with auth enabled

apiclient/types/accesscontrolrule.go, pkg/accesscontrolrule/helper.go, pkg/api/authz/mcpserver.go, pkg/api/handlers/mcp.go, pkg/api/handlers/projectmcp.go, pkg/api/handlers/serverinstances.go, pkg/auth/auth.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go, pkg/gateway/client/auth.go, pkg/gateway/client/group.go, pkg/gateway/client/identity.go, pkg/gateway/client/user.go, pkg/gateway/db/db.go, pkg/gateway/server/router.go, pkg/gateway/server/tokenreview.go, pkg/gateway/server/user.go, pkg/gateway/types/group.go, pkg/gateway/types/identity.go, pkg/proxy/proxy.go, ui/user/src/lib/components/admin/AccessControlRuleForm.svelte, ui/user/src/lib/components/admin/SearchUsers.svelte, ui/user/src/lib/services/admin/operations.ts, ui/user/src/lib/services/admin/types.ts
Add the ability for admins to use auth provider sourced groups to gate user access to MCP servers.
Addresses part of https://github.com/obot-platform/obot/issues/3484
=> feat: add support for provider auth groups

ui/user/src/lib/components/chat/McpServerOauths.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/McpOauth.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/mcp/McpServerInfoAndTools.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/routes/mcp-servers/+page.svelte
Addresses #3885
* moves the authenticate banner to also show in overview when mcp server in chat needs authentication
* provides another way to authenticate if user closes out the authentication dialog
* fixes warning not showing in sidebar when mcp server requires oauth
Addresses #3925
Addresses #3926 
Addresses #3929
=> fix: server name and chat auth fixes

ui/user/src/routes/admin/chat-threads/+page.svelte
Addresses #3995 
- rename projectNames to projects for clarity in filter options
=> fix: return project id instead of project name

ui/user/src/lib/components/chat/ChatSidebar.svelte
* per Shannon request, making editing project more obvious with an edit option on bottom left of chat sidebar
=> fix: add edit project button bottom left of chat sidebar

pkg/gateway/client/group.go
Fix the condition that detects when user group name and icon info has changed from what's cached. This will ensure informational changes to cached groups are kept up to date.
Part of https://github.com/obot-platform/obot/issues/4012
=> fix: condition for group info update

ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/mcp/McpServerInfoAndTools.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte
Addresses #3953
- mcp card name is derived from the server alias or parent manifest's name.
=> fix: inherit enabled connector name, description, categories from parent

go.mod, go.sum, pkg/api/handlers/mcpgateway/clientmessagehandler.go, pkg/mcp/docker.go, pkg/mcp/kubernetes.go
The nanobot runtime is now an image with a script that will dynamically create the necessary configuration files for nanobot.
Requires: https://github.com/obot-platform/mcp-images/pull/10
Issue: https://github.com/obot-platform/obot/issues/4243
=> feat: add nanobot runtime

ui/user/src/lib/components/admin/audit-logs/AuditLogsTimeline.svelte
Addresses #4247 
- Properly display the last data segment in some intervals
=> fix: adjust end boundary calculation for time frame steps

ui/user/src/lib/components/admin/ProviderConfigure.svelte, ui/user/src/lib/components/ui/multi-value-input/Input.svelte
Addresses #4042, #4246
Related PRs: [#65](https://github.com/obot-platform/enterprise-tools/pull/65), [#751](https://github.com/obot-platform/tools/pull/751)
- Remove the `+` button.
- Change all the helper texts in (tools/enterprise-tools) that say `comma separated`
- Support custom labels for values; instead of displaying the entered value, the input will display the provided label if it exists; otherwise, the entered value will be displayed.
=> chore: multi-value input adjustments

pkg/api/authz/authz.go, pkg/api/router/router.go, ui/user/src/lib/context/poweruserWorkspace.svelte.ts
This PR reverts the changes to allow power user and plus to have more route access, as it should be granted based on workspace and permission in another handler. Also change the UI to use a differente endpoint to list servers for the current users.
=> Fix: fix permission related issue for power users

ui/user/src/app.css, ui/user/src/lib/components/messages/Input.svelte
Addresses #4320 
- Make sure absolute elements are not clipped.
- Improve scrollbar style for a better look.
=> fix: do not clip absolute element and enhance scrollbar visibility

pkg/api/handlers/mcp.go, pkg/api/handlers/mcpcatalogs.go, pkg/api/handlers/tasks.go, pkg/api/handlers/template.go
Filter out resources in the API such that:
- template MCP servers are hidefrom the server details page
- Hide template tasks from the tasks view
Addresses https://github.com/obot-platform/obot/issues/4287
=> Hide template resources from admin views

ui/user/src/lib/components/messages/PlaintextEditor.svelte
The fourth parameter of this textBetween function call is causing us to
replaced newlines with the unicode null character. Here's the docs for
that function:
> Get all text between positions from and to. When blockSeparator is given,
> it will be inserted to separate text from different block nodes.
> If leafText is given, it'll be inserted for every non-text leaf node
> encountered, otherwise leafText will be used.
LeafText is the 4th param. The last sentence of that is confusing, but
regardless I don't think we need to set this 4th parameter.
=> Fix: Dont replace newlines with null character

ui/user/src/lib/components/chat/McpServerRequirements.svelte, ui/user/src/lib/components/edit/ProjectConfiguration.svelte
- Add keys for config prompt elements
- Hard refresh page on project upgrade to ensure new config/auth dialogs are
triggered
Addresses https://github.com/obot-platform/obot/issues/4372
Loom: https://www.loom.com/share/1c2ceed88d6643f0a39032232950930d?sid=6fa39560-5b32-4813-b352-65c1e62fc3a8
=> fix: multiple config prompt sequence

pkg/accesscontrolrule/helper.go, pkg/api/authz/mcpid.go, pkg/api/handlers/mcp.go, pkg/api/handlers/mcpcatalogs.go, pkg/api/handlers/poweruserworkspace.go, pkg/api/handlers/projectmcp.go, pkg/api/handlers/serverinstances.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go, pkg/services/config.go
This PR fixes a couple of issue regarding to admin and ACR
- Admin by default still see all entries and servers from all users, be able to view logs/server details
- Admin should not see mcp server from connector page from PU/PUP users unless a ACR is granted to admin
- PU/PUP user should see their mcp servers and use them without having a ACR if they are the owner.
https://github.com/obot-platform/obot/issues/4382
https://github.com/obot-platform/obot/issues/4341
=> Fix: fix admin ACR to view entries and servers

pkg/bootstrap/bootstrap.go, pkg/gateway/types/users.go
This ensures that the MCP Publisher page doesn't show for the bootstrap user.
Issue: https://github.com/obot-platform/obot/issues/4430
=> fix: stop giving bootstrap user power user grups

ui/user/src/lib/components/SensitiveInput.svelte, ui/user/src/lib/components/mcp/CatalogConfigureForm.svelte
Addresses #4220
- The user has to click on the eye icon to show/edit sensitive info.
- If a user tries to edit hidden sensitive info, the eye icon will start pulsing to grab the user's attention.
=> fix: do not show sensitive info automatically

ui/user/src/lib/components/admin/McpServerEntryForm.svelte
It looks like ivy already added this functionality and it will only show the regenerate tool button when server is updated but tools preview are not generated(which is better). So I am going to revert this change.
https://github.com/obot-platform/obot/issues/4120
=> Fix: revert regenerate tool preview

Dockerfile, pkg/controller/handlers/mcpcatalog/mcpcatalog.go, pkg/controller/handlers/poweruserworkspace/poweruserworkspace.go
When downgrading from power user plus to power user, we should delete every ACR rules from PUP so that power user won't be able to share their entries with existing ACR rules in place. This include default generated rules to share everything from power user plus.
https://github.com/obot-platform/obot/issues/4456
=> Fix: delete all ACR when depromoted to power user

pkg/api/handlers/mcp.go
Docker appends a header to the log output so that it knows where to send the log (stdout/stderr) and how long the log is. Including this information in our output produces weirdness in the UI. So we remove it here.
https://github.com/obot-platform/obot/issues/4517
=> fix: strip Docker log header from output

pkg/controller/handlers/poweruserworkspace/poweruserworkspace.go
for https://github.com/obot-platform/obot/issues/4409
There is separate logic that already gives PUs access to things in their own PUW, so we don't need to create this default ACR for them anymore.
=> fix: do not create needless ACR for power users

pkg/accesscontrolrule/helper.go, pkg/api/authz/mcpid.go, pkg/api/authz/mcpserver.go, pkg/api/handlers/accesscontrolrules.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go, pkg/controller/handlers/poweruserworkspace/poweruserworkspace.go, pkg/controller/routes.go, pkg/storage/apis/obot.obot.ai/v1/run.go
The clean up of unauthorized MCP servers and instances was a universal handler. This could cause slowdown as we list the world every time an MCP server or instance is changed.
This change separates cleanup for catalogs and workspaces in an effort to be more efficient.
=> chore: separate catalog and workspace cleanup

pkg/gateway/client/identity.go
This bug was causing an issue where new users in Entra and Okta (who weren't given an explicit Owner role using the environment variables) were getting created with RoleUnknown instead of the proper default role.
for https://github.com/obot-platform/obot/issues/4469
=> fix: set created=true when creating a new identity
