ui/admin/app/components/knowledge/KnowledgeSourceDetail.tsx
- Drop `loading file` section
- Fix the knowledge details page in dark mode
=> Fix: remove loading file section, fix dark mode

ui/admin/app/components/knowledge/AddSourceModal.tsx
https://github.com/otto8-ai/otto8/issues/320
=> Fix: properly trim websites with space

ui/admin/app/components/workflow/DeleteWorkflow.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/components/workflow/WorkflowView.tsx, ui/admin/app/routes/_auth.workflows._index.tsx
- Complete full crud for workflows
- Include YAML dump for workflows
- Add knowledge card to workflows
=> feat: complete workflow CRUD

pkg/controller/handlers/knowledgefile/knowledgefile.go, pkg/controller/routes.go, pkg/services/config.go, ui/admin/app/components/knowledge/AddSourceModal.tsx, ui/admin/app/components/knowledge/AgentKnowledgePanel.tsx, ui/admin/app/components/knowledge/KnowledgeSourceDetail.tsx
- Add ingestion limit for knowledge set(1000)
- Only keep links in onedrive/website add modal
- Add scrape limit for website(and UI)
https://github.com/otto8-ai/tools/pull/202
=> Chore: Add ingestion limit per knowledge set, tweak knowledge UI

ui/admin/app/components/ui/button.tsx, ui/admin/app/lib/model/threads.ts, ui/admin/app/lib/model/users.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/lib/utils.ts, ui/admin/app/routes/_auth.threads.tsx, ui/admin/app/routes/_auth.users.tsx
- users page now links to threads page with userId query param
- threads page now supports filtering by userId
- add filter chips to threads page
=> UI feat: implement support for multiple threads per user

ui/admin/app/routes/_auth.workflows._index.tsx
=> UI fix: Workflows - workflow thread count always displaying as 1 (incorrectly)

ui/admin/app/components/agent/AgentForm.tsx, ui/admin/app/components/model/ModelForm.tsx, ui/admin/app/lib/model/models.ts
=> UI feat: add usage field to model form

docs/docs/02-concepts/06-workflows.md, docs/docs/02-concepts/07-models.md
=> Docs: Workflows and models

docs/docs/03-guides/02-integrating-oauth.md
=> Docs: OAuth Guide

ui/admin/app/routes/_auth.threads.tsx
=> fix: admin ui - fix error when navigating to threads page

ui/admin/app/components/agent/DeleteAgent.tsx, ui/admin/app/routes/_auth.agents._index.tsx
=> feat: admin ui - confirm when deleting agents

pkg/controller/handlers/oauthapp/oauthapplogin.go, pkg/storage/apis/otto.otto8.ai/v1/oauthapp.go
Issue: https://github.com/otto8-ai/otto8/issues/590
=> fix: allow retries of oauth logins

pkg/controller/handlers/knowledgesource/knowledgesource.go, pkg/controller/handlers/knowledgesource/metadata.go
Issue: https://github.com/otto8-ai/otto8/issues/592
=> fix: check for NotFoundInWorkspaceError to avoid transient errors

ui/admin/app/components/agent/AgentPublishStatus.tsx, ui/admin/app/components/composed/CopyText.tsx, ui/admin/app/lib/routers/baseRouter.ts
=> feat: admin ui - agent refname - open agent in new tab on

ui/admin/app/lib/service/api/threadsService.ts
=> feat: update max runs to 50 in admin ui

ui/admin/app/components/agent/AgentPublishStatus.tsx
=> fix: incorrect agent status display in admin ui

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentContext.tsx
=> chore: indicate when saving agent fails in admin ui

pkg/controller/handlers/knowledgefile/knowledgefile.go
depends on https://github.com/otto8-ai/tools/pull/223
=> change: do not stat file for fileSize during ingestion flow as that happens in knowledge already

ui/admin/app/components/agent/shared/AgentSelect.tsx, ui/admin/app/components/composed/SelectModule.tsx, ui/admin/app/components/ui/button.tsx, ui/admin/app/components/workflow/WorkflowSelectModule.tsx, ui/admin/app/components/workflow/steps/Step.tsx
=> feat: add agent and workflow dropdowns to workflow steps

ui/admin/app/components/chat/Message.tsx, ui/admin/app/lib/model/chatEvents.ts, ui/admin/app/lib/model/messages.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/PromptApi.tsx
This PR adds the ability to handle credential-based authentication from within the chat interface
=> feat: add credential based authentication to chat

ui/admin/app/components/workflow/ParamsForm.tsx, ui/admin/app/components/workflow/steps/AddStep.tsx, ui/admin/app/components/workflow/steps/StepsForm.tsx
Moved a couple of buttons around and changed their variants to match the rest of the form
=> fix: theme updates for workflows

ui/admin/app/tailwind.css
=> chore: add some guidance to the purpose of the colors in the tailwind.css file

ui/admin/app/components/knowledge/FileTree.tsx
https://github.com/otto8-ai/otto8/issues/688
=> Fix: use bracket wisely

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentPublishStatus.tsx
* minor update to add a spinner if displaying the URL is waiting on the update to complete
https://github.com/user-attachments/assets/d6866c43-45e1-4335-9559-6d88fe8a1e88
=> fix: Minor UX improvement, spinner if publish URL is still in progress.

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/lib/model/chatEvents.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/workflowService.ts, ui/admin/app/routes/_auth.workflows.$workflow.tsx
- makes prompt message more generic (only displays auth related metadata, when provided)
- provides authenticate button to workflow form
- allows users to handle authentication in workflow chat
=> feat: allow users to trigger workflow authentication in the chat interface

ui/admin/app/components/chat/Chat.tsx, ui/admin/app/components/chat/RunWorkflow.tsx
=> enhance: adjust the offset of the workfow parameter dialog to overlay the invoke button

ui/admin/app/lib/service/routeService.ts
Replaces extremely ugly (and mostly useless) switch statement with a slightly less ugly TypeScript Type.
Accomplishes the same result minus the runtime impact.
=> chore: improve performance and typing for route helpers in admin ui

ui/admin/app/components/model/DefaultModelAliasForm.tsx, ui/admin/app/components/ui/dialog.tsx, ui/admin/app/components/ui/select.tsx, ui/admin/app/lib/model/models.ts
- Add labels for various model aliases and usages
- fix issue where content spills over dialog content
- Sort default model aliases (backend sends them in an arbitrary order)
=> fix: update labels for model aliases and usages

ui/admin/app/components/header/HeaderNav.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/_auth.threads.$id.tsx, ui/admin/app/routes/_auth.threads._index.tsx
- fixed by renaming `routes/_auth.thread.$id.tsx` to `routes/_auth.threads.$id.tsx`
- updated links to match change
=> fix: highlight threads sidebar item on thread view page

pkg/invoke/invoker.go
Decrease OAuth prompt timeout to 90 seconds (from 5 minutes) and improve timeout message.
Addresses https://github.com/otto8-ai/otto8/issues/570
=> fix: decrease oauth prompt timeout

ui/admin/app/components/composed/DataTable.tsx, ui/admin/app/components/composed/HelperTooltip.tsx, ui/admin/app/components/model-providers/ModelProviderForm.tsx, ui/admin/app/components/ui/table.tsx, ui/admin/app/components/ui/tooltip.tsx
* create TooltipContent variant
* move tooltips in ModelProviderForms to composed HelperTooltip
* fix sticky table header (needed to remove some wrapping divs, checked the others that used DataTable but lemme know if anything looks off)
=> enhance: helper tooltip and minor table ui fix

pkg/controller/handlers/knowledgefile/knowledgefile.go
Increase ingestion timeout to 1 hour.
=> Chore: Increase ingestion timeout to 1 hour

ui/admin/app/components/knowledge/OAuthSignDialog.tsx
=> Fix: Change minor wording issue

ui/admin/app/components/model-providers/ModelProviderLists.tsx
* quick change to first option of recommended pill
=> chore: remove typography & change to recommended

ui/admin/app/components/agent/Agent.tsx
* polling check for aliasAssigned published model
=> fix: add polling check for agent aliasAssigned for publishing

ui/admin/app/components/knowledge/FileTree.tsx
Ref https://github.com/otto8-ai/otto8/issues/718
=> feat: show unsupported files on folder in knowledge ingestion view

ui/admin/app/components/chat/ChatContext.tsx
=> fix: prevent loading state after replay complete when loading threads

.goreleaser.yaml, Makefile
- **chore: add git tag to ldflags on build**
- **chore: use correct package path for version ldflag**
=> chore: correct otto8 release version info

pkg/api/authz/thread.go, pkg/gateway/client/auth.go, pkg/gateway/client/user.go, pkg/invoke/invoker.go, pkg/jwt/jwt.go, pkg/services/config.go
Additionally, this change adds this information to the JWT token for each run.
Issue: https://github.com/acorn-io/acorn/issues/903
=> feat: add user info to run environment variables

ui/admin/public/assets/jira_icon.svg
Add tool icon for `Jira` to admin UI assets.
=> chore: add jira tool icon

ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/lib/model/workflows.ts
* remove credentials section from workflows UI
=> chore: remove workflow credentials section

ui/admin/app/components/model-providers/ModelProviderLists.tsx
* move recommended to top left
=> chore: move recommended chip in model provider

pkg/api/handlers/env.go, pkg/api/handlers/workflows.go, pkg/api/router/router.go, pkg/gateway/server/router.go
These endpoints are added for workflows and agents. Setting the environment variables for a workflow or agent will ensure that the object's manifest has the same information.
=> enhance: create API endpoints for setting environment variables

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/components/chat/Chatbar.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/lib/model/messages.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/threadsService.ts
Addresses #358 
* adds stop button to stop running thread process
https://github.com/user-attachments/assets/7868c04b-5bf7-4bf5-abd8-024a8eb98b3d
=> enhance: allow interruption of running thread

ui/admin/app/components/agent/shared/EnvironmentVariableSection.tsx
=> fix: conditionally render EnvironmentVariableSection to avoid empty state

ui/admin/app/routes/_auth.workflows._index.tsx
* clicking edit button goes to workflow fix
=> fix: click edit button opens workflow

ui/admin/app/components/chat/Chatbar.tsx, ui/admin/app/components/model-providers/ModelProviderLists.tsx, ui/admin/app/lib/model/oauthApps/providers/github.ts, ui/admin/app/lib/model/oauthApps/providers/google.ts, ui/admin/app/lib/model/oauthApps/providers/notion.ts, ui/admin/app/lib/model/oauthApps/providers/slack.ts, ui/admin/app/routes/_auth.model-providers.tsx
* small nit little things to fix:
Before:
https://github.com/user-attachments/assets/bc22c87b-09de-41a6-a270-89a6d9ef3e36
After:
https://github.com/user-attachments/assets/618aa1d7-d28f-4c6c-af0d-cc286ffd5828
Before:
After:
* fix hitting enter goes through for chatbar when it should be disabled
* few more Ottos to change to Obot
=> fix: minor ui/ux bugs

ui/admin/package.json, ui/admin/pnpm-lock.yaml
=> chore: remove remix-routes typescript plugin

ui/admin/app/components/model-providers/ModelProviderConfigure.tsx, ui/admin/app/components/model-providers/ModelProviderDeconfigure.tsx, ui/admin/app/components/model-providers/ModelProviderDropdown.tsx, ui/admin/app/components/model-providers/ModelProviderForm.tsx, ui/admin/app/components/model-providers/ModelProviderLists.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/modelProviderApiService.ts
* added option UI to deconfigure for a Model Provider
https://www.loom.com/share/1bc06d6f7214486b9fe406cbed2c0426?sid=12b787ec-8602-43d6-9fad-7803c1360d25
=> feat: deconfigure model provider option

ui/admin/app/components/tools/ToolCatalog.tsx
- sort first by bundlable tool groups
- sort by alphabetical tool category name
=> enhance: organize tool catalog

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/PastThreads.tsx, ui/admin/app/routes/_auth.agents.$agent.tsx
https://www.loom.com/share/0480ca9b0521475aa6342a807c96fe0a
* quick fix, adds a check button to show the currently selected thread if there is one
=> fix: show selected thread in agents threads dropdown

ui/admin/app/components/agent/AgentDropdownActions.tsx, ui/admin/app/components/agent/AgentPublishStatus.tsx, ui/admin/app/components/ui/dropdown-menu.tsx, ui/admin/app/hooks/component-helpers/useConfirmationDropdown.tsx
addresses #446 
https://www.loom.com/share/98e9f022d4b340b881c4e63170af6a60?sid=31090a2e-0413-412f-ad60-0d9de115c741
=> feat: add ability to delete agents from agent edit page

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/MessageDebug.tsx
addresses #1022
https://www.loom.com/share/0da12332dee84083bbe4d6a2497e6a8f?sid=c6c42ccd-11a3-457e-8256-689a976a7704
=> feat: add run debug info to user messages in admin ui

ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.model-providers.tsx, ui/admin/app/routes/_auth.oauth-apps.tsx, ui/admin/app/routes/_auth.threads.$id.tsx, ui/admin/app/routes/_auth.threads._index.tsx, ui/admin/app/routes/_auth.tools._index.tsx, ui/admin/app/routes/_auth.users.tsx, ui/admin/app/routes/_auth.webhooks.$webhook.tsx, ui/admin/app/routes/_auth.webhooks._index.tsx, ui/admin/app/routes/_auth.workflows.$workflow.tsx, ui/admin/app/routes/_auth.workflows._index.tsx
https://github.com/user-attachments/assets/b9ac3a82-4487-4f30-b7dc-4bd7b43a60e4
Throwing this suggestion out there! Not sure if there was a reason to keep it at localhost:8080/admin/{route}
=> suggestion: enhance: add meta title for routes/pages

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/components/chat/Message.tsx
addresses #1023 
https://www.loom.com/share/5d542cec4815494b866e095aca462088?sid=6f42e1f1-ac7a-4b16-b885-f43c23010de4
=> feat: add message that indicates a thread was aborted

ui/admin/app/components/ui/dnd/index.tsx, ui/admin/app/components/ui/dnd/sortable.tsx, ui/admin/app/components/workflow/steps/IfContent.tsx, ui/admin/app/components/workflow/steps/StepBase.tsx, ui/admin/app/components/workflow/steps/StepRenderer.tsx, ui/admin/app/components/workflow/steps/StepsForm.tsx, ui/admin/app/components/workflow/steps/WhileContent.tsx, ui/admin/app/components/workflow/steps/step-renderer-helpers.ts, ui/admin/package.json, ui/admin/pnpm-lock.yaml
addresses #1033
- imports the `@dndkit/core` library
https://www.loom.com/share/94a5e9133a7340749adf2dfe684f40b4?sid=23fa7b3d-ca11-4a83-8025-8f6fd091cd9f
=> feat: add drag n drop to workflow steps

ui/admin/app/components/webhooks/WebhookConfirmation.tsx, ui/admin/app/components/webhooks/WebhookForm.tsx, ui/admin/app/components/webhooks/WebhookFormContext.tsx, ui/admin/app/components/workflow/DeleteWorkflowWebhook.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/components/workflow/WorkflowSchedulePanel.tsx, ui/admin/app/components/workflow/WorkflowWebhookDialog.tsx, ui/admin/app/components/workflow/WorkflowWebhookPanel.tsx, ui/admin/app/hooks/cronjob/useCronjob.tsx, ui/admin/app/lib/model/cronjobs.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/cronjobApiService.ts, ui/admin/app/routes/_auth.workflows.$workflow.tsx
Addresses #873
* adds scheduling and webhooks into updating/creating workflows
* reuses webhook form
https://www.loom.com/share/d5cba91f5a334a6392bb2d0c1bb5ac01
=> enhance: add schedule & webhook options into workflows

ui/admin/app/components/chat/thread-helpers.ts, ui/admin/app/components/oauth-apps/custom/CustomOAuthAppForm.tsx, ui/admin/app/components/webhooks/WebhookFormContext.tsx, ui/admin/app/hooks/knowledge/useKnowledgeSourceFiles.ts, ui/admin/app/hooks/useAsync.tsx, ui/admin/app/hooks/useMultiAsync.ts, ui/admin/app/lib/service/async.ts
- convert from object signature to tuple signature
- added config object to provide extra options as necessary
- updated usages of `handlePromise` accordingly
=> chore: update signature for handleAsync

ui/admin/app/components/agent/shared/ToolAuthenticationStatus.tsx, ui/admin/app/components/workflow/steps/StepBase.tsx
=> enhance: improve colors for workflow steps UX

ui/admin/app/components/composed/NameDescriptionForm.tsx, ui/admin/app/components/workflow/ParamsForm.tsx
addresses #1117
- remove default value for workflow params form
- update style for name/description form
=> enhance: workflow params form default to empty

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/hooks/cronjob/useCronjob.tsx
* filter out bundle with metadata.oauth set if the oauth provider isn't configured
* also fix for workflow schedule sorting has item move or first item can't be changed
=> fix: filter out tools with unconfigured oauth provider

ui/admin/app/components/workflow-triggers/DeleteWorkflowTrigger.tsx, ui/admin/app/components/workflow-triggers/WorkflowTriggerActions.tsx
=> fix: broken button in workflow trigger actions dropdown

ui/admin/app/components/workflow/steps/StepBase.tsx
* bring up confirmation dialog for update/delete step if any changes have been made
=> fix: show confirm dialog only if there are changes for workflow step

ui/admin/app/components/errors/Error.tsx
=> fix: capitalize error boundary text

ui/admin/app/components/agent/UserAuthorizationSelect.tsx, ui/admin/app/components/composed/ComboBox.tsx
* minor icon changes depending on user, just email, or everyone
* multi-select in dropdown so user doesn't have to keep opening for every change
* validateCreate on comboBox so add option isn't enabled if validation returns `false`
https://www.loom.com/share/511c18ce70554053b6631eac116605b6
=> enhance: authorizing users in agent ux updates

go.mod, go.sum, pkg/api/handlers/cronjob.go, pkg/controller/handlers/cronjob/cronjob.go, pkg/controller/handlers/knowledgesource/reschedule.go, ui/admin/app/components/workflow-triggers/shared/ScheduleSelection.tsx, ui/admin/app/lib/model/oauthApps/providers/zoom.ts
Update the cron parsing package we use so that we could support "last day of the month" syntax.
Also, fix a small display issue with the last day of the month in the admin UI.
=> enhance: support L to mean last day of the month in cron

ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/hooks/workflow-triggers/useWorkflowTriggers.ts
=> fix: update workflow form to filter out webhooks for other workflows

pkg/api/router/router.go, ui/admin/app/components/composed/typography.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/threadsService.ts, ui/admin/app/lib/utils/downloadFile.ts
=> feat: allow admins to download files in thread workspaces

ui/admin/app/components/agent/AgentAccessControl.tsx, ui/admin/app/components/agent/AgentAlias.tsx, ui/admin/public/assets/user_lock.svg
* couldn't find appropriate lucide-icon with a person and lock so frankensteined two together
* changed dropdown with delete to just trashcan and delete
=> enhance: agent delete & access control icons

ui/admin/app/components/agent/shared/ToolAuthenticationDialog.tsx, ui/admin/app/components/agent/shared/ToolAuthenticationStatus.tsx, ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/composed/ConfirmationDialog.tsx, ui/admin/app/hooks/messages/useMessageSource.ts, ui/admin/app/hooks/messages/useThreadEvents.ts
- update icons
- remove intermediary dropdown menu
- replace chat interface with custom auth messages
https://www.loom.com/share/99b782b1c30249da86cc65ad304a3c27?sid=4ba6d5ef-4bc9-4ad7-b02a-4117597e3837
=> Enhance: improve tool authentication UX

ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/shared/ToolAuthenticationStatus.tsx, ui/admin/app/components/tools/ToolCatalog.tsx
=> feat: collapse agent/user tools into single section

ui/admin/app/components/chat/ChatRunInfo.tsx, ui/admin/app/components/chat/Chatbar.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/MessageDebug.tsx, ui/admin/app/components/chat/MessagePane.tsx, ui/admin/app/components/ui/scroll-area.tsx, ui/admin/app/components/ui/scroll-to-bottom.tsx, ui/admin/app/hooks/messages/useAnimatedText.ts, ui/admin/app/hooks/useOnResize.ts, ui/admin/app/routes/_auth.threads.$id.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
addresses #1277
- additionally typing dots elements and current run debug info action to the chat bar (to prevent them from bouncing during scroll)
https://www.loom.com/share/a3d17e6bd15d46abaf353170fbcc65d2?sid=b4b19128-b327-46da-be26-3e9ea4c6aa51
=> enhance: chat generation/scroll animations

pkg/api/handlers/agent.go, pkg/api/handlers/workflows.go
Issue: https://github.com/obot-platform/obot/issues/1280
=> fix: stop creating credentials at the "namespace" scope for workflows

ui/admin/app/components/chat/Message.tsx
https://www.loom.com/share/f5a656883bed4afeaf08659570552f8f?sid=a19fd9b6-46ad-46f0-8678-16a35a09b407
=> fix: Prevent replay messages from animating in on thread page

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentCapabilityForm.tsx, ui/admin/app/components/agent/ToolEntry.tsx, ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/shared/AgentCapabilityForm.tsx, ui/admin/app/components/agent/shared/constants.ts, ui/admin/app/components/composed/typography.tsx, ui/admin/app/components/tools/BasicToolForm.tsx, ui/admin/app/components/tools/toolGrid/ToolCard.tsx, ui/admin/app/components/ui/tooltip.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/hooks/tools/useCapabilityTools.ts, ui/admin/app/lib/model/toolReferences.ts, ui/admin/app/tailwind.css
addresses #1185, #1284 
- Adds Capability Section to Agent/Workflow forms
- removes capabilities from tool catalogs and sections
- Ensures sorted order of capabilities in Capability sections
- Improves performance of Agent/Workflow forms by debouncing/batching all updates
=> feat: Add Capabilities to Agents and Workflows

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentIntroForm.tsx, ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/components/chat/NoMessages.tsx, ui/admin/app/lib/model/agents.ts, ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.threads.$id.tsx
https://www.loom.com/share/0113c62a037c4556acaf7c82161131c6
* adds starter messages & introductions into agent form
=> enhance: add starter & introduction message for agents

ui/admin/app/components/ui/dnd/sortable.tsx, ui/admin/app/components/workflow/steps/StepBase.tsx, ui/admin/app/components/workflow/steps/StepsForm.tsx, ui/admin/app/lib/model/workflows.ts
https://www.loom.com/share/a769cedb20c445329bd273d6551a5312?sid=24193c56-700b-43da-a07b-3251c228297a
=> feat: animate workflow steps!

ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/lib/model/toolReferences.ts
Addresses #1307 
* missing adding appOverride.integration in set for ToolCatalog
* update tools list render logic (bundled custom tools got filtered out)
=> fix: custom tool bundle not showing up & oauth custom tool still disabled on agent fix

ui/admin/app/components/workflow/CreateWorkflow.tsx, ui/admin/app/routes/_auth.agents._index.tsx
=> feat: add capabilities to agents and workflows by default

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentForm.tsx, ui/admin/app/components/agent/shared/AgentModelSelect.tsx, ui/admin/app/components/agent/shared/EnvironmentVariableSection.tsx, ui/admin/app/components/workflow/Workflow.tsx, ui/admin/app/tailwind.css
=> feat: move model and env variables to advanced section

pkg/controller/handlers/knowledgefile/knowledgefile.go
When the knowledge source or knowledge set is deleted, then we don't have to delete the files from the workspace one at a time. Instead, the workspace controller will take care of deleting the files all at once.
=> enhance: stop deleting knowledge files file by file

ui/admin/app/components/ui/animate/expand.tsx, ui/admin/app/components/ui/animate/index.ts, ui/admin/app/components/ui/animate/rotate.tsx, ui/admin/app/components/ui/animate/slide-in-out.tsx, ui/admin/app/components/ui/dnd/sortable.tsx, ui/admin/app/components/workflow/steps/StepBase.tsx, ui/admin/app/components/workflow/steps/StepsForm.tsx
=> chore: create abstractions for motion components

ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/ui/clickable-div.tsx
https://github.com/user-attachments/assets/1d08670f-5228-4c7d-9856-73fea6f43a07
=> feat: allow download of thread files via clicking on the file name

ui/admin/app/components/agent/ToolEntry.tsx, ui/admin/app/components/composed/typography.tsx
=> chore: update tool entry description tooltip to align start and smaller width

ui/admin/app/components/user/UserActionsDropdown.tsx
=> fix: disable Update User button for explicit admins

ui/admin/app/components/agent/AgentForm.tsx
* one liner -- line under Instructions to match other sections
=> fix: line styling under Instructions

ui/admin/app/components/ui/markdown.tsx
* allow `a` tags through sanitize
=> fix: allow a href tags through sanitize for markdown

ui/admin/app/components/thread/ThreadMeta.tsx
=> feat: open thread meta files accordion by default

apiclient/types/model.go, pkg/api/handlers/model.go, pkg/storage/openapi/generated/openapi_generated.go, ui/admin/app/components/composed/ComboBox.tsx, ui/admin/app/components/model/DefaultModelAliasForm.tsx, ui/admin/app/lib/model/models.ts
Addresses #1174 
* user friendly label for model provider id
* combobox header tweak
=> enhance: tweak model dropdown & combobox header

pkg/api/handlers/authprovider.go, pkg/api/router/router.go, pkg/proxy/proxy.go
for #1376
https://www.loom.com/share/0834d40ec5a34639a226cec8d27b8c2b
=> enhance: support deconfiguring auth providers

ui/admin/app/components/ui/dialog.tsx
=> fix: auto-focus first focusable element in dialog on open

pkg/render/render.go
https://github.com/obot-platform/obot/issues/1370
We are not include thread knowledge dataset during the retrival process if there are multiple datasets.
=> Fix: fix thread knowledge dataset not being included

pkg/api/handlers/authprovider.go, ui/admin/app/components/auth-and-model-providers/AuthProviderLists.tsx, ui/admin/app/components/auth-and-model-providers/ModelProviderLists.tsx, ui/admin/app/components/auth-and-model-providers/ProviderConfigure.tsx
This was requested today.
https://www.loom.com/share/f1b3cd5f40ef48a08d56b582a38f8134
After recording the loom, I swapped the question mark circle icon for one that is the same design but looks better and more consistent with our kebab icon.
=> fix: auth providers: allow only one at a time

chart/templates/deployment.yaml, chart/templates/secret.yaml, chart/values.yaml, docs/docs/05-configuration/03-auth-providers.md, pkg/bootstrap/bootstrap.go, pkg/services/config.go
=> enhance: add option to disable bootstrap user

ui/admin/app/components/form/controlledInputs.tsx, ui/admin/app/components/user/UserMenu.tsx
Addresses #1315 
* slight user menu styling tweak
* data-1p-ignore to disable 1password autofillable
=> fix: no 1password autofill by default & small user menu styling

pkg/api/handlers/workflows.go, pkg/storage/apis/obot.obot.ai/v1/cronjob.go, pkg/storage/apis/obot.obot.ai/v1/emailaddress.go, pkg/storage/apis/obot.obot.ai/v1/webhook.go
https://github.com/obot-platform/obot/issues/1175
This PR adds a parameter `delete-triggers` to clean up existing triggers.
=> Add delete-triggers parameters to clean up triggers

docs/docs/02-concepts/06-workflows.md, docs/docs/05-configuration/05-email-webhook.md
More updates to workflow on email triggers.
=> Fix: Update docs

ui/admin/app/routes/_auth.workflow-triggers.email.create.tsx
Fixed an issue where email trigger is not returning to trigger page after creation.
=> Fix: email trigger is not returning back to trigger page after creation

pkg/proxy/proxy.go
There was an issue with how I was trying to save the existing cookies when replacing the value of the access token cookie, that was causing all other cookies to get deleted. This fixes that by properly storing the values of the other cookies and then re-adding them to the request.
=> fix: auth: don't delete the csrf cookie

ui/admin/app/components/user/UserUpdateForm.tsx, ui/admin/app/lib/model/auth.tsx
* update workflow for setting first admin user as bootstrap user
https://www.loom.com/share/fd27d46840354b0ca9e38c1b372a1cca
=> fix: improve workflow for first admin user selection

ui/admin/app/components/auth-and-model-providers/ProviderConfigure.tsx
=> fix: include 401/403 for auth/model provider reveal call

ui/admin/app/routes/_auth.threads.$id.tsx
=> fix: make workflow threads readonly

docs/docs/05-configuration/02-model-providers.md, docs/docs/10-enterprise.md
=> Docs: Updates to model providers

ui/handler.go
for #1488
This is a small change to support just `/` as the OAuth2 callback URL for auth providers. There will be some slight changes needed for the frontend and the auth provider tools. But that will be pretty easy to do. Merging this now will not affect anything.
=> chore: backend: support / for the oauth2 callback URL

ui/admin/app/components/auth-and-model-providers/ProviderConfigure.tsx
for #1488
This should NOT be merged until we are sure that every auth provider's OAuth app is updated to have this as a valid redirect URI.
=> chore: frontend: support / for auth provider callback url

ui/admin/app/components/auth-and-model-providers/ProviderForm.tsx, ui/admin/app/components/auth-and-model-providers/constants.ts
=> chore: ui: add constants for okta

ui/admin/app/components/agent/shared/ToolAuthenticationDialog.tsx
=> enhance: add prompt message to pre-auth prompt dialog

pkg/api/handlers/agent.go, pkg/api/handlers/workflows.go, pkg/controller/data/agent.yaml, pkg/controller/handlers/cleanup/credentials.go, pkg/controller/handlers/threads/threads.go, pkg/controller/routes.go, pkg/storage/apis/obot.obot.ai/v1/run.go, pkg/storage/apis/obot.obot.ai/v1/thread.go
Issue: https://github.com/obot-platform/obot/issues/1530
=> fix: remove agent and workflow credentials on delete

ui/admin/app/components/chat/ChatContext.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/chat/MessagePane.tsx, ui/admin/app/routes/_auth.agents.$agent.tsx, ui/admin/app/routes/_auth.threads.$id.tsx
* change agentName -> name since ChatProvider type = workflow || agent
* add (icon || name) check to showIcon
=> fix: empty icon in thread/workflow fix

ui/admin/app/components/oauth-apps/ConfigureOAuthApp.tsx
fix toast showing undefined oauth configuration updated
Addresses #1566
=> fix: toast showing "undefined oauth updated" on replace oauth config

ui/admin/app/routes/_auth.threads.$id.tsx
* only agent/icons for agent threads
=> fix: icons/agent for threads of agent type

ui/admin/app/components/knowledge/AddKnowledgeButton.tsx
=> fix: add microsoft/notion config dialog if knowledge is selected & not configured

pkg/api/handlers/tables.go, pkg/api/handlers/threads.go, pkg/api/router/router.go, ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/model/tables.ts, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/workspaceTableApiService.ts
Addresses #1463 
Notes:
- This PR makes changes to both frontend and backend
- @ivyjeong13 - Do not Review UI portion of this PR until #1568 is merged
displays a dropdown for Tables in the admin thread sidebar
future work:
implement way to open tables in a dialog for viewing/modifying rows
=> feat: admin ui thread view tables

pkg/api/handlers/tables.go, pkg/api/handlers/threads.go, pkg/api/router/router.go, ui/admin/app/components/chat/shared/thread-helpers.ts, ui/admin/app/components/composed/PaginationActions.tsx, ui/admin/app/components/model/tables.ts, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/components/thread/ThreadTableDialog.tsx, ui/admin/app/hooks/pagination/usePagination.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/agentService.ts, ui/admin/app/lib/service/api/primitives.ts, ui/admin/app/lib/service/api/service-primitives.ts, ui/admin/app/lib/service/api/threadsService.ts, ui/admin/app/lib/service/api/workspaceTableApiService.ts, ui/admin/app/lib/service/pagination.ts, ui/admin/app/lib/service/queryService.ts, ui/admin/app/lib/utils/isArrayEqual.ts
addresses #1463 
https://www.loom.com/share/b405f316eb7f49068175d44dd9f62531?sid=55571ab8-2a90-407b-bf24-3b917349002e
=> feat: view database table in expanded dialog

ui/admin/app/components/composed/SetupBanner.tsx
* one-liner fix, missed `steps` -> `stepsToConfigure` check on conditional styling
=> fix: steps check on setup banner styling

ui/admin/app/components/workflow/triggers/WorkflowEmailTab.tsx
Missed some words in admin dashboard
=> fix: Missed some words

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/services/chat/messages.ts, ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/thread.svelte.ts, ui/user/src/lib/services/chat/types.ts
addresses #1582 
https://www.loom.com/share/714b4fa1814e4870b587e95a7acb4368?sid=fb56bb79-e04d-4b33-94c3-5bbf7377e8da
=> feat: allow users to authenticate via credentials in user ui

ui/admin/app/components/chat/Message.tsx, ui/user/src/lib/components/messages/Message.svelte
=> fix: user ui credential inputs styling

ui/admin/app/components/agent/shared/ToolAuthenticationDialog.tsx
=> fix: width/markdown issue in wordpress pre-authentication

ui/admin/app/lib/model/oauthApps/providers/google.ts
Addresses https://github.com/obot-platform/obot/issues/1678
=> docs: add drive scope to google oauth app config instructions

go.mod, go.sum
Required for https://github.com/obot-platform/obot/issues/1671
=> chore: bump gptscript to pick up required envs for daemon tools

ui/admin/app/lib/service/api/agentService.ts, ui/admin/app/lib/service/api/service-primitives.ts
=> fix: prevent mutator service methods from automatically cancelling by default

ui/admin/app/lib/routers/apiRoutes.ts
=> fix: unable to download agent workspace files

ui/admin/app/lib/model/oauthApps/providers/microsoft365.ts
quick one line fix, the last section is for multi-tenant only.
=> fix: update microsoft 365 oauth instruction text

apiclient/agent.go, apiclient/emailreceiver.go, apiclient/run.go, apiclient/thread.go, apiclient/toolref.go, apiclient/types/errors.go, apiclient/types/time.go, apiclient/webhook.go, apiclient/workflow.go, pkg/api/handlers/agent.go, pkg/api/handlers/assistants.go, pkg/api/handlers/files.go, pkg/api/handlers/model.go, pkg/api/handlers/modelprovider.go, pkg/api/handlers/sendgrid/webhook.go, pkg/api/handlers/tasks.go, pkg/api/handlers/threads.go, pkg/api/handlers/webhooks.go, pkg/api/handlers/workflows.go, pkg/api/request.go, pkg/gateway/server/llmproxy.go, pkg/gateway/server/oauth.go, pkg/gateway/server/oauth_apps.go, pkg/gateway/server/token.go, pkg/gateway/server/user.go
There were a bunch of small formatting oddities. I switched to a new AI agent
that found and fixed them. I reviewed by hand and all look good to me.
=> chore: fix formatting

ui/admin/app/components/composed/PaginationActions.tsx
=> fix: showing 1/0 for pagination with no pages

ui/admin/test/mocks/handlers/tools.ts, ui/admin/test/setup.ts
* add enforcement of unhandled async requests that need to be mocked
=> fix: tests, enforce unhandled mocked requests

ui/admin/app/components/tools/toolGrid/ToolGrid.tsx, ui/admin/app/lib/model/toolReferences.ts, ui/admin/app/routes/_auth.tools._index.tsx
Addresses #1273 
* capability section in tools page
=> fix: capabilities in own section in tools page

go.mod, go.sum, pkg/services/config.go
Issue: https://github.com/obot-platform/obot/issues/1725
=> enhance: validate workspace provider configuration on startup

ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/ui/scroll-area.tsx, ui/admin/app/components/ui/scroll-to-bottom.tsx
=> fix: add scrollable content to message prompt dialog

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/AgentAlias.tsx, ui/admin/app/components/agent/AgentContext.tsx, ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/__tests__/Agent.test.tsx, ui/admin/app/components/agent/icon/AgentIcon.tsx, ui/admin/app/components/signin/SignIn.tsx, ui/admin/app/components/ui/animate/animate-resize.tsx, ui/admin/app/components/ui/animate/slide-in-out.tsx, ui/admin/app/components/ui/scroll-area.tsx, ui/admin/app/hooks/animate/useSlideInOut.ts, ui/admin/app/hooks/useDebounce.ts, ui/admin/app/lib/utils/isScrolledToBottom.ts, ui/admin/app/routes/_auth.agents.$id.tsx, ui/admin/app/routes/_auth.task-runs.$id.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
Addresses #1697 
- made header sticky
- adds animation and Try it Out! CTA to open agent in new tab
- removes footer with chat actions and save status
https://www.loom.com/share/1f75be1ab18943d88a185632c6f614eb?sid=3edc3626-c352-456e-bcfb-db495dd68000
=> feat: remove chat from agent edit

ui/admin/app/components/chat/Chatbar.tsx, ui/admin/app/components/chat/Message.tsx, ui/admin/app/components/thread/ThreadTableDialog.tsx, ui/admin/app/components/tools/ToolCatalog.tsx
additional improvements:
- improve accuracy of chat "thinking" indicator
- improved animation for table updates
- debounce image generation to ensure there is no performance hit from text animation
=> chore: tiny cleanup for tool catalog updates

ui/admin/app/components/signin/SignIn.tsx, ui/user/src/routes/+page.svelte, ui/user/src/routes/[agent]/+page.svelte
* when visiting link that requires auth, after logging in, return to that link
Addresses #1557
https://github.com/user-attachments/assets/f77ccd09-cee6-43df-9beb-2d015a30e2bf
=> fix: redirect back to url visited after logging in

ui/admin/app/components/agent/__tests__/Agent.test.tsx
* use userEvent.paste instead 
* assert one call of putSpy / save call has been made
=> fix: remove short timeout & use userEvent.paste

pkg/gateway/server/router.go, pkg/gateway/server/user.go, ui/admin/app/components/agent/AgentAccessControl.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/userService.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/_auth.chat-threads._index.tsx, ui/admin/app/routes/_auth.task-runs._index.tsx, ui/admin/app/routes/_auth.tasks._index.tsx, ui/admin/app/routes/_auth.users.tsx
User Table:
- Enables filtering via query param
- Adds filtr chips
- Adds user email filter header
Thread view
- removes status
- replaces with username w/ link to filtered users table
https://www.loom.com/share/f124868c39d74c5d8526dd5e63341ca5?sid=e36d52c1-8fd1-45e2-9812-4c707fbdae17
=> feat: display user info in thread meta + enable filtering on users table

ui/admin/.prettierrc, ui/admin/app/components/agent/AgentAlias.tsx, ui/admin/app/components/composed/NavigationProgress.tsx, ui/admin/app/components/ui/animate/animate-resize.tsx, ui/admin/app/root.tsx, ui/admin/package.json, ui/admin/pnpm-lock.yaml
addresses #1644 
https://www.loom.com/share/ddbd504ed5dc42be8811f8657991b4dd?sid=a0f36d32-3e76-4621-a3eb-b2ce776605ff
=> feat: add top loading bar on page navigation in admin UI

ui/admin/app/components/chat/ToolCallInfo.tsx
Addresses #1666
https://github.com/user-attachments/assets/8607687d-56c9-4a29-a2c7-08002cbfd19c
=> fix: add scrollarea to tool call info popover

ui/admin/app/components/agent/AgentAccessControl.tsx
=> fix: allow agent access control w/o auth enabled

pkg/tools/resolve.go
The previous way of indexing a tool based on localTool doesn't seem to be correct. the local tools parsed from gptscript load doesn't seem to have tools that are referenced from other gptscripts.
Instead, we should be able to look up tools directly from tool.export. It also needs to correctly reference tools from other gptscript files like ./company.gpt when indexing subTool.
This will solve the hubspot tool case where sub tools are located into other files other that tool.gpt.
=> Fix: Fix tool reference to properly index gpt files

pkg/controller/handlers/toolinfo/toolinfo.go
This should fix oauth not working for knowledge source tools like O365 and Notion.
Credit goes to donnie for figuring this out.
=> Fix: fix oauth for knowledge source

ui/admin/app/lib/model/oauthApps/providers/salesforce.ts
relates to https://github.com/obot-platform/obot/issues/1321
=> chore: improve flow of salesforce setup instructions

ui/admin/app/lib/model/chatEvents.ts, ui/admin/app/lib/store/chat/message-store.ts
=> feat: add tavily search citations

ui/user/eslint.config.js, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/services/chat/messages.ts, ui/user/src/lib/services/chat/types.ts
https://www.loom.com/share/56d0f66a9d324c35b52c029105ac495f?sid=5b7df9b8-599b-4ad1-8356-b79a2cf2942a
=> feat: add citations to user ui

ui/user/package.json, ui/user/pnpm-lock.yaml, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte
https://www.loom.com/share/bb7db5a2094a490ab7a6e9663767c9f5?sid=3105c9b1-40ee-4044-a55e-6b59f01641a8
=> feat: animate text in user UI

pkg/gateway/client/user.go
for https://github.com/obot-platform/obot/issues/1775
=> fix: profile images: load new profile image if user switched auth providers

apiclient/types/oauthapp.go, pkg/gateway/server/oauth_apps.go, pkg/gateway/types/oauth_apps.go, ui/admin/app/components/oauth-apps/OAuthAppTypeIcon.tsx, ui/admin/app/lib/model/oauthApps/index.ts, ui/admin/app/lib/model/oauthApps/oauth-helpers.ts, ui/admin/app/lib/model/oauthApps/providers/pagerduty.ts, ui/admin/public/assets/pagerduty-icon.svg
Added PagerDuty OAuthAppType to exclude sending Basic Auth creds.
Added PagerDuty OAuthApp default settings.
Added PagerDuty OAuthApp setup.
=> enhance: Add support for PagerDuty app

ui/admin/app/components/composed/DataTable.tsx, ui/admin/app/components/composed/Filters.tsx, ui/admin/app/components/composed/typography.tsx, ui/admin/app/routes/_auth.chat-threads._index.tsx, ui/admin/app/routes/_auth.task-runs._index.tsx, ui/admin/app/routes/_auth.tasks._index.tsx
Addresses #1060 
* add apply/clear buttons to created filter
* fix pill
=> fix: add apply/clear for created filter, fix created filter pill

tools/package-tools.sh
Our fork made a couple changes to make authentication work on GKE.
=> chore: use our fork of k8s-cloudkms-plugin

ui/user/src/lib/actions/div.ts, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte
addresses #1810
- improves scroll sticking mechanism to better discern user scroll events from system scroll events
- replaces loading spinner with dot to reduce scroll bouncing
Credit to @ivyjeong13 for helping me with the loading animation
https://www.loom.com/share/b7e5d6daa5f642529df7583577585a3a?sid=3ff4aaec-ae38-461d-9fb3-da38ef96c7b9
=> fix: keep scroll box stuck to bottom on message generation

ui/admin/app/components/ui/markdown.css, ui/user/src/app.css
Addresses #1759 
* more styling fixes for admin-ui & user-ui side for wysiwyg introductions
=> fix: wysiwyg and intro styling fixes

pkg/credstores/credstore.go
The encryption provider was not ready in time for when we needed to use it, leading to crashes. (At least, that is my theory.) This fix adds a retry loop to wait on the health check to pass before proceeding.
=> chore: gcp encryption: make healthz request

ui/admin/app/components/agent/icon/AgentIcon.tsx, ui/admin/app/components/oauth-apps/ConfigureOAuthApp.tsx, ui/admin/app/components/oauth-apps/DeleteOAuthApp.tsx, ui/admin/app/components/oauth-apps/shared/OAuthAppDetail.tsx
* show choose color as disabled if user doesn't select/have an obot logo
* remove success modal & toast redundancy notifications for oauth app configuring
=> fix: remove success/layered modal & choose color fix

ui/admin/app/routes/_auth.users.tsx
* fix not being to filter to another user when on users page with existing user filter
Addresses #1794
=> fix: can filter to diff user on filtered users page

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/editor/Pdf.svelte
=> feat: implement readonly view for pdf files

go.mod, go.sum, pkg/api/router/router.go
=> chore: bump nah to allow dumping of triggers

pkg/api/handlers/agent.go, pkg/api/handlers/assistants.go, pkg/api/handlers/files.go, pkg/api/handlers/threads.go, pkg/api/router/router.go, ui/admin/app/components/chat/Message.tsx, ui/admin/app/lib/model/messages.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/knowledgeFileApiService.ts, ui/admin/app/lib/store/chat/message-store.ts, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/services/chat/messages.ts
file param is of style `<namespace>/<knowledgeset>::<filename>`
Depends on https://github.com/obot-platform/tools/pull/428
Issue https://github.com/obot-platform/obot/issues/1801
https://github.com/user-attachments/assets/e55f8163-a539-4ed7-a70b-ff54fd450767
=> add: assistants knowledge file download API

pkg/api/handlers/tasks.go
Fix so that task can use agent's knowledge data.
=> Fix: make sure task can use agent's knowledge

ui/user/src/routes/[agent]/+layout.svelte
Addresses #1859 
https://github.com/user-attachments/assets/f9d3b0ff-5667-4798-98c0-2c8c16c7d8dd
=> fix: max-width on main to avoid column stretch

ui/admin/app/routes/_auth.agents._index.tsx
* agent has the 'deleted' property too, if it is in process of being deleted
* filter out those with deleted in agents page
Addresses #1851
=> fix: account for agent.deleted in agents page

ui/admin/app/components/agent/AgentMeta.tsx, ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.task-runs.$id.tsx
* project threads shouldn't be accounted for in the thread count
* one nit styling padding for back button task run thread page
=> fix: agent thread counts, ignore project threads

ui/user/src/lib/actions/index.ts, ui/user/src/lib/actions/popover.svelte.ts, ui/user/src/lib/actions/popover.ts, ui/user/src/lib/components/CopyButton.svelte, ui/user/src/lib/components/navbar/Files.svelte, ui/user/src/lib/components/navbar/KnowledgeFile.svelte, ui/user/src/lib/components/navbar/KnowledgeFiles.svelte, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/components/navbar/Menu.svelte, ui/user/src/lib/components/navbar/Tables.svelte, ui/user/src/lib/components/navbar/Tasks.svelte, ui/user/src/lib/components/navbar/Tools.svelte
=> feat: add tooltips to truncated list items in menu popups

ui/admin/app/components/agent/UserAuthorizationSelect.tsx
=> fix: filter admin users from access  control dropdown

ui/user/src/lib/components/messages/Message.svelte
* make whole preview of created file clickable
* add decodeuricomponent on citation display url
=> fix: whole created file preview is clickable to preview

ui/admin/app/components/agent/icon/AgentIcon.tsx
* keep color when switching icons if color was selected
=> fix: keep color when switching icons

ui/user/src/lib/components/messages/Message.svelte
https://www.loom.com/share/98abe0bb878c40adb0ad89bc5913f0a1?sid=6a5ad7f4-07e0-464b-85c3-a3a688c48808
=> fix: broken syntax highlighting in generated code tags

ui/user/src/lib/components/tasks/Steps.svelte
* adds error if trying to run test without any instructions, allow run of thread once there is at least one instruction
=> fix: add error state in Steps when testing Tasks

pkg/api/handlers/tasks.go
Fix to have params created from UI.
=> Fix: fix param task

go.mod, go.sum, pkg/controller/handlers/cleanup/cleanup.go, pkg/invoke/invoker.go
This change also removes some unnecessary uncached calls to the database.
=> chore: update kinm to cefd352a44b5

go.mod, go.sum, pkg/controller/handlers/knowledgesource/knowledgesource.go
The fix in kinm exposed a potential bug as well: not recreating the workspace of
a knowledge source if it gets deleted. That is fixed here as well.
=> chore: bump kinm to da1846b6055e

go.mod, go.sum
=> chore: revert kinm sql change to look for empty strings

pkg/api/handlers/projects.go
Before this change, users could only list their own projects. This change allows
admins to list all projects with the all=true query parameter.
=> enhance: allow admins to list all projects

Dockerfile, azure-encryption.yaml, pkg/credstores/credstore.go, pkg/services/config.go, tools/package-tools.sh
See my video in Slack for a demo of this.
=> feat: add azure key vault encryption

ui/user/src/routes/home/+page.svelte
=> fix: landing create new obot styling for mobile

pkg/controller/handlers/projects/projects.go, pkg/controller/routes.go
=> fix: copy parent project manifest to children

pkg/api/handlers/projectshare.go
Before this change, thread shares were created "for" the user that made the
request. Now, thread shares are created "for" the user on the thread.
=> fix: share threads by thread user

ui/user/src/routes/home/+page.svelte
=> fix: placeholder image webp

ui/admin/app/components/agent/AgentMeta.tsx, ui/admin/app/components/agent/DeleteAgent.tsx, ui/admin/app/components/composed/Filters.tsx, ui/admin/app/components/sidebar/Sidebar.tsx, ui/admin/app/components/task/TaskMeta.tsx, ui/admin/app/components/thread/ThreadMeta.tsx, ui/admin/app/hooks/useRouteInfo.ts, ui/admin/app/lib/model/tasks.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/projectApiService.ts, ui/admin/app/lib/service/routeService.ts, ui/admin/app/routes/_auth.agents._index.tsx, ui/admin/app/routes/_auth.chat-threads.$id.tsx, ui/admin/app/routes/_auth.chat-threads._index.tsx, ui/admin/app/routes/_auth.obots._index.tsx, ui/admin/app/routes/_auth.task-runs.$id.tsx, ui/admin/app/routes/_auth.task-runs._index.tsx, ui/admin/app/routes/_auth.tasks.$id.tsx, ui/admin/app/routes/_auth.tasks._index.tsx, ui/admin/test/mocks/models/task.ts
@ivyjeong13 - Please review #2003 before reviewing this PR :)
addresses #2012
- replaces agent column with obot column in chat threads page
- renames `Agents` top level page to `Base Agents`
- replaces `Threads` column with `Obots` on agents page
- adds `Obots` property to agent meta
- adds tasks count + link to obots page
- adds `Obot` property to chat thread and workflow run meta
- replaces `Agent` column with `Obot` in tasks page
=> enhance: add project information throughout the admin ui

ui/user/src/lib/components/edit/CollapsePane.svelte, ui/user/src/lib/errors.ts, ui/user/src/routes/+error.svelte, ui/user/src/routes/[agent]/+page.svelte, ui/user/src/routes/[agent]/+page.ts, ui/user/src/routes/o/[project]/+page.svelte, ui/user/src/routes/o/[project]/+page.ts, ui/user/src/routes/s/[id]/+page.svelte, ui/user/src/routes/s/[id]/+page.ts
Addresses #1972 
* fallback +error.svelte page, displays 404, 403, 500
=> fix: add error fallback page

go.mod, go.sum, pkg/controller/handlers/cleanup/cleanup.go
This change also adds back the uncached gets on cleanup.
=> chore: bump nah to 09e6e25e968f

ui/user/src/app.css, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Navbar.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/messages/Input.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/messages/MessageIcon.svelte, ui/user/src/lib/components/navbar/Menu.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/lib/icons/AssistantIcon.svelte
* first run of user ui changes
=> enhance: general user-ui chat cleanup

ui/admin/app/components/agent/ToolEntry.tsx, ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/__tests__/Agent.test.tsx, ui/admin/app/components/tools/ToolCatalog.tsx, ui/admin/app/components/tools/ToolCatalogGroup.tsx, ui/admin/app/components/tools/ToolItem.tsx, ui/admin/app/components/tools/toolGrid/BundleToolList.tsx, ui/user/src/app.css, ui/user/src/lib/actions/popover.svelte.ts, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/edit/CollapsePane.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/edit/Tools.svelte, ui/user/src/lib/context/toolReferences.svelte.ts, ui/user/src/lib/services/chat/types.ts, ui/user/src/lib/stores/errors.svelte.ts, ui/user/src/routes/o/[project]/+page.svelte, ui/user/src/routes/o/[project]/+page.ts
addresses #1977
- Updates admin UI tool catalog to allow for combinations of both bundle tools with granular tools on an agent
- Adds a tool catalog (similar to admin UI) to the user UI
=> enhance: update admin tool catalog list + add tool catalog to user ui

docs/docs/50-configuration/06-encryption-providers.md
Adding docs for the KMS providers based.
=> chore: docs add azure kms

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/editor/Controls.svelte, ui/user/src/lib/components/messages/Input.svelte
- improves styling of file editor panel
- improves animations (removes snapping of chat text)
- sets text to fade out on scroll for both the top and bottom of the chat container
- moves download button to be located inside of the text editor
- adds file picker to editor tabs
- prevents wrapping from tabs
https://www.loom.com/share/6a05c882b58f4030a4ae631cbbf1f538?sid=f3eeee24-24da-467e-815a-cc97fcd3a7f0
=> enhance: user ui editor UX

pkg/api/authz/pathmatcher.go, ui/user/src/lib/components/sidebar/TaskItem.svelte, ui/user/src/lib/components/sidebar/Tasks.svelte
- Add a dropdown menu to task runs that allows users to delete them
- Fixes an issue preventing authorized users from deleting task runs
Addresses https://github.com/obot-platform/obot/issues/2122
https://github.com/user-attachments/assets/4d2604b5-0db5-40ee-bc2b-f2a9d4a3f622
=> enhance: add ability to delete task runs 

pkg/api/authz/thread.go
I'm not 100% sure if this is the proper fix, but I think it is. I'll make sure Darren sees it.
for https://github.com/obot-platform/obot/issues/1978
=> fix: authz: fix access to threads

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/tailwind.config.ts
https://www.loom.com/share/63cbfc5bf8e84d4bb96b7d0385a193c1
=> enhance: chat ui updates

ui/user/src/app.css, ui/user/src/lib/components/profile/ProfileIcon.svelte, ui/user/src/lib/components/tasks/Files.svelte, ui/user/src/lib/components/tasks/Input.svelte, ui/user/src/lib/components/tasks/OnDemand.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/lib/components/tasks/Trigger.svelte
https://www.loom.com/share/38c5339ed0a44e34a984b6185f83bed9
=> enhance: task editor ui cleanup

pkg/api/handlers/threads.go, pkg/render/render.go, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/tasks/Task.svelte
- **chore: make thread env inheritable**
- **bug: fix task delete from task edit page**
=> bug: fix task delete from task edit page

ui/user/src/lib/components/Thread.svelte
Addresses https://github.com/obot-platform/obot/issues/2130
Signed-off-by: Nick Hale <4175918+njhale@users.noreply.github.com>
=> chore: add disclaimer below chat box

ui/user/src/app.css, ui/user/src/lib/actions/overflow.ts, ui/user/src/lib/actions/popover.svelte.ts, ui/user/src/lib/actions/resize.ts, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/edit/Tools.svelte, ui/user/src/lib/components/editor/Controls.svelte, ui/user/src/lib/components/editor/FileEditors.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/sidebar/Tasks.svelte
addresses #2151
- scroll container was not expanded to full width in the chat box
- resizing was broken on editor panel
- fixes issue where pdf viewer disappears
=> fix: various editor ux issues

ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte
Addresses https://github.com/obot-platform/obot/issues/2047
=> fix: don't show obot icons, intros, or starter messages for task runs

ui/user/src/lib/components/sidebar/TaskItem.svelte, ui/user/src/lib/components/sidebar/Threads.svelte
Addresses https://github.com/obot-platform/obot/issues/2125
https://github.com/user-attachments/assets/6491d401-355c-4a1d-8bb6-c4fc59d768c4
=> fix: show dropdown dots on hover instead of click

ui/user/src/lib/components/ToolPill.svelte, ui/user/src/routes/home/+page.svelte
- Fix dark mode support for the "My Obots" section header
- Make tool pills darker in dark mode
=> fix: darkmode for my obots on home page

ui/user/src/lib/components/navbar/Projects.svelte
Addresses https://github.com/obot-platform/obot/issues/2118
=> enhance: split obot nav into recently used and my obots sections

ui/user/src/lib/components/Thread.svelte
=> enhance: add report bug link near disclaimer text

ui/user/src/app.css, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/navbar/Menu.svelte, ui/user/src/routes/+page.svelte
* non-logged in home page mobile styling fixes [Slack Reference](https://acorn-io.slack.com/archives/C07P0EZR917/p1742150397846259)
* overflow showing up in mobile chat screen [Slack Reference](https://acorn-io.slack.com/archives/C07P0EZR917/p1742150397846259)
=> enhance: more mobile styling updates

ui/user/src/lib/services/editor/index.svelte.ts
for https://github.com/obot-platform/obot/issues/1978
Video to explain it:
https://www.loom.com/share/4ec15eff9fa742aebf68cd3a878aec20
=> fix: user ui: use correct project ID in file download URL

ui/user/src/app.css, ui/user/src/lib/actions/reactiveLabel.svelte.ts, ui/user/src/lib/actions/textarea.ts, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/edit/CollapsePane.svelte, ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/edit/General.svelte, ui/user/src/lib/components/edit/GenerateIcon.svelte, ui/user/src/lib/components/edit/Instructions.svelte, ui/user/src/lib/components/edit/Interface.svelte, ui/user/src/lib/components/edit/Tasks.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/KnowledgeUpload.svelte, ui/user/src/lib/components/navbar/Tools.svelte
Addresses #2095 
* consistent buttons in editor mode
* some styling updates for editor (font sizes, editing image)
https://www.loom.com/share/97b34e6b90504d2681cd85fe5aeb3da0
=> fix: button consistency & editor stylings

ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/messages/MessageIcon.svelte
https://www.loom.com/share/2cbec5dfa1bf42ed8947b4e5bf438b94
* move Input details into thread
* clean up json preview of Output
=> enhance: input details in thread

ui/user/src/routes/home/+page.svelte
https://github.com/user-attachments/assets/485fb83c-f915-492a-8437-ee7e6fb02676
=> enhance: add remove button to recently used obots menu

ui/user/src/lib/actions/reactiveLabel.svelte.ts
* Oops missed this, works on initial mount but needs to update as value changes
=> fix: reactiveLabel update when value changes

pkg/controller/handlers/runs/runs.go
=> fix: stop marking runs inactive when thread is deleting

ui/user/src/lib/components/messages/Message.svelte
https://github.com/user-attachments/assets/d0c432b1-bd74-45d1-8e4a-b9fc89cba991
* update to Thread tool "Details"
=> fix: change thread tool input to opt-in button

ui/user/src/lib/components/Confirm.svelte, ui/user/src/routes/+page.svelte
* tailwind v4, no bg-opacity-[val], use bg-[color]/[opacity] instead
=> fix: fix dialog backdrop being solid black

.github/workflows/build-tools.yaml, .github/workflows/docker-build-and-push.yml, Dockerfile, Dockerfile-tools
requires https://github.com/obot-platform/tools/pull/527 and https://github.com/obot-platform/enterprise-tools/pull/40
=> chore: use built tools image

pkg/api/server/server.go, pkg/gateway/client/apiactivity.go
Additionally, there are some users that have a blank UID. Stop tracking activity
for those users as well.
=> fix: stop tracking user activity for the anonymous user

ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte
* some restructuring to get user to be able scroll outside the chat well
https://github.com/user-attachments/assets/30a034a4-1af7-4baa-91cb-8963ff29bc0e
=> fix: be able to scroll outside chat well

ui/user/src/lib/components/Thread.svelte
* add introductionMessage back, below basicSection/editorBasicSection
=> fix: introductionMessage back in thread

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/services/editor/index.svelte.ts
Addresses #2248 
* when onFileChanged is fired, need to call saveContents
=> fix: file editor not saving when file contents changed

ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/services/chat/messages.ts
=> fix: abort on chat ui

ui/user/src/app.css, ui/user/src/lib/actions/popover.svelte.ts, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/Credentials.svelte, ui/user/src/lib/components/messages/Input.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/tasks/Dropdown.svelte, ui/user/src/lib/components/tasks/Files.svelte, ui/user/src/lib/components/tasks/Input.svelte, ui/user/src/lib/components/tasks/OnDemand.svelte, ui/user/src/lib/components/tasks/Schedule.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/lib/components/tasks/Trigger.svelte, ui/user/src/lib/components/tasks/Type.svelte
=> enhance: task & task ui updates

pkg/gateway/server/oauth_apps.go, pkg/storage/apis/obot.obot.ai/v1/oauthapp.go
Fix the oauth app to look it up in a correct way.
https://github.com/obot-platform/obot/issues/2331
=> Fix: Look up oauth app in a right way

pkg/api/server/server.go, ui/user/src/lib/errors.ts, ui/user/src/routes/+error.svelte
If the anonymous user is unauthorized, then whoever made the request should authenticate.
=> chore: return 401 when the anonymous user is unauthorized

ui/user/src/lib/components/tasks/Schedule.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte
* add data-testid for Webdriver.IO automation testing per @shweta8996 's request
* and quick styling consistency update for the schedule dropdowns not matching that was bugging me lol
=> chore: add data-testids for step buttons

ui/user/src/app.css, ui/user/src/lib/components/FeaturedObotCard.svelte, ui/user/src/lib/components/ObotCard.svelte, ui/user/src/lib/url.ts, ui/user/src/routes/+page.svelte, ui/user/src/routes/catalog/+page.svelte, ui/user/src/routes/catalog/+page.ts, ui/user/src/routes/home/+page.svelte, ui/user/src/routes/home/+page.ts, ui/user/src/routes/o/[project]/+page.svelte
https://www.loom.com/share/f268443dab164fbeb23b51e32055a199
* adds homepage featured & regular obot card changes
* obot catalog page
=> enhance: homepage changes & obot catalog page

pkg/controller/routes.go, pkg/gateway/server/oauth_apps.go, pkg/storage/apis/obot.obot.ai/v1/oauthapp.go
Look up oauth app correctly using both id and alias.
=> Look up oauth correctly

ui/user/src/app.css, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Navbar.svelte, ui/user/src/lib/components/edit/EditIcon.svelte, ui/user/src/lib/components/edit/General.svelte, ui/user/src/lib/components/edit/Instructions.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/EditorToggle.svelte, ui/user/src/routes/o/[project]/+page.svelte
https://www.loom.com/share/25d85934fea444da92a6dfddffc38ba7
* obot instance editor mode 
* removal of copy / create new obot option if you're not the original owner
=> enhance: obot editor instance updates

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/messages/Message.svelte
* fix weird resize behavior
* close and show files button going off screen when width is too small
=> fix: file editor ui wonkiness

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/components/sidebar/Threads.svelte, ui/user/src/routes/o/[project]/+page.svelte
* revert the setting of first thread or creating a new thread change
* do similar thing with files, create thread if user clicks thread tool catalog
* remove `navigating` check, swore there was an error before but now think I'm going crazy 🤷‍♀️
=> fix: revert set initial thread change

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/editor/Codemirror.svelte, ui/user/src/lib/components/editor/Controls.svelte, ui/user/src/lib/components/editor/FileEditors.svelte, ui/user/src/lib/components/editor/Milkdown.svelte, ui/user/src/lib/components/editor/Table.svelte
* rework files buttons to file tabs
* fix various styling issues 
* fix codemirror tooltip placement
Addresses #2398 
https://www.loom.com/share/14a8a24b31a14bfda96ce67f8159b5d9
=> enhance: update file editor

pkg/api/handlers/slack.go, pkg/api/handlers/slackevent.go, pkg/api/handlers/tasks.go, pkg/api/router/router.go, pkg/gateway/server/oauth_apps.go, pkg/storage/apis/obot.obot.ai/v1/slacktrigger.go, pkg/storage/openapi/generated/openapi_generated.go, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/slack/Slack.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/lib/components/tasks/Trigger.svelte, ui/user/src/lib/components/tasks/Type.svelte, ui/user/src/lib/services/chat/http.ts, ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/types.ts
1. Add slack integration UI.
2. Add slack triggering for task.
3. Some other tweaks to make UI nicely.
=> Feat: Add slack integration ui

pkg/bootstrap/bootstrap.go
=> enhance: bootstrap: always print token if bootstrap is enabled

ui/user/src/lib/components/navbar/EditorToggle.svelte
* quick request from Shweta to add test-id for the obot editor btn
=> chore: add data-testid for obot editor btn

ui/user/src/lib/actions/clickoutside.ts, ui/user/src/lib/components/Search.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/routes/o/[project]/+page.svelte
Addresses #2376 
https://www.loom.com/share/e6532a8def8741b8bece196507ccaabc
* Also includes filtering out some other basic tools: 'Threads' & 'Obot Website Knowledge' 
https://acorn-io.slack.com/archives/C03FU91U4SX/p1743710370900289?thread_ts=1743707670.160049&cid=C03FU91U4SX
=> fix: tool catalog search updates

ui/user/src/app.css, ui/user/src/lib/actions/tooltip.svelte.ts, ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/CustomTool.svelte, ui/user/src/lib/components/edit/CustomTools.svelte, ui/user/src/lib/components/edit/Tasks.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/edit/Tools.svelte, ui/user/src/lib/components/edit/customtool/Env.svelte, ui/user/src/lib/components/edit/customtool/Params.svelte, ui/user/src/lib/components/tasks/Input.svelte, ui/user/src/lib/components/tasks/OnDemand.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/routes/home/+page.svelte
* custom tools TLC 
* some UI consistency in arguments/running with arguments in tasks & custom tools
* tweak to popover action to disable portaling if needed (keeps tooltips working in dialogs moved to the #topLayer)
* also tacked on: fix to make sure the fade-in/fade-out gradients do not overlap over the scrollbars
Addresses #2404 
https://www.loom.com/share/12c1adf656a341659df968bc49aa76d5
=> enhance: custom tools TLC

ui/user/src/lib/components/messages/Input.svelte
super quick! : )
Addresses #2132
=> fix: allow user to continue typing in chat during generation

go.mod, go.sum, pkg/gemini/client.go, pkg/services/config.go, ui/user/src/lib/components/edit/GenerateIcon.svelte, ui/user/src/lib/services/editor/index.svelte.ts
- **enhance: retry gemini icon gen when image is filtered**
- **enhance: make icon generation errors pretty**
Addresses https://github.com/obot-platform/obot/issues/2264
e.g. filtered image error
=> Improve content-policy error handling for generated icons

pkg/invoke/invoker.go
for https://github.com/obot-platform/obot/issues/2367
Before: 
After:
=> fix: clean up error messages in invoker code

ui/user/src/lib/components/edit/CredentialAuth.svelte, ui/user/src/lib/components/messages/Message.svelte
for https://github.com/obot-platform/obot/issues/2367
https://www.loom.com/share/b647eb9527844291824df7be07a3afa3
=> chore: ui: add close button for credential errors

pkg/api/handlers/projects.go, pkg/api/handlers/projectshare.go, ui/user/src/lib/components/ObotCard.svelte, ui/user/src/lib/components/ToolPill.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/constants.ts
Addresses #2384 
https://github.com/user-attachments/assets/b0ab98ae-9f6b-4506-9128-8374b587aac4
https://github.com/user-attachments/assets/ea4b47a4-b502-493e-a550-65c2996ed717
=> fix: include built-in tools for homepage obot cards

ui/admin/app/components/agent/DefaultAgent.tsx, ui/admin/app/lib/model/agents.ts, ui/admin/app/lib/routers/apiRoutes.ts, ui/admin/app/lib/service/api/agentService.ts, ui/admin/app/routes/_auth.agents._index.tsx
Addresses #2099 
Related Loom: https://www.loom.com/share/f2ef6b1d6d5e4225a9b95cf6759bc3da
=> enhance: set default agent option in admin-ui

pkg/controller/handlers/knowledgesummary/knowledgesummary.go
Knowledge summaries were being generated from only the first page of
content. This resulted in poor summaries for documents with little or
no information on the first page (e.g. slide deck PDF starting with a title
slide). To fix this, gather content from each page until the 3000
character knowledge summary limit is reached.
Addresses https://github.com/obot-platform/obot/issues/2381
=> fix: generate knowledge summaries from more than the first page

go.mod, go.sum
for https://github.com/obot-platform/obot/issues/2367
to bring in https://github.com/gptscript-ai/gptscript/commit/4b87a83c9191d1dfd92be8511c9dcabfd55e0f73
=> chore: bump gptscript dependency

pkg/api/authz/authz.go, pkg/api/authz/resources.go, pkg/api/handlers/projectshare.go, pkg/api/router/router.go, ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/s/[id]/+page.svelte, ui/user/src/routes/s/[id]/+page.ts
Related Loom: https://www.loom.com/share/beed6d3f3f254215983bd950104b59ab
Addresses #2254
=> enhance: shared obot warning

ui/user/src/lib/components/edit/GenerateIcon.svelte
Addresses https://github.com/obot-platform/obot/issues/2264
=> fix: capture more image filtered errors in icon generation popout

ui/user/src/lib/components/tasks/Type.svelte
=> task: update task schedule default to daily

pkg/gateway/client/session.go, pkg/gateway/client/user.go, pkg/gateway/server/user.go
There was a race condition that would cause sessions to not always get cleaned up. This ensures that the sessions get cleaned up when the user is deleted.
Issue: https://github.com/obot-platform/sensitive-issues/issues/28
=> fix: immediately cleanup session when deleting a user

chart/values.yaml, docs/docs/50-configuration/01-general.md, pkg/controller/handlers/retention/retention.go, pkg/controller/routes.go
Forgot to take care of these earlier.
=> chore: add retention to chart and docs; add retention migration

ui/user/src/lib/components/edit/CredentialAuth.svelte, ui/user/src/lib/components/edit/Credentials.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/navbar/Credentials.svelte
Loom: https://www.loom.com/share/f17fb57d169f45f2a9a5144b37522a99
Addresses #2387 
Also addresses: 
* adds bundle tag in search results for tool catalog
* clicking the ChevronsRight also moves the tool over in tool catalog
=> fix: cred dialog tweaks & helper text clarity

pkg/gateway/client/runstate.go
When decompress chatState, it accidentally use the encrypted chatState value after creating runState. It should use the decrypted one when running decompress.
[https://github.com/obot-platform/obot/issues/2528](https://github.com/obot-platform/obot/issues/2528#event-17292949980)
=> Fix: assign chatState before encryption

apiclient/thread.go, pkg/invoke/invoker.go, pkg/jwt/jwt.go
This PR allows the obot token passed to run to upload file/knowledge files that are used in https://github.com/obot-platform/tools/pull/587
https://github.com/obot-platform/obot/issues/2563
=> Chore: Add necessary library and permission to upload files in client

ui/admin/app/components/agent/Agent.tsx, ui/admin/app/components/agent/ToolEntry.tsx, ui/admin/app/components/agent/ToolForm.tsx, ui/admin/app/components/agent/shared/AgentCapabilityForm.tsx, ui/admin/app/routes/_auth.agents._index.tsx
* changes toggle to dropdown to allow Always On/Optional - On/Optional - Off/Off for capabilities
* Addresses #2090
=> enhance: admin capabilities tools update (optional on/off)

ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/FeaturedObotCard.svelte, ui/user/src/lib/components/ObotCard.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/edit/ToolCatalog.svelte, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/sort.ts, ui/user/src/routes/+error.svelte, ui/user/src/routes/+page.svelte, ui/user/src/routes/+page.ts, ui/user/src/routes/catalog/+page.svelte, ui/user/src/routes/catalog/+page.ts, ui/user/src/routes/home/+page.ts, ui/user/src/routes/profile/+page.svelte, ui/user/src/routes/s/[id]/+page.svelte
https://www.loom.com/share/00270d854cea4d339c7fa1996babbaf5
https://www.loom.com/share/8a1ff32becdf43158d6bd301d268806a
* updates to navigation experience 
* also includes sorting priority of tools that shown in the obot cards (Analyze Images, Generate Images, & Obot Search being least prio)
* also fix for click outside should trigger save on ToolCatalog
Addresses #2588
=> enhance: catalog instead of home & create obot in projects dropdown

ui/user/src/lib/components/navbar/KnowledgeUpload.svelte
We should allow uploading markdown file in knowledge.
=> Fix: allow uploading markdown files

ui/user/src/lib/components/EditMode.svelte
=> fix: delete in obot editor relocating when it shouldn't

apiclient/client.go, pkg/cli/root.go, pkg/cli/token.go
This command will also fetch a token if one is not available.
=> enhance: add CLI command to print token

pkg/controller/handlers/workflowstep/loop.go, pkg/controller/handlers/workflowstep/workflowstep.go, pkg/controller/routes.go, pkg/invoke/invoker.go, pkg/render/render.go
depends on https://github.com/obot-platform/tools/pull/599
=> enhance: allow looping over JSON string lists in addition to datasets 

ui/user/src/lib/constants.ts
=> Fix: switch to linkedin featured assistant

apiclient/types/projectshare.go, pkg/api/handlers/projectshare.go, pkg/storage/apis/obot.obot.ai/v1/threadshare.go, pkg/storage/openapi/generated/openapi_generated.go, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/s/[id]/+page.ts
Addresses #2626 
* do not do GetProject call to find out if they're an editor, instead include in the ProjectShare information
=> fix: 403 on non-admin user visiting shared featured agent

ui/user/src/lib/components/Obot.svelte
Add shortcuts to open edit mode and thread panel.
ctrl + e: edit mode
ctrl + t: thread panel
ctrl + h: help on shortcuts
=> Chore: add shortcut to open edit mode and thread panel

ui/user/src/lib/components/Footer.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/services/chat/http.ts, ui/user/src/routes/+page.svelte, ui/user/src/routes/privacy-policy/+page.svelte, ui/user/src/routes/terms-of-service/+page.svelte
https://www.loom.com/share/a17fa7468cda4b469a04e2ff82b988fe
=> enhance: add terms of service and privacy policy pages

pkg/gateway/client/session.go
This will help me track down an issue with the "log out of all other sessions" function.
=> chore: change delete session logs to info level

ui/user/src/lib/components/Footer.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/services/chat/http.ts, ui/user/src/routes/privacy-policy/+page.svelte, ui/user/src/routes/terms-of-service/+page.svelte
* adds /privacy-policy & /terms-of-service links and pages in prototype
=> add privacy policy & terms of service

apiclient/types/usage.go, pkg/gateway/client/tokenactivity.go, pkg/gateway/server/llmproxy.go, pkg/gateway/server/usage.go, pkg/gateway/types/activity.go, pkg/invoke/invoker.go, pkg/storage/openapi/generated/openapi_generated.go
This allows for better observability and tracking of everything chat completion request that comes through the proxy.
=> enhance: move token tracking into the LLM proxy

ui/user/src/lib/components/EditMode.svelte, ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Navbar.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Select.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/SidebarConfig.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/ChatBot.svelte, ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/edit/Interfaces.svelte, ui/user/src/lib/components/edit/Members.svelte, ui/user/src/lib/components/edit/Tools.svelte, ui/user/src/lib/components/slack/Slack.svelte, ui/user/src/routes/agents/+page.svelte, ui/user/src/routes/o/[project]/+page.svelte
* fix linter/type errors from user-ui prototype stuffs
=> chore: fix linter/type errors user-ui

pkg/api/handlers/assistants.go, pkg/events/events.go, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/services/chat/messages.ts, ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/thread.svelte.ts, ui/user/src/lib/services/chat/types.ts
In the user UI, add a `Load older messages` button to the top of the chat that allows users to view older messages when available.
Addresses https://github.com/obot-platform/obot/issues/2365
https://github.com/user-attachments/assets/a585ca42-180d-461f-a020-9633e14a1e86
=> feat: add the ability to load previous messages in chat

pkg/api/handlers/projects.go, ui/user/src/routes/i/[code]/+page.svelte
for https://github.com/obot-platform/obot/issues/2802
I also made a style change for https://github.com/obot-platform/obot/issues/2801
=> fix: project membership: allow owner and members to see all threads

ui/user/src/lib/components/edit/Files.svelte, ui/user/src/lib/components/tasks/OnDemand.svelte, ui/user/src/lib/components/tasks/Task.svelte, ui/user/src/lib/components/tasks/TaskOptions.svelte
- move task option above steps section
- code cleanup
- minor improvements
=> chore: always display task option above steps

pkg/api/handlers/projects.go, ui/user/src/routes/agents/+page.svelte
I also edited the UI so that the delete button does not appear unless you are the owner.
=> fix: disallow project members from deleting projects

pkg/api/authz/resources.go, pkg/api/handlers/threads.go, pkg/api/router/router.go
I forgot to do this in my PR that introduced this route.
=> fix: authz: add thread default model route to authz logic

ui/user/src/app.css, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Search.svelte, ui/user/src/lib/components/agents/AgentCatalog.svelte, ui/user/src/lib/components/edit/CredentialAuth.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpInfoConfig.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/messages/MessageIcon.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/components/sidebar/ModelProviders.svelte, ui/user/src/routes/agents/+page.svelte, ui/user/src/routes/catalog/+page.svelte, ui/user/src/routes/catalog/+page.ts
* legacy auth when selecting former tool bundle mcp server
=> fix: use legacy auth with tool bundle mcp server

ui/user/src/lib/components/edit/Interfaces.svelte, ui/user/src/lib/context/layout.svelte.ts
=> chore: sort interfaces & add mcp server option

ui/user/src/lib/components/tasks/LoopStep.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte, ui/user/src/lib/components/tasks/Task.svelte
Addresses #2842 
- add auto scroll feature during task run
- add scroll navigation 
- enhance steps animations and UI
=> feat: add task run autoscroll & scroll navigation

ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/tasks/LoopStep.svelte, ui/user/src/lib/components/tasks/Step.svelte
=> fix: looping ux bugs

ui/user/src/lib/components/edit/CredentialAuth.svelte
Fixed a regression bug where sending credential is stuck after selecting oauth vs pat.
=> Fix: fix regression when sending credentials

ui/user/src/routes/i/[code]/+page.svelte
for https://github.com/obot-platform/obot/issues/2816
=> fix: ui: display 'my agent' instead of unnamed project in invitations

ui/user/src/lib/components/mcp/McpInfoConfig.svelte
Not sure why this is hardcoded....but it fixes https://github.com/obot-platform/obot/issues/2898
=> Fix: fix google search mcp tools

ui/user/src/lib/actions/scrollFocus.svelte.ts, ui/user/src/lib/components/Sidebar.svelte
https://www.loom.com/share/de44dce8e4c3440da32591bc4ca0c08d
Addresses #2829
=> fix: keep sidebar content in view when expanding

ui/user/src/lib/components/Thread.svelte
=> fix: select old thread doesnt start stick to bottom if user scrolled up

ui/user/src/lib/components/Navbar.svelte, ui/user/src/lib/components/Sidebar.svelte, ui/user/src/lib/components/edit/BuiltInCapabilities.svelte, ui/user/src/lib/components/edit/Knowledge.svelte, ui/user/src/lib/components/navbar/Logo.svelte, ui/user/src/lib/context/helperMode.svelte.ts, ui/user/src/lib/context/toolReferences.svelte.ts
* `Built-In Capabilities` section for sidebar
=> feat: built-in capabilities section

ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpInfoConfig.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte
* show remote config form when mcp server is a url manifest
=> fix: use mcp catalog remote config form for url manifests

ui/user/src/lib/actions/scrollFocus.svelte.ts, ui/user/src/lib/components/mcp/McpCatalog.svelte
* sort mcp categories: Official, Verified, Browse All
* also fix with useScrollFocus action, avoid scroll focusing with nested dialog content interactions
=> chore: sort mcp catalog categories

pkg/controller/handlers/toolreference/toolreference.go, pkg/storage/apis/obot.obot.ai/v1/toolreference.go, pkg/storage/openapi/generated/openapi_generated.go, pkg/tools/resolve.go
for https://github.com/obot-platform/obot/issues/2933
=> chore: remove capability tools from catalog

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/navbar/Tools.svelte
=> fix: show tools dropdown in thread if there are project mcps

ui/user/src/lib/components/integrations/webhook/Webhook.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte
* makes sure to reset after opening mcp catalog again 
* default show all descriptions to true
=> fix: tools after config showing incorrectly

ui/user/src/lib/components/tasks/Step.svelte
=> chore: show confirmation dioalog before converting to a regular step

ui/user/src/lib/components/tasks/TaskOptions.svelte
This PR fixed an issue where onDemand and schedule tab is not showing up for tasks.
=> Fix: fix schedule and onDemand tab not showing up

ui/user/src/lib/components/tasks/LoopStep.svelte, ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte, ui/user/src/lib/components/tasks/Task.svelte
=> fix: steps grayed on post run

pkg/controller/handlers/task/task.go, ui/user/src/lib/components/edit/Interfaces.svelte, ui/user/src/lib/components/integrations/discord/Discord.svelte, ui/user/src/lib/components/integrations/slack/Slack.svelte, ui/user/src/lib/components/tasks/TaskOptions.svelte
- Fixing discord integration with new external interface UX. 
- Adding some small touch up for slack UX.
- Hiding email tab if email domain is not configured
https://github.com/obot-platform/obot/issues/2729
=> Fix discord

pkg/controller/handlers/workflow/discord.go, ui/user/src/lib/components/integrations/discord/Discord.svelte
Discord controller should be using the local credentail.
https://github.com/obot-platform/obot/issues/2504
=> Fix: fix wrong credential id for discord

pkg/mcp/loader.go
It turns out that there is still a delay between the pod being ready, it being added to the service load balancer, and the IP tables being updated so that other pods can resolve it. This change goes back to a URL polling approach that we know will work.
=> fix: revert to polling the service URL for MCP servers

ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/services/chat/types.ts
=> enhance: mcp & general update improvements

ui/user/src/app.css, ui/user/src/lib/components/CopyButton.svelte, ui/user/src/lib/components/SidebarConfig.svelte, ui/user/src/lib/components/integrations/slack/Slack.svelte
=> WIP - better slack instructions

ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Steps.svelte, ui/user/src/lib/components/tasks/Task.svelte
Addresses #2917
- load task run data in read only mode and recalculate the steps and loop steps
=> fix: show steps and loop steps correctly in a task run

ui/user/src/lib/components/PageLoading.svelte, ui/user/src/lib/components/SidebarConfig.svelte, ui/user/src/lib/components/edit/ChatbotConfig.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpInfoConfig.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte, ui/user/src/lib/components/navbar/Tools.svelte, ui/user/src/lib/constants.ts, ui/user/src/lib/services/chat/mcp.ts, ui/user/src/lib/services/chat/operations.ts
Addresses #2996 
Partially addresses #2878 (loading/pending state)
Addresses #3004
=> enhance: mcp catalog ux/ui continued updates

ui/user/src/lib/components/integrations/slack/Slack.svelte
=> Fix: Open slack app page in new tab

pkg/controller/data/agent.yaml
=> Chore: get the default tool setup down to bare minimum

ui/user/src/lib/components/agents/AgentCatalog.svelte, ui/user/src/lib/components/agents/AgentWizard.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/+page.svelte, ui/user/src/routes/+page.ts, ui/user/src/routes/agents/+page.svelte, ui/user/src/routes/agents/+page.ts, ui/user/src/routes/catalog/+page.svelte
* show pending logging in state instead of unauthenticated if it goes to rendered route
* also moves fetching of mcp servers to on opening of catalog to reduce server side loading of data
* also fixes when deleting a project's mcp, it still shows (comes back with a `deleted` property, filter those out instead)
=> fix: show logging in pending state when user has logged in instead of unauthenticated content

ui/user/src/lib/components/tasks/Step.svelte
Address #2915 
- Show a confirmation dialog before deleting a loop step.
=> fix: confirm action before delete a loop step

ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/McpInfoConfig.svelte, ui/user/src/lib/components/mcp/McpSetupWizard.svelte, ui/user/src/lib/components/mcp/ProjectMcpConfig.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/components/navbar/Tools.svelte
Addresses #3024 
Addresses #3023 
Addresses #3013
Addresses #3030 
Addresses #3029
=> fix: batch of mcp server UI related bugs

ui/user/src/lib/services/chat/thread.svelte.ts
=> fix: remove jitter issue on task is completed

ui/user/src/lib/components/PageLoading.svelte
=> fix: loading mcp server readability

ui/user/src/lib/components/messages/Message.svelte
Addresses #3039 
* adds download / add to workspace files option for images outputted from mcp tools
TODO: add Loom here
=> enhance: option to download/add to workspace files for mcp tool image output

ui/user/src/lib/components/tasks/Step.svelte
=> fix: show loop step running outline on task re-run

ui/user/src/lib/components/mcp/McpCatalog.svelte
* make sure fetching of mcps happens on mount for inline 
* also account for showing preselected if preselectedMcp is set
=> fix: mcp catalog page spinner spinning forever

ui/user/src/lib/components/mcp/McpServerTools.svelte
Addresses #3031 
* show params in mcp tools
=> enhance: show params in mcp tools

pkg/controller/handlers/task/task.go
The alias and workflow name used to execute external integration
webhooks was not being set, which prevented webhook integrations from
being found when users attempted to execute them. Update the tasks
controller to set the alias and workflow name when generating webhook
resources.
Addresses https://github.com/obot-platform/obot/issues/3021
=> fix: assign generated alias and workflow name to webhooks

pkg/controller/data/agent.yaml
Updated the obot base prompt to be more verbose instructions around tone and interaction.
=> enhance: update obot base prompt

remote_catalog.json
=> Fix: metadata needs to have string values

ui/user/src/lib/components/agents/AgentWizard.svelte, ui/user/src/lib/components/mcp/McpCatalog.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte
* mcp server from catalog can be set up more than once
* change displaying 'Verified' as 'Community' instead
Addresses #3060 
Addresses #3025
=> fix: can setup mcp server more than once & community tag

ui/user/src/lib/components/mcp/McpCatalog.svelte
* sorts categories alphabetically
* removes sort by github stars and sort mcp servers alphabetically
=> chore: categories and mcp server entries alphabetically

remote_catalog.json
=> Chore: Markdown in zapier description

ui/user/src/lib/components/tasks/Step.svelte
=> fix: highlight step and loop step on delete

ui/user/src/routes/+page.svelte
=> Chore: unauthed homepage tweaks

pkg/gateway/server/llmproxy.go, pkg/invoke/invoker.go, pkg/jwt/jwt.go
Addresses https://github.com/obot-platform/obot/issues/2919
=> fix: use top-level project when getting credentials for model provider

ui/user/src/lib/components/edit/TaskItem.svelte
Addresses #2911
- Highlight the selected task.
- Highlight the selected task run.
- Highlight the task run's related task by setting the font to medium.
=> fix: highlight selected task and task run

ui/user/src/lib/components/Banner.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/agents/+page.svelte
Addresses #3083 
* show if user hasn't closed out before and if account is greater than a week old
=> enhance: add upgrade banner notification

ui/user/src/lib/components/ModelProviderCard.svelte
=> fix: show provider models in mobile devices

ui/user/src/lib/components/tasks/Step.svelte, ui/user/src/lib/components/tasks/Task.svelte
=> fix: show running indicatorsd as soon as user clicks run

ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/components/mcp/McpInfoConfig.svelte, ui/user/src/lib/markdown.ts
=> fix: mcp server descriptions w/ markdown links open in new tab

ui/user/src/lib/components/edit/ThreadModelSelector.svelte
Addresses #2879 
- show models grouped by provider
- auto scroll to the selected model
- improve models list item
=> chore: improve models selector in thread view

ui/user/src/lib/actions/tooltip.svelte.ts, ui/user/src/lib/components/InfoTooltip.svelte, ui/user/src/lib/components/edit/BuiltInCapabilities.svelte, ui/user/src/lib/components/edit/Knowledge.svelte, ui/user/src/lib/context/helperMode.svelte.ts
Addresses #3102 
* added maxWidthClass cause the tooltip seemed too small, squished with the amount of helper text
* fixed a couple helper tips not assigned correctly/showing up
=> chore: update sidebar helper text descriptions

ui/user/src/lib/components/tasks/LoopStep.svelte, ui/user/src/lib/components/tasks/Step.svelte
=> fix: use input event over value binding

ui/user/src/lib/components/ModelProviderCard.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/HostedMcpForm.svelte, ui/user/src/lib/components/mcp/RemoteMcpForm.svelte
- **fix: add missing script tag in user ui**
- **fix: ensure chatbot user mcp config is limited to existing envs and headers**
- **enhance: implement unconfigured mcp ux for top-level agents**
=> enhance: improve agent unconfigured mcp warning ux

ui/user/src/lib/components/tasks/Step.svelte
=> fix: remove left margins

ui/user/src/lib/components/tasks/Task.svelte
Addresses #2912
- remove background color from sticky header
=> fix: make design more consistent

pkg/mcp/loader.go
Issue: https://github.com/obot-platform/obot/issues/3144
=> fix: ensure allowed tools is respected when deploying to Kubernetes

ui/user/src/lib/components/ModelProviders.svelte
=> fix: adjust saving andicator size and postion

catalog/duckduckgo_search.json, catalog/mysql.json, catalog/time.json, pkg/api/handlers/mcp.go, pkg/mcp/capabilities.go, pkg/mcp/loader.go, pkg/mcp/prompts.go, pkg/mcp/resources.go, pkg/mcp/types.go, pkg/render/mcp.go
Issue: https://github.com/obot-platform/obot/issues/3160
=> Ensure deployment for capabilities

catalog/duckduckgo_search.json, catalog/mysql.json, catalog/time.json
depends on changes here: https://github.com/obot-platform/mcp-images/pull/1
=> fix: correct syntax for official uvx

ui/user/src/lib/components/ModelProviderCard.svelte
=> fix: model provider overflow issue on reconfigure

ui/user/src/lib/components/mcp/HostedMcpForm.svelte
Addresses https://github.com/obot-platform/obot/issues/3173
https://github.com/user-attachments/assets/0b3cbf7b-0b0e-4fa6-8e6b-ef6910fa6527
=> enhance: enable declaring required env vars for custom mcp servers

ui/user/src/lib/actions/clickoutside.ts, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/edit/ThreadModelSelector.svelte, ui/user/src/lib/components/mcp/McpPrompts.svelte, ui/user/src/lib/components/mcp/ProjectMcpResources.svelte, ui/user/src/lib/components/messages/Input.svelte, ui/user/src/lib/components/sidebar/ModelProviders.svelte, ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/types.ts
* adds prompt/resources to user-ui
* quick fixes with res.items making an error show up in console
* quick fix with click outside on non-`<dialog>` elements not actually triggering
=> feat: prompts/resources from mcps in user-ui

go.mod, go.sum
https://github.com/obot-platform/obot/issues/3248
=> chore: bump gptscript and nanobot to pickup streamable http init fix

pkg/mcp/capabilities.go
Issue: https://github.com/obot-platform/obot/issues/3259
=> fix: handle legacy tool bundles when getting server capabilities

go.mod, go.sum, pkg/api/handlers/mcpgateway/handler.go
Issue: https://github.com/obot-platform/obot/issues/3266
=> MCP Gateway fixes

go.mod, go.sum
Issues: https://github.com/obot-platform/obot/issues/3333, https://github.com/obot-platform/obot/issues/3334
=> chore: bump nanobot to pick up SSE client fix

pkg/api/handlers/serverinstances.go
Issue: https://github.com/obot-platform/obot/issues/3338
=> fix: admin users can connect to any multi-user MCP server

ui/user/src/lib/services/chat/operations.ts, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/mcp-servers/+page.svelte
* update ui/ux with the mcp server instances backend changes
=> fix: updated ui/ux with mcp server instance changes

apiclient/types/mcpserver.go, apiclient/types/zz_generated.deepcopy.go, catalog/firecrawl.json, catalog/gitmcp.json, pkg/api/handlers/mcp.go, pkg/storage/openapi/generated/openapi_generated.go, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/services/admin/types.ts, ui/user/src/lib/services/chat/types.ts
- Surface tool previews for catalog entries
- Add tool previews to GitMCP and Firecrawl entries
=> enhance: enable capability previews on catalog entries

ui/user/src/routes/mcp-servers/+page.svelte
* fix for hasEditableConfiguration check on hostname
=> fix: remote server hasEditableConfiguration hostname check fix

pkg/api/handlers/mcp.go, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/mcp/McpCard.svelte, ui/user/src/lib/components/mcp/ProjectMcpServerTools.svelte, ui/user/src/routes/mcp-servers/+page.svelte
**temporary** For the upcoming demo, will be swapped out once Darren's chat is ready to switch over to.
* adds chat option for users' connected mcp servers 
Loom: https://www.loom.com/share/a2a37f8401aa4922a182089c03ac33ce
=> enhance: add chat option for user connected mcp servers

ui/user/src/lib/components/mcp/McpServerTools.svelte
Fix tool preview not loading in catalog
=> Fix: fix tool prefix loading

ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/mcp/HowToConnect.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/routes/mcp-servers/+page.svelte
Some tweaks requested from Will
* nav order change
* Admin Dashboard links to /v2/admin instead of old admin-ui
* Add Chat button in the connect dialog
=> enhance: update nav links ordering & styling/href tweaks

ui/user/src/routes/v2/admin/audit-logs/+page.svelte
=> fix: users unknown on audit logs page, fetch users on afterNavigate

chart/templates/pvc.yaml
Signed-off-by: Taylor Price <tayworm@gmail.com>
=> fix: bring back erroneously deleted pvc

go.mod, go.sum, pkg/api/handlers/mcpgateway/sessionstore.go, pkg/create/create.go, pkg/services/config.go
Issue: https://github.com/obot-platform/obot/issues/3410
=> Mcp proxy auth and session fixes

ui/user/src/app.css, ui/user/src/lib/components/Table.svelte, ui/user/src/lib/services/admin/types.ts, ui/user/src/routes/v2/admin/mcp-servers/+page.svelte
=> enhance: sync errors ui for adding git source URLs

pkg/api/authz/resources.go
I was in this code working on something else, so I figured I would just fix this.
Issue: https://github.com/obot-platform/obot/issues/3420
=> fix: allow non-admin users to get prompts

ui/user/src/lib/components/admin/MarkdownInput.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/navbar/Profile.svelte
Addresses #3325 
Addresses #3390
=> fix: admin dashboard link & overview description opens links in new tab

ui/user/src/lib/actions/clickoutside.ts, ui/user/src/lib/components/Calendar.svelte, ui/user/src/lib/components/admin/AuditDetails.svelte, ui/user/src/lib/components/admin/StatBar.svelte, ui/user/src/lib/time.ts, ui/user/src/routes/v2/admin/audit-logs/+page.svelte
* adds date range selector for Audit Logs
* more user-friendly timestamp
* fix clickoutside for dialog.show() cases
=> enhance: time range selector for audit logs & readable timestamp

ui/user/src/lib/components/SensitiveInput.svelte, ui/user/src/routes/mcp-servers/+page.svelte
for https://github.com/obot-platform/obot/issues/3302
=> fix: ui: single-user/remote server config dialog: disable launch button until all required fields are filled

pkg/api/handlers/mcpgateway/auditlog.go, pkg/gateway/client/mcpauditlog.go, ui/user/src/lib/actions/clickoutside.ts, ui/user/src/lib/actions/dialogAnimation.ts, ui/user/src/lib/components/Select.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/admin/audit-logs/AuditDetails.svelte, ui/user/src/lib/components/admin/audit-logs/AuditFilters.svelte, ui/user/src/lib/components/admin/audit-logs/AuditLogDetails.svelte, ui/user/src/lib/services/admin/types.ts, ui/user/src/routes/v2/admin/audit-logs/+page.svelte
Addresses #3399
Addresses #3439 
Addresses #3431 
* adds filters to Audit Logs
* adds detail panel containing request/response information to Audit Logs
* fixes filters not properly being accounted for when applied/cleared
=> enhance: filters and request response details audit logs

pkg/controller/handlers/accesscontrolrule/accesscontrolrule.go, pkg/controller/routes.go
for https://github.com/obot-platform/obot/issues/3301
=> fix: access control rules: prune nonexistent resources

pkg/controller/handlers/accesscontrolrule/accesscontrolrule.go
for https://github.com/obot-platform/obot/issues/3495
=> fix: acr pruning: keep the selectors

pkg/api/handlers/mcp.go, pkg/api/router/router.go, pkg/mcp/loader.go, ui/user/src/lib/components/admin/McpServerK8sInfo.svelte, ui/user/src/lib/services/admin/operations.ts
This PR added an endpoint to restart k8s deployment, and also buttons in frontend to be able to refresh k8s details, events and logs. 
https://github.com/obot-platform/obot/issues/3381
=> Feat: Add deployment restart button

ui/user/src/lib/components/mcp/CatalogConfigureForm.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte
* fix for env/headers not saving on /configure & url not showing when hostname is set for remote server
* changed if config.url to config.hostname check
* make sure configureForm and error gets reset on selection of new mcp server
* make sure configureForm doesn't get reset on configureDialog close
=> fix: configure envs/headers & url not showing/saving fix

go.mod, go.sum, pkg/api/handlers/mcpgateway/clientmessagehandler.go, pkg/api/handlers/mcpgateway/oauth/mcpoauthhandler.go, pkg/mcp/client.go, pkg/mcp/loader.go, pkg/mcp/mcp.go, pkg/services/config.go, ui/user/src/lib/components/admin/audit-logs/AuditDetails.svelte
Issue: https://github.com/obot-platform/obot/issues/3497
=> enhance: distinguish Obot Chat client in the audit logs

pkg/api/authz/mcpserver.go, pkg/api/handlers/projectmcp.go, pkg/mcp/loader.go, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/services/admin/operations.ts, ui/user/src/routes/mcp-servers/+page.svelte
Issue: https://github.com/obot-platform/obot/issues/3552, https://github.com/obot-platform/obot/issues/3556, https://github.com/obot-platform/obot/issues/3557
=> Various mcp server fixes

pkg/api/handlers/projectmcp.go
Issues: https://github.com/obot-platform/obot/issues/3556, https://github.com/obot-platform/obot/issues/3560
=> fix: check whether a user has access to a multi-user MCP server

ui/user/src/routes/mcp-servers/+page.svelte
Issue: https://github.com/obot-platform/obot/issues/3567
=> fix: properly detect when a project already has a multi-user MCP server

ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/edit/EditIcon.svelte, ui/user/src/lib/services/admin/operations.ts, ui/user/src/lib/services/admin/types.ts, ui/user/src/lib/sort.ts, ui/user/src/routes/v2/admin/chat-configuration/+page.svelte, ui/user/src/routes/v2/admin/chat-configuration/+page.ts, ui/user/src/routes/v2/admin/model-providers/+page.svelte
Addresses #3470 
Related Loom: https://www.loom.com/share/d6dbda4f0df442c6ae75f0708153e9e0
=> feat: chat configuration admin page

chart/values.yaml
=> chore: enable k8s functionality when running in the chart

ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/MemoriesDialog.svelte, ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/chat/ChatSidebar.svelte, ui/user/src/lib/components/chat/ChatSidebarConfig.svelte, ui/user/src/lib/components/chat/sidebar/Threads.svelte, ui/user/src/lib/components/edit/McpServers.svelte, ui/user/src/lib/components/edit/Memories.svelte, ui/user/src/lib/components/edit/TaskItem.svelte, ui/user/src/lib/components/edit/Tasks.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/context/chatLayout.svelte.ts, ui/user/src/lib/services/chat/messages.ts, ui/user/src/lib/services/chat/thread.svelte.ts, ui/user/src/routes/mcp-servers/+page.svelte
Addresses #3535 
Addresses #3591
=> enhance: next round nav ui feedback

ui/user/src/routes/+page.svelte
=> enhance: redo the homepage, just login

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/edit/ProjectConfiguration.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/routes/v2/admin/chat-configuration/+page.svelte
=> enhance: initial chat screen revamp

ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/chat/ChatSidebarConfig.svelte, ui/user/src/lib/components/chat/ChatSidebarMcpServer.svelte, ui/user/src/lib/components/mcp/McpServerInfo.svelte, ui/user/src/lib/components/mcp/McpServerInfoAndTools.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte
=> enhance: move tabs in mcp servers overview to own tab

ui/user/src/lib/components/MemoriesDialog.svelte, ui/user/src/lib/components/chat/ChatSidebar.svelte, ui/user/src/lib/components/edit/Memories.svelte, ui/user/src/lib/components/edit/ProjectConfiguration.svelte
Addresses #3602
Addresses #3607
=> enhance: move memories to project config

ui/user/src/lib/time.ts, ui/user/src/routes/v2/admin/users/+page.svelte
Issue: https://github.com/obot-platform/obot/issues/3620#event-18888340968
=> fix: use day granularity for displaying user's last active day

ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/mcp/McpPrompts.svelte, ui/user/src/lib/components/messages/Input.svelte
* fix for incorrect prompt being selected & not going through when clicking enter
=> fix: clicking enter on prompt not selecting right prompt/going through

pkg/controller/data/agent.yaml
Issue: https://github.com/obot-platform/obot/issues/3635
=> enhance: add chat welcome message with Obot icon

ui/user/src/lib/components/mcp/SingleMultiMcpForm.svelte
https://github.com/obot-platform/obot/issues/3453
=> Fix: trim space for command and args

pkg/api/handlers/mcpcatalogs.go, ui/user/src/lib/services/admin/operations.ts, ui/user/src/routes/admin/mcp-servers/+page.svelte
https://github.com/obot-platform/obot/issues/3451
=> Fix: Don't allow duplicate URL in catalog server

ui/user/src/lib/components/Obot.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/chat/ChatSidebarConfig.svelte, ui/user/src/lib/components/chat/ChatSidebarMcpServer.svelte, ui/user/src/lib/components/chat/sidebar/Threads.svelte, ui/user/src/lib/components/edit/ProjectConfiguration.svelte, ui/user/src/lib/components/mcp/McpServerInfoAndTools.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/context/chatLayout.svelte.ts, ui/user/src/routes/mcp-servers/+page.svelte, ui/user/vite.config.ts
Addresses #3671 
Addresses #3608 
Addresses #3596 
Addresses #3595 
Addresses #3362
=> fix: chat mcp bugfixes

go.mod, go.sum, ui/user/src/lib/components/mcp/MyMcpServers.svelte
Part of https://github.com/obot-platform/obot/issues/3280
=> Auto reinitialize mcp client

pkg/api/handlers/mcp.go, pkg/mcp/details.go, ui/user/src/lib/components/admin/McpServerInstances.svelte, ui/user/src/lib/components/mcp/ContainerizedRuntimeForm.svelte, ui/user/src/lib/components/mcp/NpxRuntimeForm.svelte, ui/user/src/lib/components/mcp/UvxRuntimeForm.svelte
for https://github.com/obot-platform/obot/issues/3476
=> fix: show k8s details for remote servers, even when there are no server instances

ui/user/src/lib/actions/resize.ts, ui/user/src/lib/components/Select.svelte, ui/user/src/lib/components/Table.svelte, ui/user/src/lib/components/admin/StatBar.svelte, ui/user/src/lib/components/admin/audit-logs/AuditLogDetails.svelte, ui/user/src/lib/components/admin/usage/UsageGraphs.svelte, ui/user/src/routes/admin/audit-logs/+page.svelte, ui/user/src/routes/admin/chat-threads/+page.svelte, ui/user/src/routes/admin/mcp-servers/+page.svelte
Addresses craig's request in #3469
=> enhance: styling cleanup tables/searchbetween admin pages

ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/MemoriesDialog.svelte, ui/user/src/lib/components/ResponsiveDialog.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/chat/McpServerSetup.svelte, ui/user/src/lib/components/mcp/McpResources.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/routes/admin/chat-configuration/+page.svelte, ui/user/src/routes/mcp-servers/+page.svelte
* Addresses one Very High bugfix and multiple High minor bugfixes
Addresses #3726 
Addresses #3636 
Addresses #3452 
Addresses #3365
Addresses #3652 
Addresses #3655 
Addresses #3649 
Addresses #3367 
Addresses #3658
=> fix: ui chat/mcp related minor bugfixes

ui/user/src/lib/components/admin/audit-logs/AuditFilters.svelte
=> fix: auto close filter slideover after applying changes

ui/user/src/routes/admin/audit-logs/+page.svelte
=> rename `mcp_server_catalog_entry_name` display label

ui/user/src/routes/admin/audit-logs/AuditLogsTimeline.svelte
=> fix: set 24H timeline interval in hours instead of days

ui/user/src/lib/components/TimeInput.svelte
=> fix: set value to zero when time input is cleared

ui/user/src/lib/components/ResponsiveDialog.svelte, ui/user/src/lib/components/Thread.svelte, ui/user/src/lib/components/admin/BackLink.svelte, ui/user/src/lib/components/admin/SearchMcpServers.svelte, ui/user/src/lib/components/admin/SearchUsers.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/routes/admin/chat-threads/+page.svelte, ui/user/src/routes/admin/chat-threads/[id]/+page.svelte, ui/user/src/routes/mcp-servers/+page.svelte
* addresses 5 Very High and 1 High bugfix
Addresses #3658 
Addresses #3742 
Addresses #3739 
Addresses #3743 
Addresses #3745 
Addresses #3757
=> fix: chat & admin chat threads related bugfixes

pkg/mcp/client.go, ui/user/src/lib/services/chat/operations.ts
Issues: https://github.com/obot-platform/obot/issues/3759, https://github.com/obot-platform/obot/issues/3770
=> Fix project mcp unauth

ui/user/src/lib/components/mcp/McpCard.svelte
* per feedback from Craig/Will about mcp card stylings
=> enhance: mcp card styling

apiclient/types/mcpcatalog.go, pkg/api/handlers/mcpcatalogs.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go, pkg/storage/apis/obot.obot.ai/v1/mcpcatalog.go, pkg/storage/openapi/generated/openapi_generated.go
for https://github.com/obot-platform/obot/issues/3271
=> enhance: mcp catalog: add isSyncing field

pkg/invoke/invoker.go
If we have already retrieved the thread from the database, then don't worry about getting it again. We use a cached client in the invoker, so getting a new thread could race the cache and cause 404s.
Issue: https://github.com/obot-platform/obot/issues/3788#event-19016164750
=> fix: add thread field to thread invoke options

ui/user/src/lib/components/admin/usage/UsageFilters.svelte
Addresses https://github.com/obot-platform/obot/issues/3751
Loom: https://www.loom.com/share/43a2b9f118844342b45dc19a4860ec43?sid=4ec5532b-6410-4ba4-9eab-068de9f13b4d
=> enhance: add clear all filters button to usage filters

ui/user/src/lib/components/PageLoading.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/admin/mcp-servers/+page.svelte, ui/user/src/routes/mcp-servers/+page.svelte
Addresses #3767
Addresses #3784 
Addresses #3781 
Addresses #3780 
Addresses #3778 
Addresses #3685
=> enhance: ensure launch of mcp before showing connect & styling/sort fixes

ui/user/src/routes/admin/audit-logs/+page.svelte
Addresses #3772 
- fallback start time to 90 days ago
- fallback end time to now
=> fix: set fallback values for start/end times

ui/user/src/app.css, ui/user/src/lib/components/admin/CatalogServerForm.svelte, ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/mcp/ContainerizedRuntimeForm.svelte, ui/user/src/lib/components/mcp/McpServerTools.svelte, ui/user/src/lib/components/mcp/NpxRuntimeForm.svelte, ui/user/src/lib/components/mcp/RemoteRuntimeForm.svelte, ui/user/src/lib/components/mcp/UvxRuntimeForm.svelte, ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/lib/components/navbar/Projects.svelte, ui/user/src/lib/services/admin/types.ts, ui/user/src/routes/admin/mcp-servers/+page.svelte
Addresses #3769 
Addresses #3271 
Addresses #3705
Addresses #3708
Addresses #3784 follow-on
=> fix: projects, tool saving, & mcp form related bugfixes

pkg/bootstrap/bootstrap.go
Issue: https://github.com/obot-platform/obot/issues/3815
=> chore: always print bootstrap token if bootstrap is enabled

ui/user/src/lib/components/navbar/Profile.svelte, ui/user/src/routes/admin/mcp-servers/+page.svelte
Addresses #3271 
Also addresses #3784 safari issue (verified safari,chrome,firefox)
=> fix: change sync button text & info, add polling

docs/docs/01-overview.md
=> Chore: Update landing page docs

docs/docs/01-overview.md
Pull a simple getting started guide to the top and tweak the intro a
bit.
=> Chore: Update the docs' introduction

pkg/api/handlers/projectmcp.go
Project MCP servers now just point to user MCP servers, so they don't have parameters.
Issue: https://github.com/obot-platform/obot/issues/3856
=> fix: stop checking for missing paramters for project MCP servers

ui/user/src/lib/components/admin/audit-logs/AuditLogsTimeline.svelte
=> fix: improve tooltip position

ui/user/src/lib/components/Select.svelte, ui/user/src/lib/components/admin/usage/UsageFilters.svelte, ui/user/src/lib/diff.ts
* make diff lines account for movement
* clear all of usage filters should match audit logs
Addresses #3641
Addresses #3800
=> fix: diff accuracy on movement of lines & consistency clear all of usage filters

ui/user/src/lib/components/Editors.svelte, ui/user/src/lib/components/Layout.svelte, ui/user/src/lib/components/admin/ConfigureBanner.svelte, ui/user/src/lib/components/mcp/CatalogConfigureForm.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/services/chat/types.ts, ui/user/src/lib/utils.ts, ui/user/src/routes/admin/auth-providers/+page.ts
Addresses #3851 
Addresses #3863 
Addresses #3853 
Addresses small server alias fix on edit configuration for #3798
quick fixes: 
Addresses #3907 
Addresses #3906
=> fix: unauthenticated and mcp chat related fixes

ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/admin/usage/UsageFilters.svelte, ui/user/src/lib/components/admin/usage/UsageGraphs.svelte, ui/user/src/routes/admin/usage/+page.svelte
for https://github.com/obot-platform/obot/issues/3765
=> fix: show deleted user info in usage graphs

go.mod, go.sum
https://github.com/obot-platform/obot/issues/3924
=> Fix: bump gptscript

ui/user/src/lib/components/admin/McpServerInstances.svelte
=> fix: remove user_id parameter from audit logs navigation

pkg/gateway/server/user.go, ui/user/src/routes/admin/users/+page.svelte
* fixes admin `/users` page related bugs 
Addresses #3967 
Addresses #3981 
Addresses #3982
Addresses #3965
=> fix: admin users table fixes and session expired fix

ui/user/src/lib/components/admin/McpServerInstances.svelte
=> fix: update audit logs navigation to include mcp_id parameter

ui/user/src/lib/components/admin/audit-logs/AuditLogsTimeline.svelte
=> fix: enhance date formatting for midnight hours in audit logs timeline

ui/user/src/lib/components/PageLoading.svelte, ui/user/src/lib/components/chat/McpServerSetup.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/services/chat/operations.ts, ui/user/src/routes/admin/chat-threads/+page.svelte, ui/user/src/routes/mcp-servers/+page.svelte
Addresses #3942 
Addresses #3957 
Addresses #3970 
Addresses #3991 
Addresses #3996
=> fix: connectors and thread fixes

go.mod, go.sum
https://github.com/obot-platform/obot/issues/4050
=> Fix: update gptscript

pkg/api/server/server.go, pkg/proxy/proxy.go
for https://github.com/obot-platform/obot/issues/4037
=> fix: tell browser to delete cookie when session is invalid

pkg/api/handlers/mcpgateway/oauth/authorize.go, pkg/api/handlers/mcpgateway/oauth/handler.go, pkg/api/handlers/mcpgateway/oauth/token.go, pkg/api/router/router.go, pkg/api/server/server.go, pkg/auth/auth.go, pkg/gateway/client/authtoken.go, pkg/gateway/client/sessioncookie.go, pkg/gateway/client/user.go, pkg/gateway/db/db.go, pkg/gateway/server/tokenreview.go, pkg/gateway/types/sessioncookie.go, pkg/gateway/types/tokens.go, pkg/proxy/proxy.go, pkg/services/config.go, pkg/storage/apis/obot.obot.ai/v1/oauthauthrequest.go, pkg/storage/apis/obot.obot.ai/v1/oauthtoken.go, pkg/storage/openapi/generated/openapi_generated.go
Addresses https://github.com/obot-platform/obot/issues/4022
=> fix: refresh auth groups for requests with mcp auth tokens

chart/values.yaml, pkg/services/config.go
This change also adds this configuration to the helm chart.
=> chore: update MCP audit log batching defaults to be less conservative

ui/user/src/lib/components/Select.svelte, ui/user/src/lib/components/admin/CatalogServerForm.svelte, ui/user/src/lib/components/chat/McpServerSetup.svelte
Single:
Multi-User/Remote:
Addresses #4113 
Addresses #4078 styling fix
=> enhance: file/env var user supplied config fields ux

ui/user/src/lib/components/admin/McpServerEntryForm.svelte, ui/user/src/lib/components/mcp/CatalogConfigureForm.svelte, ui/user/src/lib/components/messages/Message.svelte, ui/user/src/lib/services/admin/operations.ts
Addresses #4057 
Addresses #4117
Addresses #4118 
For #4117 & #4118, tested following temporary instance cases:
* remote servers w/ fixed urls
* remote servers w/ hostname
* remote servers w/ hostname and resulting url requires mcp oauth
* single user catalog entries with no configuration required
* single user catalog with some sort of configuration required
* wasn't able to test with a multi-user server that has oauth, lemme know if there's one I should check with and happy to verify!
=> fix: copy paste input and temp instance fixes

ui/user/src/lib/components/chat/ChatSidebarMcpServer.svelte
=> fix: chat connector server details should use alias if available

ui/user/src/lib/components/admin/ProviderConfigure.svelte
=> chore: show optional field helper text

pkg/api/handlers/mcpgateway/sessionstore.go
There is a weird issue where the mcpSess's name goes empty. I haven't been able to reproduce it myself, but it is likely a race condition with multiple goroutines trying to update the session simultaneously.
Issue: https://github.com/obot-platform/obot/issues/4150
=> fix: stop retrying to update the session's last access time

ui/user/src/lib/components/admin/SelectMcpAccessControlRules.svelte
Issue: https://github.com/obot-platform/obot/issues/4195
=> fix: properly detect MCP catalog entries for access control

pkg/api/handlers/mcpcatalogs.go, pkg/api/handlers/mcpcatalogs_test.go
https://github.com/obot-platform/obot/issues/4194
=> Fix: normalize catalog entry name

chart/templates/_helpers.tpl, chart/templates/mcp.yaml, chart/templates/secret.yaml, chart/values.yaml, pkg/mcp/kubernetes.go, pkg/mcp/loader.go, pkg/services/config.go
Issue: https://github.com/obot-platform/obot/pull/4231
=> feat: add basic image pull secret support for MCP images

aws-encryption.yaml, gcp-encryption.yaml, pkg/gateway/client/auditlogpersister.go, pkg/gateway/client/mcpauditlog.go, pkg/gateway/types/mcpauditlog.go
Issue: https://github.com/obot-platform/sensitive-issues/issues/39
=> feat: encrypt the sensitive parts of MCP audit logs

pkg/api/handlers/mcpgateway/oauth/client.go, pkg/gateway/client/user.go
Issue: https://github.com/obot-platform/obot/issues/4226
=> chore: bump OAuth client secret expiration to 1 week

tools/package-chrome.sh
Ran into an issue building locally. This resolved it.
=> Fix: Update apk before adding chromium

ui/user/src/lib/components/admin/audit-logs/AuditLogs.svelte
Addresses #4183
- Make table cells resizable for better UX.
- Cell content will be truncated by default.
- Each table cell has a min width.
=> feat: make table cells resizable

pkg/controller/handlers/mcpcatalog/github.go, pkg/controller/handlers/mcpcatalog/mcpcatalog.go
Obot will now skip all patterns that match entries in .ignoreobotcatalgs file.
=> enhance: add ignore list for MCP catalog sync

ui/user/src/lib/actions/dialogAnimation.ts, ui/user/src/lib/components/ResponsiveDialog.svelte, ui/user/src/lib/components/chat/McpServerRequirements.svelte, ui/user/src/lib/components/edit/ProjectConfiguration.svelte, ui/user/src/lib/components/mcp/CatalogConfigureForm.svelte
=> fix: mcp server requirements dialog fix

ui/user/src/routes/profile/+page.svelte
https://github.com/obot-platform/obot/issues/4308
=> Fix: fix role display issue in account page

pkg/controller/handlers/threads/threads.go
Addresses https://github.com/obot-platform/obot/issues/4344
=> fix: retain task runs on project share upgrade

ui/user/src/lib/components/agents/AgentCopy.svelte, ui/user/src/lib/components/templates/TemplateConfig.svelte, ui/user/src/lib/services/chat/types.ts, ui/user/src/routes/t/[id]/+page.svelte, ui/user/src/routes/t/[id]/+page.ts
Addresses:
- https://github.com/obot-platform/obot/issues/4301
- https://github.com/obot-platform/obot/issues/4289
- https://github.com/obot-platform/obot/issues/4334
=> Fix share verbiage and display info

pkg/mcp/docker.go
Instead, wait for them to be ready.
Issue: https://github.com/obot-platform/obot/issues/4338
=> fix: stop removing containers in a created state

.gitignore, go.mod, go.sum, pkg/api/handlers/mcpgateway/clientmessagehandler.go, pkg/api/handlers/mcpgateway/handler.go
Issue: https://github.com/obot-platform/obot/issues/4210
=> fix: add support for server-to-client MCP requests

pkg/gateway/client/client.go
If a user has been marked as an explicit admin and owner, then ensure they are marked as an owner.
=> fix: prefer explicit owner over admin

ui/user/src/lib/components/admin/SelectMcpAccessControlRules.svelte
=> fix: remove 'Skip Step' button from access control rules dialog

pkg/api/authz/authz.go, pkg/api/authz/resources.go
Additionally, ensure users can trigger updates for their MCP servers
=> fix: add admin authorization for MCP servers

pkg/api/handlers/mcp.go
Issue: https://github.com/obot-platform/obot/issues/4435
=> fix: give auditor access to server details and logs

ui/user/src/lib/components/table/Table.svelte, ui/user/src/lib/components/table/TableHeader.svelte, ui/user/src/routes/admin/access-control/+page.svelte, ui/user/src/routes/admin/chat-threads/+page.svelte, ui/user/src/routes/admin/filters/+page.svelte, ui/user/src/routes/admin/task-runs/+page.svelte, ui/user/src/routes/admin/tasks/+page.svelte, ui/user/src/routes/admin/users/+page.svelte
Addresses #4420 
* adds table column filters to other admin pages with just table data (not including Audit Logs)
- Filters
- Chat Threads
- Tasks
- Task Runs 
- Users
* removes the Filter sidebar with the replacement of table column filters
=> enhance: add table columns to applicable admin pages

ui/user/src/lib/components/chat/McpServerRequirements.svelte, ui/user/src/lib/components/mcp/McpServerInfoAndTools.svelte, ui/user/src/lib/components/mcp/MyMcpServers.svelte, ui/user/src/lib/services/admin/types.ts, ui/user/src/lib/services/chat/types.ts
https://github.com/obot-platform/obot/issues/4148
=> Fix: Don't update url for mcp server that use url template

ui/user/src/lib/components/admin/McpServerEntryForm.svelte
Issue: https://github.com/obot-platform/obot/issues/4468
=> fix: list users for auditors

pkg/invoke/invoker.go
Issue: https://github.com/obot-platform/obot/issues/4491
=> fix: ensure system tokens have basic group

pkg/api/authz/resources.go, pkg/api/handlers/mcp.go, pkg/api/router/router.go
for https://github.com/obot-platform/obot/issues/4375
=> fix: allow PUPs to update servers created from their catalog entries

ui/user/src/lib/components/SensitiveInput.svelte
=> refactor: make sensitive textarea feels more native

ui/user/src/lib/components/admin/AccessControlRuleForm.svelte
=> fix: prevent loading users and groups in creation mode

pkg/api/handlers/mcp.go, pkg/api/handlers/mcpcatalogs.go, ui/user/src/lib/context/admin/mcpServerAndEntries.svelte.ts, ui/user/src/lib/services/admin/operations.ts
for https://github.com/obot-platform/obot/issues/4421
=> fix: list everything in the admin dashboard, bypassing ACR checks
